- raven-log4j/README.md
> Update documentation to extraTags.

- docs/modules/log4j.rst
- docs/modules/log4j2.rst
- docs/modules/logback.rst
- raven-log4j/src/main/java/net/kencochrane/raven/log4j/SentryAppender.java
- raven-log4j2/README.md
- raven-log4j2/src/main/java/net/kencochrane/raven/log4j2/SentryAppender.java
- raven-log4j2/src/test/resources/log4j2-integration.xml
- raven-logback/README.md
- raven-logback/src/main/java/net/kencochrane/raven/logback/SentryAppender.java
> Correct all occurances of invalid mappedTags usage

- raven/src/main/java/net/kencochrane/raven/marshaller/json/StackTraceInterfaceBinding.java
- raven/src/test/java/net/kencochrane/raven/marshaller/json/StackTraceInterfaceBindingTest.java
- raven/src/test/resources/net/kencochrane/raven/marshaller/json/StackTrace1.json
- raven/src/test/resources/net/kencochrane/raven/marshaller/json/StackTrace2.json
- raven/src/test/resources/net/kencochrane/raven/marshaller/json/StackTrace3.json
> Add filename to `StackTraceInterfaceBinding`.

- README.md
Java APIs used support the Java net properties
Fixes #176
Signed-off-by: Jesse Szwedko <jesse.szwedko@getbraintree.com>
> Add notes to README about HTTP(S) proxies

- CHANGES
- raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
This is from: https://github.com/getsentry/raven-java/pull/174
But I left out the `printf` bits, which I think needs a separate explanation.
> Add setters for dsn and tags in jul.

- CHANGES
- raven-log4j2/README.md
- raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java
Tweaked and extended https://github.com/getsentry/raven-java/pull/189
> Refer to Thread Context instead of MDC in Log4j2.

- pom.xml
- raven-appengine/pom.xml
- raven-log4j2/pom.xml
- raven-logback/pom.xml
Tested with examples. Not sure if we have strong opinions on this (or follow any guidelines in the clients for other languages)...?
No major upgrades, just bumping patch releases.
> Bump dependencies.

- .gitattributes
> Use union merge strategy for `CHANGES`.

- pom.xml
- raven-log4j/src/main/java/com/getsentry/raven/log4j/SentryAppender.java
- raven/src/main/java/com/getsentry/raven/event/Event.java
- src/checkstyle/checkstyle.xml
> Catch possible `NullPointerException` in Log4j appender.

- CHANGES
- raven/src/main/java/com/getsentry/raven/event/Breadcrumb.java
- raven/src/main/java/com/getsentry/raven/event/BreadcrumbBuilder.java
- raven/src/main/java/com/getsentry/raven/event/Event.java
- raven/src/main/java/com/getsentry/raven/event/EventBuilder.java
- raven/src/main/java/com/getsentry/raven/marshaller/json/JsonMarshaller.java
- raven/src/test/java/com/getsentry/raven/marshaller/json/JsonMarshallerTest.java
- raven/src/test/resources/com/getsentry/raven/marshaller/json/jsonmarshallertest/testBreadcrumbs.json
@tkaemming this is the breakout of "simple" breadcrumb support.
> Add (manual) support for breadcrumbs to event objects.

- CHANGES
- raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java
- raven/src/main/java/com/getsentry/raven/Raven.java
- raven/src/main/java/com/getsentry/raven/RavenContext.java
- raven/src/main/java/com/getsentry/raven/event/Breadcrumbs.java
- raven/src/main/java/com/getsentry/raven/event/helper/ContextBuilderHelper.java
- raven/src/main/java/com/getsentry/raven/util/CircularFifoQueue.java
- raven/src/test/java/com/getsentry/raven/RavenContextTest.java
- src/checkstyle/suppressions.xml
This builds on https://github.com/getsentry/raven-java/pull/216
> Add RavenContext and Breadcrumbs helper.

- CHANGES
- README.md
- raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java
- raven/src/main/java/com/getsentry/raven/connection/HttpConnection.java
#176 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/226)
> Add ability to set HTTP proxy in DSN.

- raven/src/main/java/com/getsentry/raven/Raven.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/235)
> Drop level of EventBuilderHelper addition/removal logging to debug.

- raven/README.md
- raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/239)
> Add `setExtraTags` to JUL handler.

- CHANGES
- raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java
Cleanup of https://github.com/getsentry/raven-java/pull/257
> Add raven.async.queue.overflow option

- CHANGES
- raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java
- raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java
- raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
Finished up https://github.com/getsentry/raven-java/pull/263
@tkaemming this is a quick one to skim if you'd like
> Loosen permission on some Appender/Handler methods to allow for easier overriding.

- raven/src/main/java/com/getsentry/raven/event/Breadcrumb.java
- raven/src/test/java/com/getsentry/raven/buffer/DiskBufferTest.java
> Make Breadcrumbs serializable.

- docs/modules/raven.rst
fix "Bad level value for property: .level"
> update docs about .level

- CHANGES
- raven-android/src/main/java/com/getsentry/raven/android/Raven.java
- raven-android/src/test/java/com/getsentry/raven/android/RavenIT.java
- raven-android/src/test/java/com/getsentry/raven/android/RavenITActivity.java
This makes minor cleanup to #290, plus add test and `CHANGES`.
> Allow use of custom AndroidRavenFactory

- CHANGES
- raven-log4j/src/main/java/com/getsentry/raven/log4j/SentryAppender.java
- raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java
- raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java
- raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
via https://github.com/getsentry/raven-java/pull/287
> Fix race condition, ensuring Raven initialization is synchronized in appenders. (thanks OutOfBrain)

- raven/src/main/java/com/getsentry/raven/time/Clock.java
- raven/src/main/java/com/getsentry/raven/time/FixedClock.java
- raven/src/main/java/com/getsentry/raven/time/SystemClock.java
- raven/src/test/java/com/getsentry/raven/time/ClockTest.java
> Add Clock interface for testing.

- raven/src/main/java/com/getsentry/raven/event/helper/ContextBuilderHelper.java
- raven/src/test/java/com/getsentry/raven/event/BreadcrumbTest.java
Issue: #314
This is currently just a failing test, need to decide what to do.
> Don't squash existing breadcrumbs on an EventBuilder object

- raven-android/src/main/java/com/getsentry/raven/android/event/helper/AndroidEventBuilderHelper.java
This renders like so,
Which isn't amazing, but I think the `android_id` part is important so people realize what it is, and so  if/when they set their own ID it's clear they're different...
#329
> Add a default user id on Android.

- CHANGES
- pom.xml
Well, since Jackson isn't going anywhere yet we should update it so we keep ensuring tests work well against the latest stable (plus bugfixes and whatnot).
Tests pass, I'm not sure [these kind of changes](https://github.com/getsentry/raven-java/commit/90fb5a1a0dd93c9ba990f62af94fd6f4d267dd9f) are worth a review or not? I guess maybe to catch things like `CHANGES`. 😬
> Bump Jackson.

- docs/modules/android.rst
Better init example, providing the DSN on the Java which I think is much more clear to most.
> Minor reorganization/cleanup of Android documentation.

- docs/context.rst
- docs/index.rst
- docs/modules/android.rst
- docs/modules/log4j.rst
- docs/modules/log4j2.rst
- docs/modules/logback.rst
- docs/modules/raven.rst
- docs/usage.rst
Still 😷, I hope this makes some sense.
> Add Breadcrumb documentation.

- docs/context.rst
- docs/modules/android.rst
- docs/usage.rst
Basic overhaul to show usages of static `Sentry` API.
> Update documentation for 1.0.

- sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
- sentry/src/main/java/io/sentry/event/interfaces/DebugMetaInterface.java
- sentry/src/main/java/io/sentry/marshaller/json/DebugMetaInterfaceBinding.java
- sentry/src/test/java/io/sentry/event/EventBuilderTest.java
- sentry/src/test/java/io/sentry/event/interfaces/DebugMetaInterfaceTest.java
- sentry/src/test/java/io/sentry/marshaller/json/DebugMetaInterfaceBindingTest.java
- sentry/src/test/resources/io/sentry/marshaller/json/Proguard.json
This PR should add `debug_meta` interface to events for ProGuard support.
> Debug Meta Interface

- CHANGES
- sentry/src/main/java/io/sentry/event/User.java
- sentry/src/main/java/io/sentry/event/UserBuilder.java
- sentry/src/main/java/io/sentry/event/helper/ContextBuilderHelper.java
- sentry/src/main/java/io/sentry/event/interfaces/UserInterface.java
- sentry/src/main/java/io/sentry/marshaller/json/UserInterfaceBinding.java
- sentry/src/test/java/io/sentry/event/UserTest.java
- sentry/src/test/java/io/sentry/marshaller/json/UserInterfaceBindingTest.java
- sentry/src/test/resources/io/sentry/marshaller/json/User1.json
For #336 
---
Pretty basic stuff here.
> Add ability to set extra data on the ``UserInterface``.

- CHANGES
- sentry/src/main/java/io/sentry/event/interfaces/SentryStackTraceElement.java
> Make SentryStackTraceElement Serializable.

- sentry/src/main/java/io/sentry/context/Context.java
For #434. 
---
Immutable fields are simply volatile because we desire visibility. Anything touching the Breadcrumbs CircularFifoQueue is synchronized. In addition, in `getBreadcrumbs` we now return a copied list so that the underlying crumbs aren't altered by another thread.
> Make operations on Context threadsafe.

- sentry-android/src/main/java/io/sentry/android/AndroidSentryClientFactory.java
We should allow for `noop` DSNs and simply warn the user. We also can't depend on the existing `logger` call about DSN configuration (in `Dsn.java`) because most Android applications don't use a SLF4J implementation at all and therefore won't see anything.
Related to #457.
> No longer throw an exception for a noop DSN on Android.

- sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
> Check that /proc/version can be read on Android.

- CHANGES
- sentry/src/main/java/io/sentry/event/Event.java
- sentry/src/test/java/io/sentry/event/EventTest.java
> Fix for serializing null values in Event extras map.

- sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
> Pin Android ``app_start_time`` locale to English.

- docs/migration.rst
missing ending quote in capture function
> Fix missing quote

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
This changes the Gradle plugin from only checking the first variant with
`variant.outputs.first()` to iterating over all variants. It now
uploads/links multiple version code releases to the same DSym files:
https://developer.android.com/studio/build/configure-apk-splits.html#configure-APK-versions
In addition, we now check multiple well known places for the
AndroidManifest.xml file, and print an error if none is found. This
change also fixed the plugin for my example project.
---
I did a single app build for release and checked that my multiple version codes were linked to the DSym on the backend.
```
[v.build for v in VersionDSymFile.objects.filter(dsym_file=dsym)]
[u'4002', u'3002', u'1002', u'2002', u'2', u'1']
```
4xxx is x86_64, 3xxx is x86, etc.
Automated testing remains unsolved …
> Handle multi-APK projects with different version codes.

- CHANGES
- sentry/src/main/resources/META-INF/web-fragment.xml
> Add web-fragment.xml to prevent classpath scanning.

- sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
- sentry/src/test/java/io/sentry/DefaultSentryClientFactoryTest.java
> Create a noop sentry client when the user provides bad configuration

- CHANGES
- sentry/src/main/java/io/sentry/connection/AsyncConnection.java
> Pass MDC context down to AsyncConnection worker threads.

- sentry-android-gradle-plugin/.gitignore
- sentry-android-gradle-plugin/build.gradle
- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> Fix Android Gradle Plugin for 3.3.0+

- CHANGES
- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPluginExtension.groovy
> Allow users to provide a custom  in the Sentry Gradle Plugin.

- pom.xml
- sentry-spring-boot-starter/pom.xml
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- sentry-spring-boot-starter/src/main/resources/META-INF/spring.factories
- sentry-spring-boot-starter/src/test/java/io/sentry/spring/autoconfigure/SentryAutoConfigurationTest.java
This new module add all the configuration needed to integrate web
projects with sentry.
> Add new spring boot starter module

- sentry-android/src/main/java/io/sentry/android/AndroidSentryClientFactory.java
Removed DSN URI from logs in Android module.
Issue #649
> Removed offending DSN info from Android logs

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> Gradle Plugin: Replace execute with finalizedBy

- sentry/src/main/java/io/sentry/dsn/Dsn.java
- sentry/src/main/java/io/sentry/util/Util.java
- sentry/src/test/java/io/sentry/dsn/DsnTest.java
Resolved issued described here:
https://github.com/getsentry/sentry-java/issues/695
> resolved issue number 695

- pom.xml
Supersedes #635 (thanks to @mbyczkowski for raising it)
> [JACKSON] Upgrade to version 2.9.9

- sentry/src/main/java/io/sentry/marshaller/json/StackTraceInterfaceBinding.java
> [STACKTRACE] Fix checkstyle

- sentry-android-gradle-plugin/build.gradle
- sentry-android-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
Follows #724
@nesterov-n @realdadfish  The comments you've made on #724 have been addressed.
Could you please verify?
> fix(gradle): gradle plugin on AGP version 3.4

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> fix: Look for sentry.properties on flavor folder

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> fix: AGP splits

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> fix: gradle plugin find dex task

- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/test/java/io/sentry/SentryClientTest.java
> fix: SentryClient overrides event with default data

- sentry/src/main/java/io/sentry/config/ContextClassLoaderResourceLoader.java
> fix: some threads dont have contextClassLoader

- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/test/java/io/sentry/SentryClientTest.java
> Don't attempt to send events for null payloads.

- sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
> fix: Huawei `getPackageInfo` throws

- sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java
- sentry/src/test/java/io/sentry/marshaller/json/JsonMarshallerTest.java
- sentry/src/test/resources/io/sentry/marshaller/json/jsonmarshallertest/testBreadcrumbs.json
* resolves #776
Still need to make sure the server is happy with milliseconds in the ISO format.
> feat: Milliseconds to breadcrumbs

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryProguardConfigTask.groovy
> fix(proguard): Keep exception type names

- sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> Support App Bundles (aab) and AGP 3.6.x, bug fix

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-samples/sentry-samples-android/build.gradle.kts
feat: support android 11
https://github.com/getsentry/sentry-android/pull/551
> feat: support android 11

- .gitignore
- sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt
> fix: add target to gitignore

- .github/workflows/release-drafter.yml
feat: create release drafter GH action
create release was not migrated from the repo automatically, let's move it from GH App to GH action
> feat: create release drafter GH action

- .github/ISSUE_TEMPLATE/bug_report.md
enha: Update bug_report.md to support the Java integrations
it is very Android specific right now
> enha: Update bug_report.md to support the Java integrations

- sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SampleServlet.java
- sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SentryInitializer.java
fix: spotless samples
identation is wrong for some samples
> fix: spotless samples

- sentry-samples/sentry-samples-console/README.md
- sentry-samples/sentry-samples-console/build.gradle.kts
- sentry-samples/sentry-samples-log4j2/README.md
- sentry-samples/sentry-samples-log4j2/build.gradle.kts
- sentry-samples/sentry-samples-logback/README.md
- sentry-samples/sentry-samples-logback/build.gradle.kts
- sentry-samples/sentry-samples-logback/src/main/resources/logback.xml
- sentry-samples/sentry-samples-servlet/README.md
- sentry-samples/sentry-samples-spring-boot/README.md
- sentry-samples/sentry-samples-spring/README.md
Add readme to samples.
Users browsing the repository should know how to build/run samples.
> Add readme to samples.

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
Bump: Android Gradle Plugin 4.0.2
fixes fixes including one that I've reported it :)
> Bump: Android Gradle Plugin 4.0.2

- sentry/src/main/java/io/sentry/Hub.java
Fixes 2 typos in logger messages
> fix log messages typos

- CHANGELOG.md
- sentry/src/main/java/io/sentry/MainEventProcessor.java
- sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
Set environment to "production" by default.
Fixes #1003
Unit tests.
> Set environment to "production" by default.

- README.md
> Add note for on prem users

- build.gradle.kts
- scripts/.mvn/wrapper/MavenWrapperDownloader.java
- scripts/release.kts
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/sample/MainActivity.java
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpSentryClient.java
- sentry/src/main/java/io/sentry/NoOpSerializer.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
- sentry/src/main/java/io/sentry/UserFeedback.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
Just executed spotlessApply to fix CI for #1019
> fix: spotless

- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/SamplingContext.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryTransaction.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/main/java/io/sentry/TraceContext.java
- sentry/src/main/java/io/sentry/TracingSampler.java
- sentry/src/main/java/io/sentry/TransactionContexts.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/SentryTransactionTest.kt
- sentry/src/test/java/io/sentry/TracingSamplerTest.kt
- sentry/src/test/java/io/sentry/TransactionContextsTest.kt
Sampling capabilities for performance feature.
> Add performance sampling.

- .craft.yml
- .github/workflows/build.yml
#951 
With this we just need to get the info from #952 and add a craft target `bintray`
> name artifact so craft can find it

- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry-samples/sentry-samples-android/src/main/cpp/native-sample.cpp
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/MainActivity.java
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/MyApplication.java
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/NativeSample.java
https://github.com/getsentry/sentry-java/blob/4b8b7d7d11e216153ec7fd2619490894db02ef7e/sentry/src/main/java/io/sentry/SentryStackTraceFactory.java#L40-L44
the Android samples stack traces were being omitted.
sample
running it
> Fix: Rename Android samples package

- sentry/src/main/java/io/sentry/SentryEvent.java
> Fixed a javadoc typo

- CHANGELOG.md
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
Autoconfigure traces callback in Spring Boot integration.
This will simplify providing custom tracing callback in Spring Boot autoconfiguration.
Integration test.
> Enhancement: Autoconfigure traces callback in Spring Boot integration.

- CHANGELOG.md
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpan.java
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanAdvice.java
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransaction.java
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentrySpanAdviceTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTransactionAdviceTest.kt
Change "op" to "operation" in @SentrySpan and @SentryTransaction
We changed it already on `Span` and `SentryTransaction` classes, for the sake of consistency should be changed also in annotations.
> Change "op" to "operation" in @SentrySpan and @SentryTransaction

- Makefile
Call `make format` to format the code with spotless.
We already have `make checkFormat`.
Calling it on the command line.
> build: Add make format to Makefile

- CHANGELOG.md
- sentry-servlet/src/main/java/io/sentry/servlet/SentryRequestHttpServletRequestProcessor.java
- sentry-spring/src/main/java/io/sentry/spring/SentryRequestResolver.java
- sentry/src/main/java/io/sentry/Session.java
- sentry/src/main/java/io/sentry/SessionAdapter.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SessionAdapterTest.kt
Fixes and Tests for Session serialization and deserialization
Issues with status, release and ip_address serialization
> Fixes and Tests for Session serialization and deserialization

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/config/PropertiesProvider.java
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/UncaughtExceptionHandlerIntegrationTest.kt
- sentry/src/test/java/io/sentry/config/PropertiesProviderTest.kt
Read `uncaught.handler.enabled` property from the external configuration.
Fixes #1112 
Unit tests.
> Read `uncaught.handler.enabled` property from the external configuration

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ISpan.java
- sentry/src/main/java/io/sentry/NoOpTransaction.java
- sentry/src/main/java/io/sentry/SentryTransaction.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/test/java/io/sentry/SentryTransactionTest.kt
- sentry/src/test/java/io/sentry/SpanTest.kt
Add overload for `transaction/span.finish(SpanStatus)`.
Fixes #1180
Unit tests.
> Add overload for `transaction/span.finish(SpanStatus)`.

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
Bump Gradle to 6.8.1 and AGP to 4.1.2
be sure they are compatible with the latest stable versions and get the improvements from it
> Bump Gradle to 6.8.1 and AGP to 4.1.2

- README.md
Update README to reflect new links and remove dup links
Added new links, fixed versions, and removed dup. links (which is already under Resources)
> Update README to reflect new links and remove dup links

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Hub.java
Fix: Remove misleading error logs
Fixes #1221
> Fix: Remove misleading error logs

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry/src/main/java/io/sentry/protocol/Contexts.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/protocol/ContextsTest.kt
Bump: sentry-native to 0.4.7
https://github.com/getsentry/sentry-native/pull/470
OS contexts are merged now because of https://github.com/getsentry/sentry-native/pull/467
> Bump: sentry-native to 0.4.7

- .craft.yml
- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdkUtil.java
- sentry-android-ndk/src/test/java/io/sentry/android/ndk/SentryNdkUtilTest.kt
- sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberIntegration.kt
- sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberIntegrationTest.kt
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
- sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry-spring/src/main/java/io/sentry/spring/SentryHubRegistrar.java
- sentry-spring/src/test/kotlin/io/sentry/spring/EnableSentryTest.kt
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/resources/envelope_session_sdkversion.txt
See also: https://github.com/getsentry/sentry-release-registry/pull/41
> Add release registry target to craft

- CHANGELOG.md
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
- sentry-spring/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Do not execute any extra expressions when Hub is disabled.
Fixes #1264
> Optimize SentryTracingFilter when hub is disabled.

- buildSrc/src/main/java/Config.kt
Bump Jacoco version for Java 15 compatibility.
Older Jacoco version fails to run test coverage with Java 15.
> Bump Jacoco version for Java 15 compatibility.

- CHANGELOG.md
- sentry-jul/api/sentry-jul.api
- sentry-jul/build.gradle.kts
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
Fix JUL integration SDK name.
Fixes #1293
> Fix JUL integration SDK name.

- buildSrc/src/main/java/Config.kt
> ref: contact through sdk email

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
Fix: Use the bindToScope correctly
Bugs by #1313
> Fix: Use the bindToScope correctly

- gradle/wrapper/gradle-wrapper.properties
Bump Gradle 6.8.3
https://github.com/gradle/gradle/releases/tag/v6.8.3
> Bump Gradle 6.8.3

- README.md
After running a few tests, everything worked out as expected
> Remove signal handlers side by side limitation from README

- CHANGELOG.md
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentrySpanAdviceTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/test/java/io/sentry/GsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/SpanTest.kt
Feat: configure max spans per transaction
Fixes #1356
> Feat: configure max spans per transaction

- .github/workflows/codeql-analysis.yml
> codeql workflow

- README.md
> readme: add missing packages

- sentry-android-okhttp/build.gradle.kts
- sentry-android-timber/build.gradle.kts
Fix https://github.com/getsentry/sentry-java/issues/1392
> Migrate detekt config to latest version

- .github/workflows/build.yml
- .github/workflows/check-formatting.yml
- .github/workflows/generate-javadocs.yml
Fix https://github.com/getsentry/sentry-java/issues/1377
> Bump Java actions

- .github/CODEOWNERS
Reverts getsentry/sentry-java#1284
> Revert "Remove bruno from codeowners"

- .github/workflows/codeql-analysis.yml
We're building the in the line below
> remove auto build

- sentry/src/main/java/io/sentry/adapters/CollectionAdapter.java
- sentry/src/main/java/io/sentry/adapters/ContextsDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/ContextsSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/DateDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/DateSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/MapAdapter.java
- sentry/src/main/java/io/sentry/adapters/OrientationDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/OrientationSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SentryIdDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SentryIdSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SentryLevelDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SentryLevelSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SpanIdDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SpanIdSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SpanStatusDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/SpanStatusSerializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/TimeZoneDeserializerAdapter.java
- sentry/src/main/java/io/sentry/adapters/TimeZoneSerializerAdapter.java
Part of https://github.com/getsentry/sentry-java/pull/1439
> Add nullability annotations to `adapters` package.

- sentry/src/main/java/io/sentry/Stack.java
- sentry/src/test/java/io/sentry/StackTest.kt
Fix Stack clone
Stack items were cloned in wrong order.
Unit tests.
> Fix Stack clone

- sentry-samples/sentry-samples-servlet/README.md
> Polish servlet sample readme.

- buildSrc/src/main/java/Config.kt
- sentry/src/main/java/io/sentry/NoOpTransaction.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/protocol/SdkVersion.java
- sentry/src/main/java/io/sentry/protocol/SentryPackage.java
> Bump: build plugins and test dependencies

- .craft.yml
> add missing craft targets

- CHANGELOG.md
- scripts/release.kts
> Fix: Sources and Javadoc artifacts were mixed up

- .craft.yml
- README.md
> Add sentry-android-fragment to release registry and readme

- buildSrc/src/main/java/Config.kt
- sentry-samples/sentry-samples-spring/build.gradle.kts
> Bump gretty gradle

- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle 7.1

- .github/workflows/build.yml
> ci(releases): Run CI on release branches

- .github/workflows/generate-javadocs.yml
Fix https://github.com/getsentry/sentry-java/issues/1578
> Do not publish javadocs for pre releases

- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
- sentry-servlet/src/test/kotlin/io/sentry/servlet/SentryRequestHttpServletRequestProcessorTest.kt
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/mvc/SentrySpringIntegrationTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/webflux/SentryWebfluxIntegrationTest.kt
- sentry/src/main/java/io/sentry/OptionsContainer.java
- sentry/src/test/java/io/sentry/config/PropertiesProviderTest.kt
> Fix lint tests

- buildSrc/src/main/java/Config.kt
> Bump AGP to 4.2.2

- sentry/src/main/java/io/sentry/SpanContext.java
> docs: Fix typo in code doc for SpanContext

- buildSrc/src/main/java/Config.kt
> Clean ded code shouldSignArtifacts

- .craft.yml
> Add sentry-bom registry target

- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-okhttp/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-apache-http-client-5/build.gradle.kts
- sentry-jul/build.gradle.kts
- sentry-kotlin-extensions/build.gradle.kts
- sentry-log4j2/build.gradle.kts
- sentry-logback/build.gradle.kts
- sentry-openfeign/build.gradle.kts
- sentry-samples/sentry-samples-android/build.gradle.kts
- sentry-samples/sentry-samples-console/build.gradle.kts
- sentry-samples/sentry-samples-jul/build.gradle.kts
- sentry-samples/sentry-samples-log4j2/build.gradle.kts
- sentry-samples/sentry-samples-logback/build.gradle.kts
- sentry-samples/sentry-samples-openfeign/build.gradle.kts
- sentry-samples/sentry-samples-servlet/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot/build.gradle.kts
- sentry-samples/sentry-samples-spring/build.gradle.kts
- sentry-servlet/build.gradle.kts
- sentry-spring-boot-starter/build.gradle.kts
- sentry-spring/build.gradle.kts
- sentry-test-support/build.gradle.kts
- sentry/build.gradle.kts
- settings.gradle.kts
Type-safe project accessors in Gradle config.
Fixes #1452.
Since this is an incubating feature, I am not convinced we should use it. I does not seem to hurt but also does not seem to bring much value.
> Type-safe project accessors in Gradle config.

- .craft.yml
No idea if it affects something, but it probably does?
> fix: maven artifacts location

- .craft.yml
> Add Openfeign module to Craft.

- CHANGELOG.md
> Bump: sentry-native to 0.4.12

- .github/workflows/build.yml
- buildSrc/src/main/java/Config.kt
> Build against different JVM versions

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-okhttp/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-samples/sentry-samples-android/build.gradle.kts
Fix https://github.com/getsentry/sentry-java/issues/1664
> Skip debug build when CI runs

- .github/workflows/codeql-analysis.yml
Fix https://github.com/getsentry/sentry-java/issues/1662
> Improve Code QL CI

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/JsonObjectDeserializer.java
- sentry/src/main/java/io/sentry/JsonObjectReader.java
- sentry/src/main/java/io/sentry/protocol/DebugImage.java
- sentry/src/main/java/io/sentry/protocol/DebugMeta.java
- sentry/src/main/java/io/sentry/protocol/SdkInfo.java
- sentry/src/test/java/io/sentry/JsonObjectReaderTest.kt
- sentry/src/test/java/io/sentry/JsonObjectSerializerTest.kt
- sentry/src/test/java/io/sentry/JsonUnknownSerializationTest.kt
- sentry/src/test/java/io/sentry/UserFeedbackSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/AppSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/BrowserSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/DebugImageSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/DebugMetaSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/DeviceSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/GpuTests.kt
- sentry/src/test/java/io/sentry/protocol/OeratingSystemSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SdkInfoSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryRuntimeSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SpanContextSerializationTest.kt
- sentry/src/test/resources/gson/debug_image.json
- sentry/src/test/resources/gson/debug_meta.json
- sentry/src/test/resources/gson/sdk_info.json
- Implement serialization/deserialization for `SdkInfo`
- Implement serialization/deserialization for `DebugImage`
- Implement serialization/deserialization for `DebugMeta`
- Added `nextList` to `JsonObjectReader`
- Added tests.
> Vendor JSON: DebugMeta

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/Mechanism.java
- sentry/src/main/java/io/sentry/protocol/SentryException.java
- sentry/src/test/java/io/sentry/JsonUnknownSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/MechanismSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryExceptionSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryStackTraceSerializationTest.kt
- sentry/src/test/resources/gson/mechanism.json
- sentry/src/test/resources/gson/sentry_exception.json
- sentry/src/test/resources/gson/sentry_stack_trace.json
- Implement serialization/deserialization for `Mechanism`
- Implement serialization/deserialization for `SentryException`
- Added tests.
> Vendor JSON: SentryException

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
Include unfinished spans in transaction
Fixes #1690.
Unit tests.
> Feat: Include unfinished spans in transaction.

- README.md
I also reordered things so it's newest to oldest
> new blog post on readme

- sentry/src/main/java/io/sentry/Hub.java
Ref: Check if `options.isTracingEnabled` before calling `Hub#assignTraceContext`
Fixes #1710
> Ref: Check if `options.isTracingEnabled` before calling `Hub#assignTraceContext`

- buildSrc/src/main/java/Config.kt
- sentry/src/main/java/io/sentry/vendor/Base64.java
- sentry/src/test/java/io/sentry/DiagnosticLoggerTest.kt
> Bump dev deps

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryEnvelopeHeader.java
- sentry/src/main/java/io/sentry/SentryEnvelopeItemHeader.java
- sentry/src/main/java/io/sentry/SentryItemType.java
- sentry/src/test/java/io/sentry/JsonUnknownSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryEnvelopeHeaderSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryEnvelopeItemHeaderSerializationTest.kt
- sentry/src/test/resources/gson/sentry_envelope_header.json
- sentry/src/test/resources/gson/sentry_envelope_item_header.json
- Implement serialization/deserialization for `SentryEnvelopeHeader`
- Implement serialization/deserialization for `SentryEnvelopeItemHeader`
- Added tests.
> Vendor Json: SentryEnvelope

- README.md
> readme: add sentry-apollo

- dangerfile.js
> Danger PR number as markdown link

- .craft.yml
Closes https://github.com/getsentry/sentry-java/issues/1723
> add sentry-apollo to craft config

- README.md
> add sentry-jdbc to readme

- .craft.yml
> Add `sentry-graphql` to Craft.

- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle and Dev deps

- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle to 7.3.2

- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle to 7.3.3

- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
> Replace androidx annotations with jetbrains

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-okhttp/build.gradle.kts
- sentry-android-timber/build.gradle.kts
> Bump AGP to 7.1.0

- Makefile
- gradle.properties
Only the publish tasks cannot run in parallel https://github.com/vanniktech/gradle-maven-publish-plugin
> Build runs task in parallel

- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Config.kt
> Bump build plugins

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle to 7.4 and AGP to 7.1.2

- CHANGELOG.md
> Fix changelog 5.6.2

- sentry-android-fragment/proguard-rules.pro
> Fix proguard rules for fragments

- .github/CODEOWNERS
@maciejwalkowiak so you can focus on the issues that you were purposely tagged :)
> Remove Maciej from code owners

- .github/ISSUE_TEMPLATE/bug_report_android.yml
- .github/ISSUE_TEMPLATE/bug_report_java.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_android.yml
- .github/ISSUE_TEMPLATE/feature_java.yml
- .github/ISSUE_TEMPLATE/maintainer-blank.yml
> Fix issue template errors

- sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt
> Fix format timber test

- README.md
> readme: blog on spring boot

- sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SentryInitializer.java
- sentry-samples/sentry-samples-servlet/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
Show how to properly close Sentry on servlet application un-deployment.
https://discord.com/channels/621778831602221064/621783601725308928/961881088668622848
> Close Sentry in servlet sample.

- README.md
> Add latest blogpost on the gradle plugin

- CHANGELOG.md
The goal is to use the new changelog format used by other projects like .NET, Capacitor, Unity, Cordova,...
It's a nit but it helps folks to find the url to the fixes/features easier.
> format  6.x.x changelog

- CHANGELOG.md
> chore: trim trailing whitespace in changelog.md

- CHANGELOG.md
Update the native dependency to the latest version
In the Unity SDK CI: https://github.com/getsentry/sentry-unity/actions/runs/2305224087
> Bump/native 0.4.17

- README.md
> Add Jakarta to readme

- buildSrc/src/main/java/Config.kt
- sentry-samples/sentry-samples-android/build.gradle.kts
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/GitHubService.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/compose/ComposeActivity.kt
- sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
- sentry-samples/sentry-samples-android/src/main/res/values/strings.xml
* Adds Compose sample activity
Part of #2096
> feat: Compose sample

- .github/workflows/integration-tests-benchmarks.yml
> avoid benchmark releases

- .craft.yml
- buildSrc/src/main/java/Publication.kt
> Fix compose publication

- CHANGELOG.md
Changelog of baggage PR went into an already released changelog instead of unreleased
> Fix changelog after merging baggage PR

- .github/workflows/update-deps.yml
> Update the updater workflow to v2

- .github/workflows/update-deps.yml
> ci: Update update-deps.yml

- .github/CODEOWNERS
> Add Markus to codeowners

- .github/ISSUE_TEMPLATE/bug_report_java.yml
> add spring-jakarta modules to bug report template

- .craft.yml
> Add new Spring Jakarta modules to `.craft.yml`

- .sauce/sentry-uitest-android-benchmark.yml
- .sauce/sentry-uitest-android-ui.yml
- CHANGELOG.md
> Fix changelog for already published version

- gradle.properties
> Fix artifacts version in gradle.properties

- CHANGELOG.md
- gradle.properties
This is a tagged release but not merged to the main branch - can anyone merge it **without squashing** (otherwise the release commit would say it doesn't exist in the repo?
> release: 6.7.0

- CHANGELOG.md
Replaced auto generated changelog with explanation why `6.9.1` was released.
> Fix 6.9.1 changelog

- .craft.yml
> Fix craft not handling multidigit version numbers

- .github/pull_request_template.md
> chore: Add PII to PR template

- .github/workflows/integration-tests-benchmarks.yml
- .github/workflows/integration-tests-ui.yml
> ci: use github token with saucectl-run-action to avoid GH API rate limits

- CONTRIBUTING.md
Fix minor typos in Contributing.
> chore: Fix typos in Contributing

- README.md
> Fix readme.md workflow shields badge for build status

- .github/workflows/enforce-license-compliance.yml
> Try to fix Fossa action

- gradle.properties
- sentry-android-core/src/main/res/values/public.xml
- sentry-android-fragment/src/main/res/values/public.xml
- sentry-android-navigation/src/main/res/values/public.xml
- sentry-android-ndk/src/main/res/values/public.xml
- sentry-android-okhttp/src/main/res/values/public.xml
- sentry-android-sqlite/src/main/res/values/public.xml
- sentry-android-timber/src/main/res/values/public.xml
- sentry-android/build.gradle.kts
- sentry-android/src/main/res/values/public.xml
- sentry-compose/src/androidMain/res/values/public.xml
- sentry-kotlin-extensions/src/main/res/values/public.xml
This PR bundles a few Android specific improvements based on some SDK feedback
* Enable non-transitive R class
* create empty `res/public.xml`, automatically marking all resources as private
* create empty `proguard-rules.pro` file for `sentry-android` meta package
> Improve Android specifics for ecosystem 

- .github/workflows/agp-matrix.yml
- .github/workflows/integration-tests-benchmarks.yml
- .github/workflows/integration-tests-ui.yml
- .sauce/sentry-uitest-android-benchmark-lite.yml
- .sauce/sentry-uitest-android-benchmark.yml
- .sauce/sentry-uitest-android-ui.yml
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
increased saucelabs timeout on all tests
increased concurrency on ui tests
updated build name
reenabled and fixed checkEnvelopeProfiledTransaction test
Closes https://github.com/getsentry/sentry-java/issues/2709 and improves ui tests
> Fixed checkEnvelopeProfiledTransaction ui test

- CHANGELOG.md
> Link to docs for GraphQL changes in Changelog

- CHANGELOG.md
I made a mistake in the changelog
> Fix mistake in the changelog

- .sauce/sentry-uitest-android-benchmark.yml
Changed Nokia 7.1 to Samsung Galaxy A10e
> Updated benchmark devices

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
removed frame checks from UI tests
ui tests are flaky, due to some slow devices reporting frozen frames after transaction finishes
> removed frame checks from UI tests

- .sauce/sentry-uitest-android-benchmark.yml
changed Samsung Galaxy A10e to Motorola Moto G Power
Samsung Galaxy A10e is failing most of the times (only in tests with absolute timestamps). Let's swap with a more reactive device, but in the same low end class
> Update Benchmark Device

- .craft.yml
> Uncomment sentry-quartz in .craft.yml

- codecov.yml
> Add more codecov ignores

- CHANGELOG.md
- gradle.properties
> Merge 6.33.1 release branch back into main

- codecov.yml
> Run codecov only for the entire project with target 78%

- .github/workflows/release-build.yml
> Rename release-build workflow to avoid confusion

- .github/workflows/build.yml
- .github/workflows/integration-tests-ui.yml
> Check if SAUCE_USERNAME is available for verifying test results

- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/PersonService.java
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/PersonService.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/java/io/sentry/samples/spring/boot/PersonService.java
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/PersonService.java
- sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-jakarta/src/main/java/io/sentry/samples/spring/jakarta/web/PersonService.java
Example data can be seen on the [ddm dashboard here](https://sentry-sdks.sentry.io/ddm/?statsPeriod=24h&widgets=%5B%7B%22mri%22%3A%22d%3Acustom%2Fperson.insert%40second%22%2C%22op%22%3A%22p90%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22bar%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%7D%5D).
> Add metrics API example to spring boot demo app

- LICENSE
> date range to license - 2019-2024

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
> POTEL 23 - Bump OTel versions

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/TraceContext.java
- sentry/src/main/java/io/sentry/protocol/User.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
deprecated segment in `User`, `TraceContext` and `Baggage` 
First step of https://github.com/getsentry/sentry-java/issues/3497
> deprecated User.segment

- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
- sentry/src/test/java/io/sentry/SentryReplayOptionsTest.kt
* I've picked a bit higher values for bps than iOS, because I've tested it and somehow 40kbps for medium looks pretty bad, especially on compose screens
Closes https://github.com/getsentry/team-replay/issues/444
> [SR] Add quality settings

- CHANGELOG.md
- sentry-android-replay/src/main/resources/META-INF/io/sentry/sentry-android-replay/verification.properties
Adds verification file.
I did some manual testing, the file ends up in the packaged `.aar` inside `classes.jar/META-INF/`.
> Verify sentry-android-replay for Google Play SDK Console

- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
- sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
- sentry/src/main/java/io/sentry/SentryOptions.java
> Fix Multi Init Merge and Tests

- CHANGELOG.md
> Add callout about `addIntegrationToSdkVersion` breaking change

- sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
> Make SentryTransaction non-internal

- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
- sentry-samples/sentry-samples-spring-boot-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/SentryDemoApplication.java
- test/system-test-run.sh
> fix e2e test run script

- CHANGELOG.md
Add a headline to the changelog since there's problems parsing it:
- https://github.com/getsentry/sentry-java/actions/runs/12879769636
https://github.com/getsentry/sentry-java/actions/runs/12879769636
> Add a "Summary" headline to the changelog

- scripts/update-sentry-native-ndk.sh
> ci: fix sentry-native updater script

- .github/ISSUE_TEMPLATE/bug_report_android.yml
- .github/ISSUE_TEMPLATE/bug_report_java.yml
- .github/ISSUE_TEMPLATE/feature_android.yml
- .github/ISSUE_TEMPLATE/feature_java.yml
> chore: Adds default issue types to issue templates

- .craft.yml
- README.md
Add Reactor and Apollo 4 modules to README.md and .craft.yml
Part of https://github.com/getsentry/sentry-java/issues/4199 and https://github.com/getsentry/sentry-java/issues/4201
> Add Reactor and Apollo 4 modules to README.md and .craft.yml

- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle/libs.versions.toml
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android-benchmark/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-navigation/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-replay/build.gradle.kts
- sentry-android-sqlite/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-compose/build.gradle.kts
- sentry-kotlin-extensions/build.gradle.kts
Continue adding version catalog
> Continue adding version catalog

- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle/libs.versions.toml
- sentry-samples/sentry-samples-netflix-dgs/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot/build.gradle.kts
- sentry-samples/sentry-samples-spring-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring/build.gradle.kts
- sentry-spring-boot-jakarta/build.gradle.kts
- sentry-spring-boot-starter-jakarta/build.gradle.kts
- sentry-spring-boot-starter/build.gradle.kts
- sentry-spring-boot/build.gradle.kts
- sentry-spring-jakarta/build.gradle.kts
- sentry-spring/build.gradle.kts
> Migrate Spring Plugins to Version Catalog

- sentry/src/main/java/io/sentry/util/StringUtils.java
Addresses concerns raised in https://github.com/getsentry/sentry-java/issues/4433
> Clarify usage of SHA-1 hash function

- .github/workflows/agp-matrix.yml
- .github/workflows/integration-tests-ui.yml
This is to help us keep track of our flaky tests.
> Add codecov test uploading

- CHANGELOG.md
> chore(changelog): Re-apply 7.22.6 changelog to main
