getsentry/sentry-java

raven-logback/README.md
raven-logback/src/main/java/net/kencochrane/raven/logback/SentryAppender.java
raven-logback/src/test/java/net/kencochrane/raven/logback/SentryAppenderEventBuildingTest.java
raven-logback/src/test/java/net/kencochrane/raven/logback/SentryAppenderEventLevelFilterTest.java
raven-logback/src/test/java/net/kencochrane/raven/logback/SentryAppenderFailuresTest.java
raven-logback/src/test/java/net/kencochrane/raven/logback/SentryAppenderIT.java

minimum event level filter for logback
warning: this breaks current behavior, since default filter level is WARN, events with lower levels will not be recorded anymore. See logback/README to change filter level.

minimum event level filter for logback

---

raven/src/main/java/net/kencochrane/raven/connection/AsyncConnection.java

don't remove shutdown hook if gracefulShutdown is disabled for AsyncConnection

---

README.md
raven/src/main/java/net/kencochrane/raven/DefaultRavenFactory.java

This improves:
- the check performed before instantiating the `HttpEventBuilderHelper` to ensure the correct Servlet version is available,
- documentation about the HTTP request context features.
Fixes GH-170.

Clarify Servlet 2.4 API dependency.

---

CHANGES
raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java

This is just the printf change from https://github.com/getsentry/raven-java/pull/174
By my reading/searching this is only necessary for JUL integration and WildFly, more modern logging facilities all use the `{}` style parametrized logging). Given that, I think the location of the format code seems reasonable.
Thoughts?

Add printfStyle option to JUL integration.

---

CHANGES
raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java
raven-logback/src/test/java/com/getsentry/raven/logback/SentryAppenderEventLevelFilterTest.java

This removes the default level filter that was deprecated in f5ad3dcdf8e77dcee117487e233b51ffe1bc0219, since Logback filters should be used instead of duplicating this functionality.
Fixes GH-206.
@getsentry/java

Remove Logback `minLevel` default parameter value.

---

CHANGES
README.md
docs/config.rst
raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java

This is low hanging fruit fix for #212.
On an unrelated note, `docs/` and `README` are rather out of sync... I caught it this time but should probably reconcile them in general? Or is that on purpose. (I'm also sure I was the cause of some of it)

Changed default raven.async.queuesize from unlimited to 50.

---

CHANGES
raven-appengine/src/main/java/com/getsentry/raven/appengine/connection/AppEngineAsyncConnection.java
raven/src/main/java/com/getsentry/raven/connection/AbstractConnection.java
raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java
raven/src/main/java/com/getsentry/raven/connection/Connection.java
raven/src/main/java/com/getsentry/raven/connection/EventSendFailureCallback.java
raven/src/test/java/com/getsentry/raven/connection/AbstractConnectionTest.java
raven/src/test/java/com/getsentry/raven/connection/EventSendFailureCallbackTest.java

This is a first stab at #180 to get feedback on the general idea. As usual, naming is hard.
Tests pass, failure is Javadoc crap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/201)

Add EventSendFailureCallback, called on send failure.

---

CHANGES
raven/src/main/java/com/getsentry/raven/RavenFactory.java

#183 
Used to provide this:
```
[WARNING] 
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Couldn't create a raven instance for 'Dsn{uri=http://localhost:9999/}'
at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:100)
at com.getsentry.example.Application.main(Application.java:16)
... 6 more
```
Now provides output like this:
```
[WARNING] …
```

Add more debugging information to ``RavenFactory.ravenInstance``.

---

CHANGES
raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java
raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java
raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java
raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
raven/src/main/java/com/getsentry/raven/marshaller/json/JsonMarshaller.java
raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java

Done more correctly this time.
It's not setup for log4j yet. I've never understood how (or if) log4j supports parameterized log messages. I guess *maybe* `message` can be of type `ParameterizedMessage`? But I think we'd be failing today if that were true.
The most common pattern seems to be,
```
if logging at this level is enabled:
log(manually_format(msg))
```
So maybe in log4j we just always send `message` as `formatted` (no params)? We can also leave out `formatted` on log4j.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/220)

Add formatted field to JSON if possible.

---

raven/src/test/java/com/getsentry/raven/connection/EventSendFailureCallbackTest.java

If this `EventSendFailureCallbackTest` was executed before `RavenContextTest`, the `RavenContextTest` would fail due to [this precondition not being met](https://github.com/getsentry/raven-java/blob/8207d186f0ab03c72d0ea04fec983251b68214c2/raven/src/test/java/com/getsentry/raven/RavenContextTest.java#L22
), as the active contexts set was already populated with the two contexts created when these `Raven` instances were instantiated. (I'm not sure why this doesn't seem to be an issue on CI, though.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-java/238)

Ensure contexts are removed from active contexts set after test completion.

---

CHANGES
raven/src/main/java/com/getsentry/raven/Raven.java
raven/src/main/java/com/getsentry/raven/RavenContext.java
raven/src/main/java/com/getsentry/raven/servlet/RavenServletRequestListener.java

This is a quick stab at ideas on how to handle user feedback, where basically the developer needs access to the last event sent during that request cycle.
If they sent the event manually themselves, they have access to the Event (and thus ID) already. This is for the unhandled exception (logger) case.
It's pretty overly verbose right now, but would be available at: `Raven.getStoredInstance().getContext().getLastEventId()`
There are a few issues here:
* I've decided to only store the Event ID, not the Event, because those could be large in aggregate, or hold references to other data (?).
* Because most users interact via logging frameworks, they'll need static access to Raven to get the Event ID. Thankfully we recently started storing it statically and we have `getStoredInstance()` (which …

Store last event sent in RavenContext.

---

README.md
pom.xml
raven-android/README.md
raven-android/pom.xml
raven-android/src/main/java/com/getsentry/raven/android/AndroidRavenFactory.java
raven-android/src/main/java/com/getsentry/raven/android/Raven.java
raven-android/src/main/java/com/getsentry/raven/android/RavenUncaughtExceptionHandler.java
raven-android/src/main/java/com/getsentry/raven/android/Util.java
raven-android/src/main/java/com/getsentry/raven/android/event/helper/AndroidEventBuilderHelper.java
raven-android/src/test/java/com/getsentry/raven/android/AndroidTest.java
raven-android/src/test/java/com/getsentry/raven/android/RavenIT.java
raven-android/src/test/java/com/getsentry/raven/android/RavenITActivity.java

I confused Github somehow. This is a clean diff moved from https://github.com/getsentry/raven-java/pull/231
---
Probably belongs in `raven-java`:
Mandatory for Android "hello world" (this PR):
Follow-on issues to create:

Add raven-android submodule.

---

CHANGES
raven-log4j/src/main/java/com/getsentry/raven/log4j/SentryAppender.java
raven-log4j/src/test/java/com/getsentry/raven/log4j/SentryAppenderIT.java
raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java
raven-log4j2/src/test/java/com/getsentry/raven/log4j2/SentryAppenderIT.java
raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java
raven-logback/src/test/java/com/getsentry/raven/logback/SentryAppenderIT.java
raven/README.md
raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java
raven/src/test/java/com/getsentry/raven/jul/SentryHandlerIT.java

@tkaemming this was on a whim, maybe there's some reason we didn't do this already? It seems like an obvious win to me. Should fix all deadlock issues, and for that matter I wonder if it'd allow us to drop the `RavenEnvironment` shit...

Add Filters to drop all Raven logs before they go to the Sentry server.

---

raven/src/main/java/com/getsentry/raven/Raven.java
raven/src/test/java/com/getsentry/raven/RavenContextTest.java

Noticed this on Travis, fails when they run in a different order. Also forced single threaded since it's checking shared mutable state.

Drop existing contexts before running context test.

---

raven/src/main/java/com/getsentry/raven/connection/AbstractConnection.java
raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java
raven/src/main/java/com/getsentry/raven/connection/BufferedConnection.java

This allows calling threads to determine thread interruption occurred and respond accordingly.
https://www.ibm.com/developerworks/library/j-jtp05236/
http://www.javaspecialists.eu/archive/Issue056.html

Restore thread interrupt status upon InterruptedException

---

Makefile

Covered all the commands I typically run.
The most complex is `prepare`, which is nice to finally have automated. I tested this a lot locally, you can do the same if you'd like -- it's best to run on a branch, and to undo it you'll have to hard reset back or at minimum delete the local tag it creates (so that it won't conflict or push to remote).
It adds 2 commits in addition to the normal `mvn` ones,
```
* a2e0ae27 - (HEAD -> makefile) Bump CHANGES to 7.8.3 Brett Hoerner (8 seconds ago)
* 0d27ea88 - [maven-release-plugin] prepare for next development iteration Brett Hoerner (10 seconds ago)
* a8330680 - (tag: v7.8.2) [maven-release-plugin] prepare release v7.8.2 Brett Hoerner (10 seconds ago)
* 33452227 - Bump docs to 7.8.2 Brett Hoerner (76 seconds ago)
```
The doc changes I used to run …

Add makefile.

---

raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java
raven/src/main/java/com/getsentry/raven/connection/ProxyAuthenticator.java

Fixes: https://github.com/getsentry/raven-java/issues/308
Adds the properties:
raven.http.proxy.user
raven.http.proxy.password

Support for basic authentication to proxy servers

---

raven/src/test/java/com/getsentry/raven/BaseIT.java

Minor fix.
I was getting lucky because so far I'm only testing 200 responses, but I noticed this while working on something else.

Only 'store' events in integration tests if the response is a 200.

---

raven/src/main/java/com/getsentry/raven/Raven.java

This builds on #319, so ignore until that lands (or just check the last commit).
This should help with #291 and #312, because lockdown exceptions will go to their own, easy to disable, logger. (It's *much* easier and more common to disable a logger than it is to drop certain exception classes -- I'm not even sure if all logging frameworks allow the latter.) I also changed the level from `error` to `warn` (to match `raven-js`). But `raven-js` doesn't tie into a bunch of existing application loggers ... I'm tempted for this to be `INFO` or `DEBUG`, because we already log when the lockdown is initiated.
It ends up looking like this (example from `jul`):
```java
// Called when in lockdown
logger.log(Level.SEVERE, "This is a test");
```
```
[RAVEN] [WARN ] class …
```

	Add lockdownLogger so that lockdown messages can be squelched.

---

docs/modules/android.rst
raven-android/src/main/java/com/getsentry/raven/android/AndroidRavenFactory.java
raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java

User's didn't realize what special stuff the Android client was doing (so far).
Also didn't have a way to disable buffering... it's not perfect but it seemed to make sense?

Add small explainer of Android features, add way to disable buffering.

---

raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java

Extending the concept of the lockdown logger to async connections so that we can disable these kinds of lockdown messages even if we use async connections.

Use lockdown logger for Lockdown messages

---

raven/src/main/java/com/getsentry/raven/Raven.java
raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java

A minor QOL commit, but I assume that the intention was to use the class name for lockdown loggers? Right now the lockdown logger is called `class com.getsentry.raven.Raven.lockdown`, which has an unnecessary `class` in the logger name. Should have caught this in my earlier commit.

Use Raven.class.getName for lockdown logger

---

raven/src/main/java/com/getsentry/raven/event/interfaces/HttpInterface.java
raven/src/main/java/com/getsentry/raven/marshaller/json/HttpInterfaceBinding.java
raven/src/main/java/com/getsentry/raven/marshaller/json/JsonMarshaller.java
raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java
raven/src/main/java/com/getsentry/raven/util/Util.java
raven/src/test/java/com/getsentry/raven/marshaller/json/HttpInterfaceBindingTest.java
raven/src/test/resources/com/getsentry/raven/marshaller/json/Http1.json

This is step 1 of #273, which just allows people to provide the `body` manually if they attach their own `HttpInterface` instance.
Not sure what size to trim the body to, or if we should allow overrides of that size?

Add optional 'body' field to HttpInterface.

---

pom.xml
raven/pom.xml
raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java
raven/src/main/java/com/getsentry/raven/util/Util.java

The `jsr305` was providing the "implementation" of the annotation.
"In practice this annotation is useful only for overriding an overarching NonNull annotation." http://findbugs.sourceforge.net/manual/annotations.html
We don't use `@NonNull`...
This spares us another Proguard exclusion (`-dontwarn javax.annotations.Nullable`) for 2 usages of `Nullable` throughout the codebase.

Drop needless javax.annotations.Nullable usages.

---

CHANGES
raven/src/main/java/com/getsentry/raven/event/Breadcrumb.java
raven/src/main/java/com/getsentry/raven/event/BreadcrumbBuilder.java
raven/src/main/java/com/getsentry/raven/marshaller/json/JsonMarshaller.java
raven/src/test/java/com/getsentry/raven/ContextTest.java
raven/src/test/java/com/getsentry/raven/buffer/DiskBufferTest.java
raven/src/test/java/com/getsentry/raven/event/BreadcrumbTest.java
raven/src/test/java/com/getsentry/raven/marshaller/json/JsonMarshallerTest.java
raven/src/test/resources/com/getsentry/raven/marshaller/json/jsonmarshallertest/testBreadcrumbs.json

One more cleanup thing that I think belongs in 8.0. While documenting I thought the strings were a pretty poor interface.
I highly doubt anyone was using this since Context was pretty busted up.

Change Breadcrumb type and level to enums, add more sensible defaults.

---

CHANGES
raven-log4j2/src/main/java/com/getsentry/raven/log4j2/SentryAppender.java

Apparently getFormat() can (and does) return an empty string in some
cases. This would cause a `null` format string with parameters and
display as an Event/JSON issue in the Sentry UI. This fixes the log4j2
integration to only include the parameterized message information if
getFormat() returns something useful.

Fix message interface errors in log4j2 integration.

---

CHANGES
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/SentryClientTest.java

This adds useful methods to the `SentryClient`
Roughly:
```
client = Sentry.init(dsn)
client.setRelease(1.0)
client.setEnvironment(production)
client.addTag(crappy_phone, true)
client.addEventCallback(mycallback)
// later, this should attach all the data and use the callback
Sentry.capture(exception)
```
@mitsuhiko you had asked about ways to set the other fields (env, release, tags, etc) too I think?

Add way to set release, environment, serverName, tags on SentryClient.

---

raven/src/main/java/com/getsentry/raven/context/Context.java
raven/src/main/java/com/getsentry/raven/event/User.java

For custom implementations of ContextManager it is required that Context object can be serialized.

Make Context and User classes serializable

---

sentry/src/main/java/io/sentry/dsn/Dsn.java

Handles #388, plus it makes using `noop` and `out` less annoying/dumb.

Drop HTTP auth information from default DSN to stop Android warnings.

---

sentry/src/main/java/io/sentry/SentryClient.java

For #402. It seems harmless to allow users to configure their own clients to do event building in a special order?

Change EventBuilderHelper collection from a set to a list.

---

raven-android/src/main/java/com/getsentry/raven/android/Util.java
raven-android/src/main/java/com/getsentry/raven/android/event/helper/AndroidEventBuilderHelper.java

On Android versions previous to M (Marshmallow), `uname` command is not
available, leading to an exception while computing `kernel_version` :
```
E/com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper: Exception while attempting to read kernel information
java.io.IOException: Error running exec(). Command: [uname, -a] Working Directory: null Environment: null
at java.lang.ProcessManager.exec(ProcessManager.java:211)
at java.lang.Runtime.exec(Runtime.java:173)
at java.lang.Runtime.exec(Runtime.java:246)
at java.lang.Runtime.exec(Runtime.java:189)
at com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper.getKernelVersion(AndroidEventBuilderHelper.java:267)
at com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper.<clinit>(AndroidEventBuilderHelper.java:4 …
```

android: kernel_version: fix for pre-M and align to AOSP Settings.

---

sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
sentry-log4j/src/main/java/io/sentry/log4j/SentryAppender.java
sentry-log4j/src/test/java/io/sentry/log4j/SentryAppenderEventBuildingTest.java
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/java/io/sentry/log4j2/SentryAppenderEventBuildingTest.java
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/java/io/sentry/logback/SentryAppenderEventBuildingTest.java
sentry/src/main/java/io/sentry/event/Event.java
sentry/src/main/java/io/sentry/event/EventBuilder.java
sentry/src/main/java/io/sentry/event/Sdk.java
sentry/src/main/java/io/sentry/jul/SentryHandler.java
sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java
sentry/src/test/java/io/sentry/jul/SentryHandlerEventBuildingTest.java
sentry/src/test/java/io/sentry/marshaller/json/JsonMarshallerTest.java
sentry/src/test/java/io/sentry/unmarshaller/event/UnmarshalledEvent.java
sentry/src/test/resources/io/sentry/marshaller/json/jsonmarshallertest/testSdk.json

`integrations` is currently stripped (I guess?) since it's not a part of the Sentry server.
Sentry PR: https://github.com/getsentry/raven-python/pull/1011

Add 'integrations' array field to 'sdk' in JSON.

---

docs/config.rst
docs/context.rst
docs/index.rst
docs/modules/android.rst
docs/modules/index.rst
docs/modules/log4j.rst
docs/modules/log4j2.rst
docs/modules/logback.rst
docs/modules/sentry.rst
docs/usage.rst

Strips all the duplicate (and now invalid) config out of loggers and explains all the ways you can configure stuff in one place.
I reckon this is easier to skim review by `cd docs && make html` and look in your browser.

Overhaul documentation for new configuration style.

---

CHANGES
docs/config.rst
sentry/src/main/java/io/sentry/SentryClientFactory.java
sentry/src/main/java/io/sentry/config/Lookup.java

This is for #416.
Basically you can now do something like `java -Dsentry.properties.file=/etc/myconfig.properties -cp $CP com.foo.App`.

Allow overriding the location of the properties file.

---

gradle/download-sentry-cli.sh
gradle/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
gradle/src/main/groovy/io/sentry/android/gradle/SentryPluginExtension.groovy

This adds a way to disable proguard uploads and bumps sentry-cli to 1.15.0 which fixes a bug with skipping uploads.

Add a flag to disable proguard uploads

---

CHANGES
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/event/helper/ShouldSendEventCallback.java
sentry/src/test/java/io/sentry/SentryClientTest.java

This adds a shouldSendEvent callback the be able to prevent sending of specific events.
e.g.:
```
sentryClient.addShouldSendEvent(new ShouldSendEventCallback() {
@Override
public boolean shouldSend(Event event) {
// We don't want to send events that are from ExceptionsManagerModule.
// Because we sent it already from raven.
if (event.getSentryInterfaces().containsKey(ExceptionInterface.EXCEPTION_INTERFACE)) {
ExceptionInterface exceptionInterface = ((ExceptionInterface)event.getSentryInterfaces().get(ExceptionInterface.EXCEPTION_INTERFACE));
if (exceptionInterface.getExceptions().getFirst().getExceptionClassName().contains("JavascriptException")) {
return false;
}
}
return true;
}
});
```

Add shouldSendEvent callback

---

CHANGES
docs/config.rst
docs/modules/log4j.rst
docs/modules/log4j2.rst
docs/modules/logback.rst
sentry-log4j/src/main/java/io/sentry/log4j/SentryAppender.java
sentry-log4j/src/test/java/io/sentry/log4j/SentryAppenderEventBuildingTest.java
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/java/io/sentry/log4j2/SentryAppenderEventBuildingTest.java
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/java/io/sentry/logback/SentryAppenderEventBuildingTest.java
sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/jul/SentryHandler.java
sentry/src/main/java/io/sentry/util/Util.java
sentry/src/test/java/io/sentry/DefaultSentryClientFactoryTest.java

Looks noisy, but this is just doing what it says on the tin (the old option will still work for now too).
#445

Deprecate ``extratags`` in favor of the more clear ``mdctags``.

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

#453 
The issue wasn't the classloader, it's that `os.arch` is `amd64` and not `x86_64` as the `sentry-cli` binary is named and so the file isn't found.
It gets weird because it seems like some JVMs may actually report `x86_64`, so I just handled this one (common) case for now.

Handle os.arch value of 'amd64' in the Android Gradle Plugin.

---

sentry-android/bnd.bnd
sentry-android/pom.xml
sentry-log4j/bnd.bnd
sentry-log4j/pom.xml
sentry-log4j2/bnd.bnd
sentry-log4j2/pom.xml
sentry-logback/bnd.bnd
sentry-logback/pom.xml
sentry-spring/bnd.bnd
sentry-spring/pom.xml
sentry/bnd.bnd
sentry/pom.xml

Here's a patch for #358.
This effectively marks all packages in `io.sentry` as publically available via OSGI.  If there are any packages that should not be exposed, the package should be removed from the `exportcontents` list in `bnd.bnd`.  Let me know if that's the case and I can make the change.
It also declares `javax.servlet` as an optional dependency.  I'm assuming that `javax.servlet` is not a required dependency if Sentry is not used in a servlet environment.

Add OSGI support.

---

CHANGES
sentry/src/main/java/io/sentry/environment/SentryEnvironment.java

Cleanup SentryEnvironment state to avoid memory leak warnings on Tomcat.

---

sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java

Fixes crash on Android API < 16

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

This fixes the issue that was introduced after #530 
Basically when there were no manifests in `build/intermediates/...` directory (i.e. after project was cleaned) and Gradle ran configuration phase Sentry tasks `persistSentryProguardUuidsFor*` were not created at all because of this return.
I also removed unnecessary error logging since this always gets called for clean builds polluting output.

Fix issue where Gradle tasks were not created

---

sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java

So we are using Sentry with our own infrastructure, so we are able to send reports with our own report length limitations. To do that, one has to extend the `JsonMarshaller`, since the Limitation are hardcoded in `SentyJsonGenerator#MAX*` (btw. the the [doc ](https://docs.sentry.io/learn/quotas/) says "each item is capped at 512 bytes", but currently it caps at 400 chars, which might, depending on the content depending on the content).
This was kind of hacky with the current implementation because one needed to copy a lot of code, which would make maintenance hell. I just extracted 2 methods to make it easier for an inheriting class to provide their own JsonMarshaller or JsonFactory.

Refactor creating Json Marshaller to be more friendly to extensions

---

docs/migration.rst

The class for the `logback.xml` config wasn't updated for the Now (sentry-java) example

Fix class for sentry-java logback.xml example

---

sentry/src/main/java/io/sentry/dsn/Dsn.java
sentry/src/test/java/io/sentry/dsn/DsnTest.java

This is so environment variable `SENTRY_DSN` can be set to an empty string without failing.

Default dsn when set to an empty string

---

sentry/src/main/java/io/sentry/connection/AsyncConnection.java
sentry/src/main/java/io/sentry/connection/BufferedConnection.java
sentry/src/main/java/io/sentry/util/Util.java

PR related to issue https://github.com/getsentry/sentry-java/issues/548
I noticed there are two places registering shutdown hooks (AsyncConnection and BufferedConnection), following the same pattern, so I added a method to Util to centralize the handling.

Unregister shutdown hooks on close

---

CHANGES
sentry-android/pom.xml
sentry-log4j/pom.xml
sentry-log4j2/pom.xml
sentry-logback/pom.xml
sentry-spring/pom.xml
sentry/pom.xml

#527
@kashike do you mind reviewing this?
I packaged and unzipped the `sentry-logback` JAR (as a sample), and:
```
grep Auto META-INF/MANIFEST.MF
Automatic-Module-Name: io.sentry.logback
```
I guess that's all we need for basic support?

Add Automatic-Module-Name to manifest so we have basic Java 9 support.

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

Use project.name instead of hardcoding 'app' in Android Gradle Plugin.

---

CHANGES
docs/config.rst
sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/connection/BufferedConnection.java
sentry/src/main/java/io/sentry/connection/ConnectionException.java
sentry/src/main/java/io/sentry/connection/HttpConnection.java
sentry/src/main/java/io/sentry/connection/TooManyRequestsException.java
sentry/src/test/java/io/sentry/connection/AbstractConnectionTest.java
sentry/src/test/java/io/sentry/connection/BufferedConnectionTest.java

This should bring `sentry-java` in line with other mobile SDKs and the relay.
@HazAT or @mitsuhiko not sure if you can glance at this? It's pretty simple and has tests. I mostly want to make sure it's in line with what we want mobile to do.

Changed buffer code to only retry in the case of HTTP 429 or connectivity issues.

---

sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/connection/HttpConnection.java
sentry/src/test/java/io/sentry/connection/HttpConnectionTest.java

Hi.
We are using sentry in our production environments and had a problem with one process hanging and never completing its workload. As this piece of software is heavily used and have been stable for weeks we looked at things that could happen seldom enough and have some outside stimuli.
Then I remembered a problem I had back in 2014 where java hanged when you got a problem with the connection and either the connection didn't connect or the data received never came. And we then found that in Java both Connection Timeout and Read Timeout is set to zero by default. This means that they will wait forever to either get a connection or read some data.
Looking into the sentry code you send code in the HttpConnection class and you never set the setDoInput to false so you expect there to be a …

Actively set connection timeout and read timeout for sentry connection.

---

sentry/src/main/java/io/sentry/jul/SentryHandler.java
sentry/src/test/java/io/sentry/jul/SentryHandlerEventBuildingTest.java

Handle JUL handler level correctly.
see https://stackoverflow.com/questions/46293943/sentry-io-tomcat-jul-all-logs-are-sent-to-sentry ,
https://forum.sentry.io/t/sentry-tomcat-integration/2370 and
https://forum.sentry.io/t/tomcat8-raven-jul-all-is-logged-why/438

support JUL handler level

---

.ci/agent-install.sh

Noticed another branch suddenly failing with `Package 'g++-multilib' has no installation candidate`
Trying this out.

Run apt-get update on Travis.

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

This seems to be the behavior of at least e.g [the google-services gradle plugin](https://developers.google.com/android/guides/google-services-plugin). Would be nice to not have to duplicate files when you want to use the same `sentry.properties` for different build variants I think.

fix: look for prop file directly under flavor dir

---

CHANGES
sentry/src/main/java/io/sentry/connection/BufferedConnection.java
sentry/src/test/java/io/sentry/connection/BufferedConnectionTest.java

This adjusts some of the changes from #562 to bring the Java SDK inline with what new Sentry SDKs are doing.

Drop events when the server returns an HTTP 429.

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

Without the fix android project build with sentry-android-gradle-plugin-enabled produces error:
No such property: autoProguardConfig for class: org.codehaus.groovy.runtime.GStringImpl

fixes compatibility with gradle 4.4+

---

sentry-spring-boot-starter/pom.xml

This dependency generate metadata needed to help Spring Boot with the
startup time.

Add spring boot configuration processor dependency

---

.gitignore
agent/agent.cpp

This should improve application startup. I still want to cache the class references but I'm having trouble getting that working so we can do it this in a few phases.
Oh, agent users need to actively call `Sentry.init();` when their app has completed startup. That was already the case (it's how we know which packages to look for), and documentation needs to be improved.
Related #617

Check for stored SentryClient before caching any frames.

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

Get the actual file out of the Provider<File> type to get the correct manifest path (closes #644).

Upload fix for AGP 3.3 / Gradle 4.10

---

CHANGES
sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

This fixes #671 
Adds ability to use separate sentry projects and orgs for different application build types. Use 
ext params of Android buildTypes: 
- `sentryOrg` 
- `sentryProject`
For example. Let's assume android project: 
`sentry.properties` in the project root: 
```
defaults.project=my-app
defaults.org=my-org
auth=<api_token>
```
and `build.gradle`:
```
...
android {
buildTypes { 
release { ... }
staging {
ext {
set("sentryProject", "my-app-staging")
}
....
}
experimental {
ext {
set("sentryProject", "my-app-experimental")
set("sentryOrg", "my-org-experimental")
}
}
}
```
Proguard mapping for release build type is uploaded to  `my-app` project of `my-org` (defaults)
staging to `my-app-staging` project of `my-org`
and experimental to `my-app-experimental` of `my-org-experimental`
The …

Fix #671 Use buildType.ext to override org and project 

---

sentry/src/main/java/io/sentry/marshaller/json/HttpInterfaceBinding.java
sentry/src/test/java/io/sentry/marshaller/json/HttpInterfaceBindingTest.java
sentry/src/test/resources/io/sentry/marshaller/json/Http2.json

Since if there is only body present without the parameters,
there is no need to nest body in another object.
HttpInterfaceBinding now checks if the body is present without any parameters
Fixes #683

Don't put body in nested object if parameterMap is empty

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

Sentry Android gradle plugin doesn't currently support [DexGuard](dexguard.com)
This is because DexGuard doesn't use the same `transformClasses` steps as proguard.
When running with proguard, `./gradlew -m assembleRelease` gives:
```
:app:preBuild SKIPPED
:app:extractProguardFiles SKIPPED
//....
:app:addSentryProguardSettingsForRelease SKIPPED
:app:processReleaseJavaRes SKIPPED
:app:transformResourcesWithMergeJavaResForRelease SKIPPED
:app:transformClassesAndResourcesWithProguardForRelease SKIPPED
:app:persistSentryProguardUuidsForRelease SKIPPED
:app:transformClassesWithDexForRelease SKIPPED
:app:transformClassesWithShrinkResForRelease SKIPPED
:app:mergeReleaseJniLibFolders SKIPPED
:app:transformNativeLibsWithMergeJniLibsForRelease SKIPPED …
```

feat: Support DexGuard

---

sentry/src/main/java/io/sentry/context/Context.java
sentry/src/main/java/io/sentry/event/helper/ContextBuilderHelper.java
sentry/src/main/java/io/sentry/event/interfaces/HttpInterface.java

Allow the creation of the HttpInterface object from just primitive objects.
Add HttpInterface to the context and ContextBuilderHelper, allowing integration with other web frameworks that are not Servlets. I have a proof of concept integration with Finatra but I'll keep that for a separate pr. 
First pass at addressing https://github.com/getsentry/sentry-java/issues/685

Decouple HttpInterface from Servlets

---

.gitignore
sentry-log4j2/src/test/java/io/sentry/log4j2/SentryAppenderEventBuildingTest.java

Use the builder pattern for tests instead of deprecated constructors

[LOG4J2] Remove usage of deprecated constructors

---

sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java

Hey, Sentry! We use logback appender and noticed recently a few events of thread starvation caused by the lock in `AppenderBase`. There is also an issue, https://github.com/getsentry/sentry-java/issues/151#issue-107916688, where synchronization was mentioned as a problem. 
I checked the code of `SentryAppender`, and it seems like the append method doesn't need to be synchronized. This PR changes `SentryAppender` to extend `UnsynchronizedAppenderBase`.
Cheers :)

Change logback appender to the unsynchronized version

---

sentry/src/main/java/io/sentry/event/interfaces/SentryException.java
sentry/src/test/java/io/sentry/event/interfaces/SentryExceptionTest.java

For an example class `my.sample.package.Controller$InvalidRequestException`, it's reported class name:
- Before: `Controller`
- After: `Controller$InvalidRequestException`

[EXCEPTION] Don't erase inner class names from stack trace interface when it's of type exception

---

sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java

Before this change, information about marker parents was not logged at all by sentry.
With this change, the Sentry appender will include marker & marker parent information in the same way as built-in log4j appenders (for example ConsoleAppender).

Include log4j marker parent(s) in log4j marker tag

---

sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/connection/HttpConnection.java

Hi,
we're currently dealing with some timeouts in our projects from the respective clients towards Sentry. While I could specify the general connect timeout via `sentry.properties`, I noticed that there is no convenient way of actually configuring the read timeout. This PR implements the desired functionality and fixes a documentation error in `HttpConnection` that I noticed while working on the PR.
Since this is my first contribution to this project, please let me know if there's anything I could have done differently or can do now to make everything more smooth.
Cheers,
Christoph

Allow read timeout to be configured

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

I have an android project where my release builds also shrink unused resources using `shinkResources true`. Sentry isn't able to find my dex task since it becomes `transformClassesAndDexWithShrinkResForRelease`.

find dex task when shrinking resources

---

sentry/src/main/java/io/sentry/event/interfaces/SentryStackTraceElement.java

Seems like the cached data might be missing the frame's name.
I've fixed it so it won't be crashing anymore but I'm unsure why the agent is not resolving the functions' name.
Resolves #728

fix: Cached frame might miss a name

---

sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy

When we create App Bundle, `sentry-debug-meta.properties` aren't included in aab.
So, I added task dependency to run persisting proguard uuid before packaging aab bundles.

Add task dependency to adapt Android App Bundle

---

sentry-android/src/main/java/io/sentry/android/AndroidSentryClientFactory.java
sentry-android/src/test/java/io/sentry/android/SentryITActivityUsingApplication.java
sentry-android/src/test/java/io/sentry/android/SentryITActivityUsingBaseContext.java
sentry-appengine/src/main/java/io/sentry/appengine/AppEngineSentryClientFactory.java
sentry-appengine/src/test/java/io/sentry/appengine/AppEngineSentryClientFactoryTest.java
sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryClientFactory.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/config/Lookup.java
sentry/src/main/java/io/sentry/dsn/Dsn.java
sentry/src/test/java/io/sentry/DefaultSentryClientFactoryTest.java
sentry/src/test/java/io/sentry/SentryClientFactoryTest.java
sentry/src/test/java/io/sentry/SentryIT.java
sentry/src/test/java/io/sentry/SentryTest.java
sentry/src/test/java/io/sentry/TestFactory.java
sentry/src/test/java/io/sentry/dsn/DsnTest.java

This should make us ready to have a fully customizable and composable configuration.
There are static helpers in `SentryOptions` (e.g. the `defaults()` method) that can help users get up and running quickly but the `SentryOptions` instance can be obtained using a fully configured `Lookup` instance and can also be supplied overrides for both `Dsn` and `SentryClientFactory`.
~~There should be just 1 behavioral change in this PR:~~
~~It is no longer possible to use `SentryOptions.resourceLoader` to inject the resource loader into the default Lookup instance. This needs to be done by manually constructing the `Lookup` instance, using it to construct `SentryOptions` instance and call `Sentry.init()` with that options instance.~~

Propagate the Lookup instance during the Sentry.init() and other initialization workflows.

---

sentry-appengine/pom.xml
sentry-appengine/src/main/java/io/sentry/appengine/connection/AppEngineAsyncConnection.java
sentry-appengine/src/test/java/io/sentry/appengine/AppEngineSentryClientFactoryTest.java
sentry-appengine/src/test/java/io/sentry/appengine/TestQueueFactoryProvider.java
sentry-appengine/src/test/java/io/sentry/appengine/connection/AppEngineAsyncConnectionTest.java
sentry-appengine/src/test/java/io/sentry/appengine/connection/ConnectionsInfo.java
sentry-appengine/src/test/java/io/sentry/appengine/event/helper/AppEngineEventBuilderHelperTest.java
sentry-appengine/src/test/resources/META-INF/services/com.google.appengine.spi.FactoryProvider

This rewrites the unit tests in the `sentry-appengine` module to use JUnit and Mockito without any static method or constructor mocking.
This required a small addition to the public API of the `AppEngineAsyncConnection` class and a couple of additions in the test code to use a thread-context classloader and a custom test-specific appengine queue factory to be able to test the stuff that we used to test with static method mocking.

Sentry appengine test rewrite

---

pom.xml
sentry-spring/pom.xml

Just a simple removal of traces of JMockit and TestNG from the POMs.

Remove traces of JMockit and TestNG from the POMs.

---

sentry/src/main/java/io/sentry/Sentry.java

As discussed in issue #783 this code modifications publish a method that allows to check if the singleton stored client is already initialized on Sentry

Add method to check if Sentry is already initializated #783

---

sentry-spring-boot-starter/pom.xml
sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SentryProperties.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SpringBootConfigurationProvider.java
sentry-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
sentry-spring-boot-starter/src/test/java/io/sentry/spring/autoconfigure/SentryAutoConfigurationTest.java
sentry/src/main/java/io/sentry/config/Lookup.java
sentry/src/main/java/io/sentry/config/provider/ResourceLoaderConfigurationProvider.java

Hello!
It's the very common and quite standard way to use bean auto-configuration in Spring Boot application, many developers expect to see these configs parameters inside their `application.yml` or `application.properties` files. I have implemented this feature for the current `sentry-spring-boot-starter` module.
I hope you guys will like this idea and merge this PR.
Best regards,
Alexey Zhokhov.

Added ability to init SentryClient use Spring Boot auto-configuration 

---

sentry/src/main/java/io/sentry/marshaller/json/StackTraceInterfaceBinding.java
sentry/src/test/java/io/sentry/marshaller/json/StackTraceInterfaceBindingTest.java
sentry/src/test/resources/io/sentry/marshaller/json/StackTraceBlacklist.json

Hi Sentry,
please review my change list to ignore more cglib generated dynamic classes like Guice.
Thanks and Best Regards,
James

Blacklist other frameworks using cglib dynamic classes, like Guice

---

sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/java/io/sentry/logback/SentryAppenderEventBuildingTest.java

adds support for logback encoders (the message field is encoded)
adds support for global tags and extras (not threadbound). tags and extras are
distinguished by the existing mdcTags property.
basic usage:
encoders
```
<appender name="jsonSentryAppender" class="io.sentry.logback.SentryAppender">
<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
<level>WARN</level>
</filter>
<encoder
class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
<providers>
<timestamp />
<version />
<logLevel />
...
```
basic usage:
global entries as tags or extras
```
LoggerContext context = (LoggerContext)LoggerFactory.getILoggerFactory();
context.putProperty("global", "value");
```

adds support for logback encoders (the message field is encoded).

---

sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java
sentry-appengine/src/main/java/io/sentry/appengine/connection/AppEngineAsyncConnection.java
sentry-appengine/src/test/java/io/sentry/appengine/connection/AppEngineAsyncConnectionTest.java
sentry-log4j/src/main/java/io/sentry/log4j/SentryAppender.java
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/SentryUncaughtExceptionHandler.java
sentry/src/main/java/io/sentry/buffer/DiskBuffer.java
sentry/src/main/java/io/sentry/connection/AbstractConnection.java
sentry/src/main/java/io/sentry/connection/AsyncConnection.java
sentry/src/main/java/io/sentry/connection/BufferedConnection.java
sentry/src/main/java/io/sentry/connection/HttpConnection.java
sentry/src/main/java/io/sentry/event/EventBuilder.java
sentry/src/main/java/io/sentry/jul/SentryHandler.java
sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java
sentry/src/main/java/io/sentry/servlet/SentryServletRequestListener.java
sentry/src/main/java/io/sentry/util/Util.java
sentry/src/test/java/io/sentry/connection/BufferedConnectionTest.java
sentry/src/test/java/io/sentry/jvmti/FrameCacheTest.java
sentry/src/test/java/io/sentry/marshaller/json/JsonComparisonUtil.java
sentry/src/test/java/io/sentry/unmarshaller/JsonDecoder.java

We spent a week to find, why one thread of our application can't finish after interruption ;-)
The reason is EventBuilder.getHostname, who cleared Thread.interrupted status, when we tried to log error (we use Sentry with log4j2 integration).
I have added recovery of interruption in EventBuilder, and changed catch clauses from Exception to more specific exceptions in all other places.
Otherwise, it is very difficult to understand, where Thread.interrupted status can be cleared.

Fixed loosing of interruption status in EventBuilder.

---

sentry/src/main/java/io/sentry/SentryClientFactory.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/util/Objects.java

added requireNonNull utils

---

sentry-spring-boot-starter/pom.xml
sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SentryAutoConfiguration.java
sentry-spring/pom.xml

fixed issue #806 NoSuchBeanDefinitionException. `@Autowired(required = false)` doesn't work in spring-bean's old version.

NoSuchBeanDefinitionException in spring-bean's old version

---

sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SpringBootConfigurationProvider.java
sentry-spring-boot-starter/src/test/java/io/sentry/spring/autoconfigure/SpringBootConfigurationProviderTest.java

The property sentry.stacktrace.app-packages isn't correctly converted to a string in lookup. Calling `toString()`on a Set adds `[]`around the elements, which wont match a package.

Boot app packages fix

---

sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/java/io/sentry/logback/SentryAppenderEventBuildingTest.java

(including the nesting class) rather than the simple name
The impetus here, is that as this is you can't rebuild a nested Exception class. One reason you might want to do it is to filter out certain subtypes via a ShouldSendEventCallback, which won't be possible without something like this.
There weren't too much in the contributing guidelines, so hopefully I'm not stepping on any toes here! Happy to talk about any concerns about this change or anything I'm missing. 
I think the overall impact will be:
SentryException#exceptionClassName will now be 
- Inner classes: `NestingClass$InnerClass`
- Anonymous classes: `NestingClass$1`
Added a test case to assert the inner class case, and happy to add a case (or extra logic) to cover anonymous classes if it would be preferred to keep that …

Have logback appender use the full classname 

---

sentry/src/main/java/io/sentry/event/helper/BasicRemoteAddressResolver.java
sentry/src/main/java/io/sentry/event/helper/ForwardedAddressResolver.java
sentry/src/main/java/io/sentry/event/helper/HttpEventBuilderHelper.java
sentry/src/main/java/io/sentry/event/helper/HttpServletCookieWrapper.java
sentry/src/main/java/io/sentry/event/helper/HttpServletRequestWrapper.java
sentry/src/main/java/io/sentry/event/helper/RemoteAddressResolver.java
sentry/src/main/java/io/sentry/event/interfaces/CookieInterface.java
sentry/src/main/java/io/sentry/event/interfaces/HttpInterface.java
sentry/src/main/java/io/sentry/event/interfaces/HttpRequestInterface.java
sentry/src/test/java/io/sentry/event/interfaces/HttpInterfaceTest.java
sentry/src/test/java/io/sentry/helper/RemoteAddressResolverTest.java

The HttpInterface currently ties in dependencies to javax.servlet, which makes it currently impossible to implement HttpEventBuilderHelpers for something like spring webflux (non servlet based http server). See https://github.com/getsentry/sentry-java/issues/640.
This PR extracts 2 interfaces `HttpRequestInterface` and `CookieInterface` which replace `javax.servlet.http.HttpServletRequest` and `javax.servlet.http.Cookie`.
Both interfaces get a servlet based implementation, wrapping the 2 types.
This would be a first step to provide better integration for non servlet based HTTP APIs.

Extract interfaces from servlet API to avoid servlet dependency in HttpInterface

---

README.md

Poiting badges to `sentry-java` and start some mentions of the Java SDK

Badges point to current repo

---

sentry-android-core/src/main/java/io/sentry/android/core/AndroidLogger.java
sentry/src/main/java/io/sentry/SentryLevel.java

ref: remove log level as RN do not use it anymore
we had level.LOG because of RN, but now we don't need it anymore, RN removed LOG and CRITICAL to be compatible with the unified API.

ref: remove log level as RN do not use it anymore

---

sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt

fix: read sample rate correctly from manifest meta data
sample rate from manifest was not being applied correctly
https://developer.android.com/guide/topics/manifest/meta-data-element
fixed unit tests and ran it

fix: read sample rate correctly from manifest meta data

---

sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

feat: enable attach stack traces and disable attach threads by default
threads are not useful if no stack traces, so threads are disabled by default, but if enabled, you get stack traces by default

feat: enable attach stack traces and disable attach threads by default

---

buildSrc/src/main/java/Config.kt

fix: rename bintray repos name to sync jcenter and maven central sync
we want to sync releases to jcenter and maven central, so we can't move repos on bintray

fix: rename bintray repos name to sync jcenter and maven central sync

---

sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry-samples/sentry-samples-logback/src/main/resources/logback.xml
sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
sentry-samples/sentry-samples-spring/src/main/java/io/sentry/samples/spring/SentryDemoApplication.java

Changed the DSN for a new test org.
The Android example uses one DSN while the other projects assume Java and go to another project.
Would you prefer both on the same Sentry project instead?

test: new dsn test org

---

buildSrc/src/main/java/Config.kt

fix: set oss email on releases
oss@sentry.io is a public email and its read by the oss team

fix: set oss email on releases

---

sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java

mainly to test the release drafter GH action

spotless: fix identation

---

sentry-spring/src/main/java/io/sentry/spring/SentryRequestHttpServletRequestProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryRequestHttpServletRequestProcessorTest.kt

Fixes not setting cookie on Sentry Event when `default-send-pii` is set to `false`.
`Cookies` header name instead of `Cookie` has been used before.

fix: Do not set cookies when send pii is set to false.

---

buildSrc/src/main/java/Config.kt

Upgrade Spring Boot to 2.3.4.

---

sentry-spring/src/main/java/io/sentry/spring/SentryRequestFilter.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryRequestFilterTest.kt

Pop scope at the end of the request in Spring integration.
Something we've missed before - scope should be popped at the end of the request.

fix: Pop scope at the end of the request in Spring integration.

---

sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml

This sets two necessary `<application …` flags for the android example.
ndk breaks without these.

fix: Set needed application flags in AndroidManifest

---

sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryLogbackAppenderAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryLogbackAppenderAutoConfigurationTest.kt

This change fixes following scenario:
When `sentry-logback` module was not on the classpath and Spring Boot application had dependency to `logback` (by default it has) application startup used to fail with `NoClassDefFoundException`.

fix: Enable Logback auto-configuration only when SentryAppender is on the classpath.

---

sentry-spring-boot-starter/build.gradle.kts

Change the dependency scope to `compileOnly` making it optional to use `sentry-logback` with Sentry Spring Boot Starter.
As [discussed](https://discordapp.com/channels/621778831602221064/621783601725308928/760775281148952626) with @marandaneto, following the [dependencies cost philosophy](https://develop.sentry.dev/sdk/philosophy/#dependencies-cost) using Logback with Spring Boot Starter should be an opt-in feature rather than a default behavior.
Since Logback is the default logging framework in Spring Boot, and I believe most users would want to send error logs to Sentry I believe pulling `sentry-logback` with Sentry Spring Boot starter is a right behavior - even though it may violate the dependency cost philosophy. Users would have to add single dependency instead of two, wouldn't need …

fix: Do not pull sentry-logback dependency in projects using Spring Boot Starter

---

sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
sentry/src/main/java/io/sentry/SentryThreadFactory.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt
sentry/src/test/java/io/sentry/SentryThreadFactoryTest.kt

fix: if attach stack traces are enabled, it should attach the current thread and its stack traces
we want the possibility to attach stack traces to improve grouping, but not all the threads, only the current one
unit tests

fix: if attach stack traces are enabled, it should attach current thread and its stack traces

---

.github/workflows/changelog-validation.yml

GitHub Actions workflow that runs on PRs and fails if `CHANGELOG.md` was not modified as part of that PR. Should be merged after #961.
#960
I copy-pasted it from sentry-dotnet where it's already working
Related to #960 #961

Add GitHub Action to validate presence of a changelog in a PR

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/InAppIncludesResolver.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/com/acme/MainBootClass.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt

Auto-configure `inAppIncludes` in Spring Boot integration by getting a package name from `@SpringBootApplication` or `@SpringBootConfiguration` annotated classes.
Less configuration and better experience for our users.

Auto-configure inAppIncludes in Spring Boot integration.

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryLogbackAppenderAutoConfigurationTest.kt
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

enha: make getThrowable public and improve set contexts
`getThrowable` is useful to use `instanceof` for filtering.
`setContexts` now have overloads for the most common data types as they need to be an object.
running it

enha: make getThrowable public and improve set contexts

---

CHANGELOG.md
sentry/build.gradle.kts
sentry/src/main/java/io/sentry/config/EnvironmentVariablePropertiesProvider.java
sentry/src/main/java/io/sentry/config/SimplePropertiesProvider.java
sentry/src/main/java/io/sentry/config/SystemPropertyPropertiesProvider.java
sentry/src/main/java/io/sentry/util/StringUtils.java
sentry/src/test/java/io/sentry/config/SimplePropertiesProviderTest.kt
sentry/src/test/java/io/sentry/config/SystemPropertyPropertiesProviderTest.kt
sentry/src/test/java/io/sentry/util/StringUtilsTest.kt

Accept quotes in external configuration properties, like `SENTRY_DSN="..."`.
Users who migrate from old Sentry SDK version have this issue that they used to pass quoted values and now they don't work.

Accept quotes in external configuration properties.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/transport/HttpTransport.java

fix: remove chunked streaming mode
some http servers have limitations and this was experienced on on-premise v9.x
https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#setChunkedStreamingMode-int-
reported by @ninniuz
running it

fix: remove chunked streaming mode

---

CHANGELOG.md

bump: sentry-native to 0.4.3
Fix #904

bump: sentry-native to 0.4.3

---

CHANGELOG.md
sentry-spring-boot-starter/build.gradle.kts
sentry-spring/build.gradle.kts

Fix setting up Sentry in Spring Webflux annotation by changing the scope of Spring WebMvc related dependencies.
Although we do not support decorating events with HTTP data in Spring Webflux, we should still auto-configure `Hub` and most importantly not cause application to fail to start.
Fixes gh-980
Sample project with both webflux and webmvc dependencies in all combinations.

fix: fix setting up Sentry in Spring Webflux annotation

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java
sentry-spring/src/main/java/io/sentry/spring/SentryWebConfiguration.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserProviderEventProcessorIntegrationTest.kt

Make sure HttpServletRequestSentryUserProvider runs by default before custom SentryUserProvider beans. This lets custom user providers overwrite properties set before by built in SentryUserProviders. 
In addition to that, users now can define `@Order` on custom user provider beans deciding at the same time if they run before or after built in SentryUserProviders.
Issue reported by @bruno-garcia 
Added integration tests.

Fix SentryUserProvider execution order

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryLogbackAppenderAutoConfiguration.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryProperties.java

Bind logging related SentryProperties to Slf4j Level instead of Logback to improve Log4j2 compatibility
Fixes gh-985
Integration tests cover it.

Bind logging related SentryProperties to Slf4j Level

---

build.gradle.kts
scripts/zeus.sh
sentry-android/build.gradle.kts

Build distribution zip files containing all files needed to be published to Maven.
Executing `./gradlew distZip` creates in each module that is meant to be published (not in samples or support modules) a file `build/distributions/<module-name>-<version>.zip`.
Solves #950, #951 
Find out how to publish files to Maven repository using either plain HTTP requests, Maven or Gradle (#952).

Build distribution zip files & upload to Zeus

---

CHANGELOG.md
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt

Prevent Logback and Log4j2 integrations from re-initializing Sentry when Sentry is already initialized
When `SENTRY_DSN` env property is provided, Logback integration overwrites configuration coming from Spring Boot integration.
When Logback and Spring Boot integrations are used together, Logback's SentryAppender should not re-initialize Sentry.
Same applies to Log4j2.
Fixes gh-988
Fixes gh-976
On the top of integration tests, tested with sample project on the side.

Prevent Logback and Log4j2 integrations from re-initializing Sentry when Sentry is already initialized

---

README.md

To avoid confusing when folks try out Sentry coming from other Crash reporting tools (that do not have such disclaimer on their README).

note on multiple crash reporting

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Breadcrumb.java

Make public the Breadcrumb constructor that accepts a Date. 
Apps should be able to record breadcrumbs at a particular time and then store them for a while, before delivering them at a later point. The timestamp of their creation, not their delivery to Sentry, should be preserved. 
Ran `make compile` with Java 1.8 on OSX.

Fix #1012 - Make public the Breadcrumb constructor that accepts a Date

---

CHANGELOG.md
sentry-samples/sentry-samples-android/src/main/java/io/sentry/sample/MainActivity.java
sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
sentry-samples/sentry-samples-android/src/main/res/values/strings.xml
sentry/src/main/java/io/sentry/GsonSerializer.java
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/ISentryClient.java
sentry/src/main/java/io/sentry/ISerializer.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/NoOpSentryClient.java
sentry/src/main/java/io/sentry/NoOpSerializer.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/SentryEnvelopeItemHeaderAdapter.java
sentry/src/main/java/io/sentry/SentryItemType.java
sentry/src/main/java/io/sentry/UserFeedback.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt
sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
sentry/src/test/java/io/sentry/SentryTest.kt

The SDK now provides a method captureUserFeedback to associate user
feedback to an event.
We want to bring this feature to our users.
Unit tests and simulator.
Add this to docs.

feat: Manually capturing User Feedback

---

.github/workflows/build.yml

Adds Github action to check if code is properly formatted.
We often get PRs merged that do not have code properly formatted. As the result, formatting fixes sneak in to other PRs adding noise.
This change will prevent PR build success in case code is not properly formatted.

Add Github action that checks formatting.

---

sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt

Do not exclude stack trace elements from samples. 
Bonus: fixed test.
It took me a while to figure out why errors reported in samples do not have the actual class that triggered the exception in the stack trace when running samples.
Unit test.

Do not exclude stack trace elements from samples.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Dsn.java
sentry/src/test/java/io/sentry/DsnTest.kt

Normalizes DSN URI.
#1030
Unit tests.

Normalize DSN URI.

---

.github/workflows/build.yml
.github/workflows/generate-javadocs.yml

Javadocs generation has to be triggered on the Github "release" event instead of running on specific branch/tag.
Javadocs page is not currently updated when the release is made.
On forked repository.

Fix Javadocs generation

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Breadcrumb.java
sentry/src/main/java/io/sentry/config/EnvironmentVariablePropertiesProvider.java

fix: use neutral Locale for String operations
All the other String operations already a neutral Locale

fix: use neutral Locale for String operations

---

CHANGELOG.md
sentry-android-ndk/CMakeLists.txt
sentry-android-ndk/src/main/jni/sentry.c
sentry-samples/sentry-samples-android/CMakeLists.txt

Updating to the latest sentry-native release, and making sure it is built as dynamic library.

feat: Update sentry-native to 0.4.4

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/main/java/io/sentry/protocol/App.java
sentry/src/main/java/io/sentry/protocol/Browser.java
sentry/src/main/java/io/sentry/protocol/DebugImage.java
sentry/src/main/java/io/sentry/protocol/DebugMeta.java
sentry/src/main/java/io/sentry/protocol/Device.java
sentry/src/main/java/io/sentry/protocol/Gpu.java
sentry/src/main/java/io/sentry/protocol/Mechanism.java
sentry/src/main/java/io/sentry/protocol/Message.java
sentry/src/main/java/io/sentry/protocol/OperatingSystem.java
sentry/src/main/java/io/sentry/protocol/Request.java
sentry/src/main/java/io/sentry/protocol/SdkInfo.java
sentry/src/main/java/io/sentry/protocol/SdkVersion.java
sentry/src/main/java/io/sentry/protocol/SentryException.java
sentry/src/main/java/io/sentry/protocol/SentryPackage.java
sentry/src/main/java/io/sentry/protocol/SentryRuntime.java
sentry/src/main/java/io/sentry/protocol/SentryStackFrame.java
sentry/src/main/java/io/sentry/protocol/SentryStackTrace.java
sentry/src/main/java/io/sentry/protocol/SentryThread.java
sentry/src/main/java/io/sentry/protocol/User.java

Added java docs to the protocol classes based on the https://github.com/getsentry/sentry-data-schemas project.
It improves accessibility of the SDK because all the important information is directly in the javadoc instead of in someones browser. 
`make compile` as I only added java docs.

Add java doc based on sentry-data-schemes project

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/config/PropertiesProvider.java
sentry/src/main/java/io/sentry/transport/AuthenticatorWrapper.java
sentry/src/main/java/io/sentry/transport/HttpTransport.java
sentry/src/main/java/io/sentry/transport/ProxyAuthenticator.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt
sentry/src/test/java/io/sentry/config/PropertiesProviderTest.kt
sentry/src/test/java/io/sentry/transport/HttpTransportTest.kt

Resolve HTTP Proxy parameters from the external configuration.
In order to make Proxy properties resolution in non-Spring Boot application the same as in Spring Boot application, the names of the environment variables had to be changed from ones in 1.7.x
- `SENTRY_PROXY_HOST`
- `SENTRY_PROXY_PORT`
- `SENTRY_PROXY_USER`
- `SENTRY_PROXY_PASS`
In addition to that - `SentryOptions#proxy` object had to be changed into Java bean so that we are able to bind properties via Spring Boot environment.
Fixes #1028
Unit tests.

Resolve HTTP Proxy parameters from the external configuration.

---

.appveyor.yml
.github/workflows/build.yml
CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-android-ndk/build.gradle.kts
sentry-samples/sentry-samples-android/build.gradle.kts

Sentry NDK integration is compiled against default NDK and CMake versions based on AGP's version
AGP version is heavily tested against a specific NDK version, and usually not the latest, we'd like to do the same so we don't run into unknown problems.

Sentry NDK integration is compiled against default NDK and CMake versions based on AGP's version

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt

Fix: userId should be set for hard crashes
we got reports that hard crashes were not making to user count.
ran the App, hard crash, Opened the App, an event on Sentry has userId.

Fix: userId should be set for hard crashes

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c

This cleans up the JNI layer, removes some unused things like the global transport options, and makes sure to clean up utf strings that have been created.
Avoids potential memory leaks and cleans up obsolete code.

fix: Clean up JNI code and properly free strings

---

CHANGELOG.md
sentry/src/main/java/io/sentry/GsonSerializer.java
sentry/src/main/java/io/sentry/ISerializer.java
sentry/src/main/java/io/sentry/NoOpSerializer.java
sentry/src/main/java/io/sentry/OutboxSender.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/cache/CacheStrategy.java
sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
sentry/src/test/java/io/sentry/DirectoryProcessorTest.kt
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/NoOpSerializerTest.kt
sentry/src/test/java/io/sentry/OutboxSenderTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt
sentry/src/test/java/io/sentry/cache/CacheStrategyTest.kt
sentry/src/test/java/io/sentry/cache/EnvelopeCacheTest.kt

Use single method to deserialize JSON.
https://github.com/getsentry/sentry-java/pull/971#discussion_r523730386
Unit tests.

Refactor Deserialization

---

sentry-android-core/src/main/java/io/sentry/android/core/util/RootChecker.java

Enha: SU logging was too verbose
We don't need to see the full stack trace if `su` is just not found, that's the expected behavior.

Enha: SU logging was too verbose

---

sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/Sentry.java

- remove `captureException` from Sentry class
- add overloaded version of `captureTransaction` on `Hub`.
- `captureException` is invoked from `SentryTransaction#finish` and has an `Internal` status.
- https://github.com/getsentry/sentry-java/pull/1058#pullrequestreview-535958518
Changes are breaking for current master but not for the latest released version.

Remove captureTransaction from Sentry class.

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryThreadFactory.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryThreadFactoryTest.kt

Fix: Set current thread only if theres no exceptions
We'd like to set the default (current) thread if `attachStacktrace` is enabled and there are no exceptions only, exceptions have its own stack traces already.
one of the use cases for this is events captured by hybrid SDKs like React-native or Flutter, the current thread will be always the File observer, and it doesn't make much sense.

Fix: Set current thread only if theres no exceptions

---

sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentrySpanClientHttpRequestInterceptor.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanAdvice.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentrySpanAdviceTest.kt
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/test/java/io/sentry/HubTest.kt

Adds a `getSpan` method on `Sentry` and `Hub` that returns current active transaction or span.
Currently it's very inconvenient to resolve active span or transaction - common thing when building framework integration. Other SDKs have similar methods.

Add `Hub#getSpan` method.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java
sentry-spring/src/main/java/io/sentry/spring/SentryRequestHttpServletRequestProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryRequestHttpServletRequestProcessorTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt

Spring: set transaction name on events also when performance feature is not active
Follow-up to https://github.com/getsentry/sentry-java/pull/513 compatible with SDK 3.x and the way we resolve transaction names in the performance feature.

Spring: set transaction name on events also when performance feature is not active

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/build.gradle.kts
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/config/AbstractPropertiesProvider.java
sentry/src/main/java/io/sentry/config/CompositePropertiesProvider.java
sentry/src/main/java/io/sentry/config/EnvironmentVariablePropertiesProvider.java
sentry/src/main/java/io/sentry/config/PropertiesProvider.java
sentry/src/main/java/io/sentry/config/SimplePropertiesProvider.java
sentry/src/main/java/io/sentry/config/SystemPropertyPropertiesProvider.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryOptionsTest.kt
sentry/src/test/java/io/sentry/config/EnvironmentVariablePropertiesProviderTest.kt
sentry/src/test/java/io/sentry/config/SimplePropertiesProviderTest.kt
sentry/src/test/java/io/sentry/config/SystemPropertyPropertiesProviderTest.kt

Add an option to set tags on SentryOptions through external configuration.
Fixes gh-981. Agreed with @bruno-garcia to add `tags` to `SentryOptions`.
Unit & integration tests.

Set tags on SentryOptions through external configuration

---

sentry/src/main/java/io/sentry/SentryOptions.java

The default for `cacheDirSize` is 30. The comment for the getter and setter stated 10 instead
of 30. This is fixed now.

docs: Fix comment for cacheDirSize

---

CHANGELOG.md
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry/src/main/java/io/sentry/ISpan.java
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/test/java/io/sentry/SentryTransactionTest.kt
sentry/src/test/java/io/sentry/SpanTest.kt

Add more convenient method to start child span.
https://github.com/getsentry/sentry-docs/pull/2715#discussion_r530520660

Enc: Add more convenient method to start child span.

---

CHANGELOG.md
build.gradle.kts
buildSrc/src/main/java/Config.kt
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry-android-ndk/api/sentry-android-ndk.api
sentry-android-timber/api/sentry-android-timber.api
sentry-android-timber/build.gradle.kts
sentry-log4j2/api/sentry-log4j2.api
sentry-logback/api/sentry-logback.api
sentry-samples/sentry-samples-android/api/sentry-samples-android.api
sentry-samples/sentry-samples-spring-boot/api/sentry-samples-spring-boot.api
sentry-samples/sentry-samples-spring/api/sentry-samples-spring.api
sentry-servlet/api/sentry-servlet.api
sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring/api/sentry-spring.api
sentry-test-support/api/sentry-test-support.api
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/protocol/Device.java
sentry/src/test/java/io/sentry/SpanContextTest.kt
sentry/src/test/java/io/sentry/cache/CacheStrategyTest.kt
sentry/src/test/java/io/sentry/protocol/DeviceTest.kt

Enha: Add API vlaidator and remove deprecated methods
We'd like to know when our API is broken, it's not back compatible.
`./gradlew apiCheck` is part of `./gradlew build` which is running on CI, so we don't need to do anything.
`./gradlew apiDump` is gonna be needed if API has changed and we are fine with it, changes will need to be committed.
It's breaking changes, but it's @Deprecated since 2.0 and we are going to a Major bump (4.0)

Enha: Add API validator and remove deprecated methods

---

sentry/src/test/java/io/sentry/ScopeTest.kt

`Scope.clear` is not covered by tests. This is fixed now by adding a test for it.
While adding the attachments to the scope I found out that `Scope.clear` is not covered by tests.
I added tests.

test: Add a test for Scope.clear

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/NoOpHubTest.kt
sentry/src/test/java/io/sentry/SentryTransactionTest.kt
sentry/src/test/java/io/sentry/SpanTest.kt

Refactor resolving SpanContext for Throwable
Previous implementation would fail once we switch to sending individual spans. Here we keep an association between throwable and SpanContext on the `Hub` which is independent from transaction or span being still in memory. 
Integration tests cover it.

Performance: Refactor resolving SpanContext for Throwable

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/config/PropertiesProvider.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Adds an option to set `inAppIncludes` and `inAppExcludes` using external configuration.
Mentioned in #992. For users who use Logback or Log4j2 integration it simplifies life significantly in case they want to set `inAppIncludes` or `inAppIncludes`.

Support loading in-app-includes and in-app-excludes from the external configuration

---

CHANGELOG.md
sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/InAppIncludesResolver.java

Make InAppIncludesResolver public.
Fixes #1080.
In case users want to overwrite `OptionsConfiguration` before this change they do not have an option to use `InAppIncludesResolver`.

Make InAppIncludesResolver public.

---

sentry/src/main/java/io/sentry/DateUtils.java

Improves `DateUtils` performance. See benchmark results here: https://github.com/maciej-scratches/simple-date-format-benchmark.
While this improves the current state, we can consider also opting-out from using SDF completely and rely on `Calendar` class instead similar to: https://askldjd.wordpress.com/2013/03/04/simpledateformat-is-slow/
I noticed getting current timestamp in UTC takes significant amount of CPU time while running benchmarks for the performance feature. 
This class has been also pointed in https://github.com/getsentry/sentry-java/issues/1081

Optimize DateUtils performance.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java

The method reference in SentryEnvelopeItem could cause problems on Android. This is fixed with
replacing it with a lambda.
https://github.com/getsentry/sentry-java/pull/1082/files#r535113142
CI.

fix: Remove method reference in SentryEnvelopeItem

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt

Fix: Append DebugImage list if the Event already has it
Events that contain an ImageList should append the Proguard debug image instead of skipping it.
This is a fix for Flutter mainly, as we do have an ImageList but we still want to deobfuscate Java/Kotlin stack traces
Bump SDK on Flutter

Fix: Append DebugImage list if the Event already has it

---

CHANGELOG.md
sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/InAppIncludesResolver.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt

Followup to #1084. Makes it possible to register multiple `OptionsConfiguration`.
Additionally, makes `InAppIncludesResolver#resolveInAppIncludes` so that it can be used in custom auto-configurations by users.
Issue #1080.
Currently when creating custom `OptionsConfiguration` bean, users have to either opt-out from the default behavior or replicate it even when they need just to set single custom property.
Unit tests.

Add the ability to register multiple OptionsConfiguration beans.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Fix: Sort breadcrumbs by Date if the event has breadcrumbs
If an event captured on a top SDK like Flutter and later sent by the Android SDK, the Scope breadcrumbs are merged along with the breadcrumbs from the event, but it's not respecting the timeline.
Ideally, this would be solved by the Scope sync, but if the Scope sync. can be opt-out, the same problem would happen.

Fix: Sort breadcrumbs by Date if the event has breadcrumbs

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

Fixes gh-1099
Fix inheriting sampling decision from parent.
When transaction was created from transaction context without providing custom sampling context, `tracingSampler` was not used.
Unit test.

Fix inheriting sampling decision from parent.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryExceptionFactory.java
sentry/src/main/java/io/sentry/SentryThreadFactory.java
sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt

Fix: Exception only sets a stack trace if there are frames
frames are a mandatory value for stack traces object, Unity generates an exception without stack trace and frames

Fix: Exception only sets a stack trace if there are frames

---

.github/pull_request_template.md

The prefix for the title of the PR already contains the type of change. Having to select the type
of change in the description of the PR duplicates this info and is not needed.
See description.
Didn't

meta: Remove type of change from PR template

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-android-core/build.gradle.kts
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/test/java/io/sentry/android/core/ContextUtilsTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt

Enhancement: Read tracesSampleRate from AndroidManifest.
Refactoring the ManifestReader class and tests, so it's easier to unit test things
Right now, to enable traces sample rate, we need to disable the auto init mode which is not ideal.

feat: Read tracesSampleRate from AndroidManifest

---

CHANGELOG.md
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/MainActivity.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/test/java/io/sentry/AttachmentTest.kt
sentry/src/test/java/io/sentry/ScopeTest.kt

Removed the setter for contentType and added two new constructors. Now Attachment is immutable.
Fixes GH-1120

ref: Make Attachment immutable

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Breadcrumb.java
sentry/src/main/java/io/sentry/DateUtils.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/main/java/io/sentry/Session.java
sentry/src/test/java/io/sentry/DateUtilsTest.kt
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryEventTest.kt

Ref: using Calendar instead of Dates directly
this would avoid the Date/String parsing and improve the performance #1081

Ref: using Calendar to generate Dates

---

sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/Stack.java
sentry/src/test/java/io/sentry/StackTest.kt

Refactor Stack to a separate classes that makes sure that root item is never removed thus `peek()` can never return `null`.
Reduce boilerplate and handling cases that can never happen in practice.
Unit tests.

Refactor Stack in Hub.

---

CHANGELOG.md
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/ISentryClient.java
sentry/src/main/java/io/sentry/ITransaction.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/NoOpSentryClient.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/NoOpTransactionTest.kt

Changes `startTransaction` method to never return `null`.
`null` could have been returned only if hub is closed or if stack contains zero items.
- when hub is closed, transaction will not be captured anyway since `captureTransaction` does the check for closed hub anyways
- it's not technically possible that `stack` contains zero items
Tests already cover it.
Create abstraction over stack to make sure that stack can never be empty.

Do not return null from startTransaction.

---

CHANGELOG.md
sentry-log4j2/api/sentry-log4j2.api
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpringIntegrationTest.kt
sentry-spring/src/main/java/io/sentry/spring/SentryHubRegistrar.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserProviderEventProcessorIntegrationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/AsyncHttpTransportFactory.java
sentry/src/main/java/io/sentry/NoOpTransportFactory.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/TransportFactory.java
sentry/src/test/java/io/sentry/AsyncHttpTransportFactoryTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Replace `ITransport` on `SentryOptions` with `TransportFactory`.
With this change, users will be able to easily set factory classes that create implementations of `ITransport`.

Add TransportFactory to SentryOptions.

---

CHANGELOG.md
sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryLogbackAppenderAutoConfiguration.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryLogbackInitializer.java

Spring Context can be refreshed while application is running (for example using Spring Cloud Bus). Without this change, `SentryAppender` would not get registered once refresh happens.
#1128 
AFAIK It is not possible to trigger context refresh in Spring integration testing framework.

Initialize Logback after context refreshes.

---

CHANGELOG.md
sentry-test-support/src/main/kotlin/io/sentry/test/reflection.kt
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/protocol/User.java
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/protocol/UserTest.kt

Fix: User.setOthers is marked @Nullable but crashes when passing in null
#1131

Fix: Do not crash when passing null values to @Nullable methods, eg User and Scope

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/GsonSerializer.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/exception/SentryEnvelopeException.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt

SentryEnvelopeItem.fromAttachment throws now a SentryEnvelopeException when it fails
to create an envelope item from an attachment. The GsonSerializer logs the exception
and drops the envelope item. So we avoid ingesting empty attachments.
This should have been a draft PR. It is not completely finished yet.
Fixes GH-1123
Unit tests and emulator

feat: Drop invalid attachments

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt
sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Drop attachments that are larger than the specified maxAttachmentSize in SentryOptions. I changed the units to bytes instead of having MiB. I need to change this in sentry-cocoa as well.
We want to give the users of the SDK the possibility to drop large attachments.
Unit tests.

feat: Add maxAttachmentSize to SentryOptions

---

CHANGELOG.md
sentry-apache-http-client-5/build.gradle.kts
sentry-spring-boot-starter/build.gradle.kts
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/AsyncHttpTransportFactory.java

Autoconfigures `ApacheHttpClientTransportFactory` in Spring Boot integration when `sentry-apache-http-client-5` is on the classpath.
`ApacheHttpClientTransportFactory` was done primarily for backend integrations using the Performance feature. We should make it as easy as possible for users to use high performance transport in with Spring Boot.

ApacheHttpClientTransportFactory auto-configuration.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/config/EnvironmentVariablePropertiesProvider.java
sentry/src/test/java/io/sentry/config/EnvironmentVariablePropertiesProviderTest.kt

Fix resolving dashed properties from external configuration using environment variables.
For example `in-app-includes` will be read now from `SENTRY_IN_APP_INCLUDES` variable.
Since `in-app-includes` and `in-app-excludes` use dashes, it has not been possible to set them using environment variables (that do not allow dashes in names).
Unit tests.

Fix resolving dashed properties from external configuration.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/IpAddressUtils.java
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/test/java/io/sentry/IpAddressUtilsTest.kt

In addition to `{{auto}}`, consider `{{ auto }}` as a default ip address.
Follow up to https://github.com/getsentry/sentry-java/pull/1144
Unit tests.

Fix: consider {{ auto }} as a default ip address.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Set release and environment on Transactions.
Fixes #1147
Both release and environment have to be set on transactions independently from how they are set on SentryEvents since transactions are not a subject of event processing.

Fix: Set release and environment on Transactions.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

Do not set transaction on the scope automatically.
Discussed with @bruno-garcia, It does not match single hub mode used in Android.
Unit tests.

Do not set transaction on the scope automatically.

---

CHANGELOG.md
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry-servlet/src/test/kotlin/io/sentry/servlet/SentryRequestHttpServletRequestProcessorTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentryRequestHttpServletRequestProcessorTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/ISpan.java
sentry/src/main/java/io/sentry/ITransaction.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/SpanContext.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Improve ITransaction and ISpan null-safety compatibility. Also makes `contexts` on `SentryBaseEvent` immutable which prevents cases when someone would set context to `null` on transactions.
Fixes #1159
Since in case of SentryEvents trace can be null, where for SentryTransactions trace cannot be null, I am considering refactoring `Contexts` class and create separate class for `TransactionContext`. The drawback would be the code duplication.

Improve ITransaction and ISpan null-safety compatibility

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt

Pass complete `HttpServletRequest` to CustomSamplingContext in Spring integration.
Fixes #1168

Pass request to CustomSamplingContext in Spring integration.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/config/PropertiesProvider.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Support SENTRY_TRACES_SAMPLE_RATE conf. via env variables.
Fixes #1169
Unit tests.

Support SENTRY_TRACES_SAMPLE_RATE conf. via env variables.

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c

Fix: Free Local Refs manually due to Android local ref. count limits
Fix https://github.com/getsentry/sentry-dart/issues/267
Running on Android 7 arm64
Release a patch to 3.2.0

Fix: Free Local Refs manually due to Android local ref. count limits

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/EnableSentryTest.kt

Simplify registering traces sample callback in Spring integration.
Similar to how `TracesSamplerCallback` is auto-configured in Spring Boot integration, Spring integration should detect if such bean exits and if so, set it on `SentryOptions`.

Simplify registering traces sample callback

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Scope.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/ScopeTest.kt

Discussion in: https://github.com/getsentry/develop/issues/246
Even if performance event is not used, users still must be able to set the transaction name on the scope in order to apply it on the events.

Bring back support for setting transaction name without ongoing transaction

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentrySpanRestTemplateCustomizer.java
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java

Move `SentrySpanClientHttpRequestInterceptor` to Spring module.
Simplify using performance feature for Spring (non-boot) users.
Fixes #1178.

Move `SentrySpanClientHttpRequestInterceptor` to Spring module.

---

CHANGELOG.md
sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/NdkIntegrationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/DiagnosticLoggerTest.kt
sentry/src/test/java/io/sentry/DirectoryProcessorTest.kt
sentry/src/test/java/io/sentry/EnvelopeSenderTest.kt
sentry/src/test/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegrationTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt
sentry/src/test/java/io/sentry/SentryOptionsTest.kt
sentry/src/test/java/io/sentry/SentryTest.kt
sentry/src/test/java/io/sentry/cache/EnvelopeCacheTest.kt

Allows setting "debug" through external properties.
Useful when debugging Spring (non-boot) integration.
Unit tests.

Set "debug" through external properties.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/AttachmentTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Add extra parameter addToTransaction to attachment, which specifies if the SDK adds
it to transactions or not. The default is false.
Fixes GH-1185
Unit tests.

feat: Add addToTransactions to Attachment

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ISpan.java
sentry/src/main/java/io/sentry/ITransaction.java
sentry/src/main/java/io/sentry/NoOpSpan.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/SentryTransactionTest.kt

Improve Kotlin property access in Performance API.
Let users use property access instead of setters where its suitable.

Improve Kotlin property access in Performance API.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/EnableSentryTest.kt

Auto register custom ITransportFactory in Spring integration.
For users who prefer to use Apache Http Client based transport, we have to provide convenient way of registering alternative transport factories.
Unit test.

Auto register custom ITransportFactory in Spring integration.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/CustomSamplingContext.java

Enable Kotlin map-like access on CustomSamplingContext.
Use `set` method instead of `put` to let users put properties using `context["key"]` notation.

Enable Kotlin map-like access on CustomSamplingContext.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/test/java/io/sentry/SentryTest.kt

Lower entry barrier and make samples look better with a simpler init method. 
Existed on Java 1.7, on .NET and other SDKs that support parametric overloading.

feat: init overload dsn

---

sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/NoOpHubTest.kt

Remove `IHub#getSpanContext` from public API.
After recent refactoring, this method can be private in `Hub` and can be removed from the public APIs.
The change is breaking only for the recent alphas. Since this is just a part of polishing the API I believe we can skip the changelog entry.

Remove `IHub#getSpanContext` from public API.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/DuplicateEventDetectionEventProcessor.java
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/test/java/io/sentry/SentryEventTest.kt

Add convenient method for accessing event's throwable.
Fixes #1201
Unit tests.

Add convenient method for accessing event's throwable.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/TracesSampler.java
sentry/src/test/java/io/sentry/TracesSamplerTest.kt

TracesSamplerCallback allows returning a nullable Double.
Fixes #1204
Unit tests.

TracesSamplerCallback allows returning a nullable Double.

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/SpanContext.java
sentry/src/test/java/io/sentry/SpanTest.kt

Fix returning Sentry trace header from Span.
SpanId for Sentry header should be taken from the Span itself and not from the parent transaction.
Fix #1216
Unit tests.

Fix returning Sentry trace header from Span.

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/src/main/java/io/sentry/EventProcessor.java

Improve EventProcessor nullability annotations.
Implementing custom event processor in Kotlin currently forces users to handle the case when `event` can be null, even though its never the case.
Update reference docs samples.

Event processor nullability

---

CHANGELOG.md
sentry/src/main/java/io/sentry/EnvelopeReader.java
sentry/src/main/java/io/sentry/GsonSerializer.java

Fix: Disable Gson HTML escaping
We want Gson processing as little as possible.
Escaping HTML is user's responsibility, not SDKs
setting random HTML values like `&lt; &gt;`

Fix: Disable Gson HTML escaping

---

CHANGELOG.md
sentry-samples/sentry-samples-spring-boot/api/sentry-samples-spring-boot.api
sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/CustomJob.java
sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/PersonService.java
sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/SentryDemoApplication.java
sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryAdviceConfiguration.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpan.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanAdvice.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanPointcutConfiguration.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingConfiguration.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransaction.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionPointcutConfiguration.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentrySpanAdviceTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTransactionAdviceTest.kt

Adds support for `@SentrySpan` and `@SentryTransaction` on classes and interfaces.
Fixes #1232.
Unit & Integration test, sample app.

Support @SentrySpan and @SentryTransaction on classes and interfaces.

---

CHANGELOG.md
sentry-apache-http-client-5/api/sentry-apache-http-client-5.api
sentry-apache-http-client-5/src/main/java/io/sentry/transport/apache/ApacheHttpClientTransport.java
sentry-apache-http-client-5/src/test/kotlin/io/sentry/transport/apache/ApacheHttpClientTransportTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/transport/AsyncHttpTransport.java
sentry/src/main/java/io/sentry/transport/ITransport.java
sentry/src/main/java/io/sentry/transport/NoOpTransport.java
sentry/src/main/java/io/sentry/transport/QueuedThreadPoolExecutor.java
sentry/src/main/java/io/sentry/transport/ReusableCountLatch.java
sentry/src/main/java/io/sentry/transport/StdoutTransport.java
sentry/src/test/java/io/sentry/transport/AsyncHttpTransportTest.kt
sentry/src/test/java/io/sentry/transport/QueuedThreadPoolExecutorTest.kt
sentry/src/test/java/io/sentry/transport/ReusableCountLatchTest.kt

Add ability to flush events synchronously.
Under the hood, used (copied) https://github.com/MatejTymes/JavaFixes/blob/master/src/main/java/javafixes/concurrency/ReusableCountLatch.java
Fixes #916.
Gives user an option to use Sentry in serverless scenarios where events must be flushed before lambda execution is finished.
Unit tests.
The breaking change is: `AsyncHttpTransport` takes now `QueuedThreadExecutor` instead of any `ExecutorService` in a constructor.

Add ability to flush events synchronously

---

CHANGELOG.md
sentry-samples/sentry-samples-spring/src/main/java/io/sentry/samples/spring/WebConfig.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentrySpanRestTemplateCustomizer.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java

Instead of passing templated URL to span description, pass real URL against which request is executed. It adds more details about request to executed Span and simplifies RestTemplate instrumentation configuration in non-boot usage.
Fixes #1240.
Update reference docs.

Simplify RestTemplate instrumentation.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/GsonSerializer.java
sentry/src/main/java/io/sentry/adapters/CollectionAdapter.java
sentry/src/main/java/io/sentry/adapters/MapAdapter.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt

Do not serialize empty collections and maps.
Fixes #1242.

Do not serialize empty collections and maps.

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java
sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
sentry-android-core/src/main/java/io/sentry/android/core/ApplicationNotResponding.java
sentry-android-core/src/main/java/io/sentry/android/core/IHandler.java
sentry-android-core/src/main/java/io/sentry/android/core/MainLooperHandler.java
sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryExceptionFactory.java
sentry/src/main/java/io/sentry/SentryThreadFactory.java
sentry/src/main/java/io/sentry/exception/ExceptionMechanismException.java
sentry/src/main/java/io/sentry/protocol/SentryStackTrace.java
sentry/src/test/java/io/sentry/DuplicateEventDetectionEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryEventTest.kt
sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt
sentry/src/test/java/io/sentry/SentryThreadFactoryTest.kt

Fix: Mark stacktrace as snapshot if captured at arbitrary moment
ANR stack traces and the thread list attach a stack trace captured at an arbitrary moment and this could affect grouping, this flag will be used for better grouping, maybe using hierarchical grouping or something else on the server-side.

Fix: Mark stacktrace as snapshot if captured at arbitrary moment

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryProperties.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
sentry-spring-boot-starter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
sentry-spring/src/main/java/io/sentry/spring/EnableSentry.java
sentry-spring/src/test/kotlin/io/sentry/spring/EnableSentryTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt

Change the default SentryExceptionResolver behavior to not send errors handled with Spring exception handlers.
I believe current default behavior of `SentryExceptionResolver` is surprising for users - even if they define an exception handler for an exception - to handle it gracefully - it's still being sent to Sentry as an error. This PR changes the default behavior (that can still be overwritten through setting `exception-resolver-order`) to send only unhandled exceptions.
Integration tests
While it does not break the compilation process, it is a breaking change from the behavior point of view.

SentryExceptionResolver should not send handled errors by default

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/src/main/java/io/sentry/Integration.java
sentry/src/main/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegration.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegrationTest.kt

Integration interface better compatibility with Kotlin null-safety
Fix #1230

Integration interface better compatibility with Kotlin null-safety

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/main/java/io/sentry/Scope.java

The API is stable and not experimental anymore. We can remove the annotation.
Fixes GH-1255
CI.

fix: Remove experimental annotation for Attachment

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java

Fix: Make the ANR Atomic flags immutable
https://stackoverflow.com/questions/66095728/sentry-android-anr-could-there-be-a-false-alarm/66097964?noredirect=1#comment116884716_66097964
could not reproduce the issue not being final, but the behavior is still the same.

Fix: Make the ANR Atomic flags immutable

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/EnableSentryTest.kt

Auto-configures user provided callbacks and event processors on `SentryOptions` as well as `SentryConfiguration` bean.
Currently there is no straightforward way to configure callbacks and event processors on SentryOptions in Spring integration. With this change, there is a convenient way to set most common callbacks just as Spring beans and if something advanced needs to be configured users can define `SentryConfiguration` beans that post processes `SentryOptions` before `SentryInit` is called.
Integration tests.
Update reference docs.

Simplify Sentry configuration in Spring integration.

---

sentry-apache-http-client-5/src/test/kotlin/io/sentry/transport/apache/ApacheHttpClientTransportTest.kt

Fix flaky test in `ApacheHttpClientTransportTest` by increasing the flush timeout to 100ms.
Test was randomly failing when run with Github Actions.
Fixes: #1261 
Run 1000 iterations for the same test to make sure that test won't fail.

Fix flaky test: `ApacheHttpClientTransportTest`

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/DuplicateEventDetectionEventProcessor.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/DuplicateEventDetectionEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Optimize potential `DuplicateEventDetectionEventProcessor` performance issue by changing how objects are stored from `WeakHashMap` to `ConcurrentLinkedQueue`.
Using WeakHashMap to store objects opens up a possibility that the map will grow to thousands of entries and causes performance loss when searching for stored exception. This may happen either if outside of the SDK code references to exceptions are kept or if GC does not run for long time.
Changing the implementation to `ConcurrentLinkedQueue` gives the event processor control over how many exceptions are stored in the memory.
Unit tests.

Optimize DuplicateEventDetectionEventProcessor performance.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/test/java/io/sentry/SentryTransactionTest.kt

Fix SentryTransaction#getStatus NPE
Fixes #1268.

Fix SentryTransaction#getStatus NPE

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

SentryTransaction#finish should not clear another transaction from the scope
Fixes #1269

Fix: SentryTransaction#finish should not clear another transaction from the scope

---

sentry-apache-http-client-5/src/test/kotlin/io/sentry/transport/apache/ApacheHttpClientTransportTest.kt
sentry/src/test/java/io/sentry/transport/StdoutTransportTest.kt

Fix flaky tests.
`ApacheHttpClientTransport` tests tend to fail time to time on Github actions, especially built on MacOS. This fix run 1000 times without a failure, so there's a great chance it will solve an issue.

Fix flaky test.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/protocol/Request.java
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt
sentry/src/test/java/io/sentry/protocol/RequestTest.kt

Add Request to the Scope.
We need to have a simple way to pass scope to another thread - including the request. Sample scenario:
HTTP request coming to a server application, this application executes a task on the thread from the pool, Sentry event is sent from this thread. There should be an easy way to pass the HTTP request context to this event.
Unit tests.
Refactor Spring and Servlet integrations to set the request on the scope instead of attaching event processor.

Add Request to the Scope.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/transport/QueuedThreadPoolExecutor.java

Interrupt the thread in QueuedThreadPoolExecutor.
When wait till idle is interrupted, it should interrupt also the parent thread.

Fix: Interrupt the thread in QueuedThreadPoolExecutor.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/SentryOptions.java

Prevent NoOpHub from creating heavy SentryOptions objects.
Fixes #1263

Prevent NoOpHub from creating heavy SentryOptions objects.

---

CHANGELOG.md
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry-samples/sentry-samples-logback/src/main/resources/logback.xml

Simplify configuring Logback integration when environment variable with the DSN is not set.
When an environment property that is referenced in logback.xml is not set, Logback sets its value to PROPERTY_NAME_IS_UNDEFINED (not a `null` like it could have been expected). This complicates setting up SentryLogback appender configuration where the integration should be disabled in environments that do not have this property.
Before this change, users had to do:
```xml
<options>
<dsn>${PROPERTY:- }</dsn>
</options>
```
With this change:
```xml
<options>
<dsn>${PROPERTY}</dsn>
</options>
```

Simplify configuring Logback integration when environment variable with the DSN is not set.

---

.craft.yml

Follow-up to https://github.com/getsentry/sentry-release-registry/pull/44, we need to update the canonical names in the Craft config so that `craft` is able to update the registry next time.

craft: Update package canonicals

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt

Add `io.sentry.mobile.` as an exception when detecting own stack frames
With this change, we cant use `io.sentry` as prefix in the packages for the sentry mobile app so that frames are marked correctly with `inApp=true`.
See https://github.com/getsentry/sentry-mobile/issues/117 for more information.
Added a unit test and ran the tests.
- Had issues with OpenJDK 15  though, as the tests would not run.  Had to apply fix from https://github.com/gradle/gradle/issues/15038#issuecomment-754172184 locally for them to run.
```
repositories {
maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
}
jacoco {
toolVersion = "0.8.7-SNAPSHOT"
}
```
- Some unrelated tests seem to be failing on main.
```
io.sentry.config.EnvironmentVariablePropertiesProviderTest > when system …
```

Enha: Add "io.sentry.mobile." as an exception when detecting own stack frames

---

.craft.yml

Reverts getsentry/sentry-java#1285 because of https://github.com/getsentry/sentry-release-registry/pull/45

Revert "craft: Update package canonicals"

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Fix setting in-app-includes from external properties.
https://github.com/getsentry/sentry-java/pull/1282/files#r580247477
Unit tests.

Fix setting in-app-includes from external properties.

---

.craft.yml

Craft publish requires no artifact provider if we want only to publish to release-registry, command:
eg 4.2.0
> craft publish 4.2.0 --rev 4.2.0 --target registry

Fix: Craft artifact provider

---

sentry-samples/sentry-samples-console/build.gradle.kts
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry-samples/sentry-samples-jul/build.gradle.kts
sentry-samples/sentry-samples-jul/src/main/java/io/sentry/samples/jul/Main.java
sentry-samples/sentry-samples-jul/src/main/resources/sentry.properties
sentry-samples/sentry-samples-log4j2/build.gradle.kts
sentry-samples/sentry-samples-log4j2/src/main/resources/log4j2.xml
sentry-samples/sentry-samples-log4j2/src/main/resources/sentry.properties
sentry-samples/sentry-samples-logback/build.gradle.kts
sentry-samples/sentry-samples-logback/src/main/resources/sentry.properties
sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SentryInitializer.java
sentry-samples/sentry-samples-spring-boot/README.md
sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
sentry-samples/sentry-samples-spring/README.md
sentry-samples/sentry-samples-spring/src/main/resources/sentry.properties

Fix: samples DSN and missing inAppIncludes
Found 2 bugs #1293 and #1291
#1281

Fix: samples DSN and missing inAppIncludes

---

CHANGELOG.md
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt

Initialize Sentry in Logback appender when DSN is not set in XML config
Fixes #1295
With the recent change, when DSN is set using external properties, Sentry would fail to initialize.
Unit tests.

Fix: Initialize Sentry in Logback appender when DSN is not set in XML config

---

sentry-android-core/proguard-rules.pro
sentry-android-ndk/proguard-rules.pro
sentry-android-timber/proguard-rules.pro

Fix: Add missing proguard rules
rules are per module, so some of them need to be placed in all of our android modules.
missing 2 important rules that keep our stack traces unambiguous

Fix: Add missing proguard rules

---

sentry/src/main/java/io/sentry/SentryTransaction.java
sentry/src/main/java/io/sentry/Span.java

Fix: Make AtomicBooleans transitive as they are not serializable
Reflection would pass thru those fields but its not needed

Fix: Make AtomicBooleans transitive as they are not serializable

---

sentry/src/main/java/io/sentry/transport/RateLimiter.java

Currently, The debug logs for dropped item size is printed each time a dropped item is added to the list from SentryEnvelop in RateLimiter class.
Updated this to log the dropped item size only after we have the complete list of dropped items to avoid unnecessary logs.
https://github.com/getsentry/sentry-java/issues/1316

Log dropped items size in RateLimiter only after all items are added to list

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
sentry-android-core/src/test/java/io/sentry/android/core/NdkIntegrationTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryNdk.kt
sentry-android-ndk/api/sentry-android-ndk.api
sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
sentry-android-ndk/src/main/jni/sentry.c
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ShutdownHookIntegration.java
sentry/src/test/java/io/sentry/ShutdownHookIntegrationTest.kt

Feat: Sentry closes Android NDK and ShutdownHook integrations
#1225
running it

Feat: Sentry closes Android NDK and ShutdownHook integrations

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Breadcrumb.java
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/SpanContext.java
sentry/src/main/java/io/sentry/config/EnvironmentVariablePropertiesProvider.java
sentry/src/main/java/io/sentry/protocol/App.java
sentry/src/main/java/io/sentry/protocol/Browser.java
sentry/src/main/java/io/sentry/protocol/Device.java
sentry/src/main/java/io/sentry/protocol/Gpu.java
sentry/src/main/java/io/sentry/protocol/OperatingSystem.java
sentry/src/main/java/io/sentry/protocol/SentryRuntime.java
sentry/src/main/java/io/sentry/protocol/User.java
sentry/src/main/java/io/sentry/transport/RateLimiter.java
sentry/src/main/java/io/sentry/util/CollectionUtils.java

Resolves: #1366 
This PR adds `org.jetbrains.annotations.NotNull` annotation for a places, where SDK could receive a `Map` from a client, which has a `nullable` type for `value` generic parameter.
I've also added this annotation to internal API methods and some fields to which `ConcurrentHashMap` is assigned.
`ConcurrentHashMap` can't have a `null` for any of it's entries value, [otherwise `NullPointerException` is thrown](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ConcurrentHashMap.java#l1011). By adding this `NotNull` annotation we:
- raise awareness of this issue for Java clients
- have a build-time check for Kotlin clients:
Unfortunately, I don't know how to test it, I'm open to any suggestions.

Accept only non null value maps

---

CHANGELOG.md
sentry-jul/api/sentry-jul.api
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java

Removing final keyword on sentry-jul SentryHandler class to allow inheritance for the creation of custom log handlers based on SentryHandler. 
Allows extension of SentryHandler to create custom LogHandlers that can be deployed to EE application servers like Glassfish/Payara.
Fixes #1360 
Ran local tests
- [x ] I reviewed the submitted code
- [ x] No breaking changes

Allow inheritance of SentryHandler class in sentry-jul package

---

CHANGELOG.md
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt

This is a fix for this issue: https://github.com/getsentry/sentry-java/issues/1361.

Fixed NPE when MDC contains null values.

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTransactionAdviceTest.kt
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/test/java/io/sentry/HubTest.kt

Do not bind transactions to scope by default.
Fixes #1355

Do not bind transactions to scope by default.

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/NoOpHub.java

Make NoOpHub Public
https://github.com/getsentry/sentry-java/pull/1372

Make NoOpHub Public

---

CHANGELOG.md
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt

Avoid NPE when MDC contains null values
Follow up https://github.com/getsentry/sentry-java/pull/1364

Fix: Avoid NPE when MDC contains null values

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java

Fix: fix `Hub` thread safety.
`WeakHashMap` is not thread safe and must be synchronized.

Fix: fix `Hub` thread safety.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTransactionAdvice.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTransactionAdviceTest.kt

Fix: `SentryTransactionAdvice` should operate on the new scope.
`@SentryTransaction` is meant to be used for integrations that we do not support out of the box like messaging, scheduled jobs. These integrations work on thread pools, meaning if users modify the scope, without having push & pop scope changes would last also for further invocations happening on the same thread.
Unit tests.

Fix: `SentryTransactionAdvice` should operate on the new scope.

---

CHANGELOG.md
gradle.properties
sentry-apache-http-client-5/src/main/java/io/sentry/transport/apache/ApacheHttpClientTransportFactory.java
sentry-apache-http-client-5/src/test/kotlin/io/sentry/transport/apache/ApacheHttpClientTransportFactoryTest.kt
sentry-test-support/src/main/kotlin/io/sentry/test/reflection.kt

Fix: use connection and read timeouts in ApacheHttpClient based transport
When `ApacheHttpClientTransport` was used, timeouts were not respected.
Console sample and slowing down connections with ToxiProxy connected to Sentry relay running locally.

Fix: use connection and read timeouts in ApacheHttpClient based transport

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java

Fix: handle network errors in SentrySpanClientHttpRequestInterceptor.
Related to #1351
Unit tests.

Fix: handle network errors in SentrySpanClientHttpRequestInterceptor.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Fix: set scope on transaction
Until now, only request has been set from the scope on transaction.
Unit tests
I believe applying scope deserves a refactoring. We can add a method on `SentryBaseEvent#applyScope(scope)` which will get overwritten in `SentryTransaction` and `SentryEvent`.

Fix: set scope on transaction

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c

Fix: Pass maxBreadcrumbs config. to sentry-native
https://github.com/getsentry/sentry-native/releases/tag/0.4.7 and https://github.com/getsentry/sentry-native/issues/473
running

Fix: Pass maxBreadcrumbs config. to sentry-native

---

CHANGELOG.md
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserProviderEventProcessorIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserProviderEventProcessorTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Apply user from the scope to transaction.
#1335 Note: this does not solve the issue of setting user on transaction in Spring/Spring Boot integrations.
Unit tests.
Adding nullability annotations to `user` makes it a breaking change for Kotlin users.
Fix setting user on transaction for Spring & Spring Boot.

Fix: Apply user from the scope to transaction.

---

sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/util/Pair.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/NoOpHubTest.kt
sentry/src/test/java/io/sentry/SentryTracerTest.kt
sentry/src/test/java/io/sentry/SpanTest.kt

Fix setting transaction name on events sent after transaction is over.
Events that got triggered after span/transaction is over, but are connected with a span, must have also `transaction` field set, so that they are searchable in the UI by transaction name.
Also, without `transaction` field set, the red error box is not shown on the transaction details page (like below)
This topic has been discussed on Discord: https://discord.com/channels/621778831602221064/777210445442187274/834151506620973058
Unit tests.

Fix setting transaction name on events sent after transaction is over.

---

.github/workflows/build.yml

We don't use zeus anymore for releases
Craft expects a GitHub artifact named after the commit sha (which is already done on line 55)

remove zeus from ci

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c
sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml

Bump: sentry-native to 0.4.9
https://github.com/getsentry/sentry-native/releases/tag/0.4.9
locally and running tests on device farm
migration page for removing `extractNativeLibs`

Bump: sentry-native to 0.4.9

---

CHANGELOG.md
Makefile
sentry-android-core/build.gradle.kts
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
sentry-android-ndk/src/main/jni/sentry.c
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/CustomEventProcessor.java
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserProviderEventProcessorTest.kt
sentry-test-support/api/sentry-test-support.api
sentry-test-support/src/main/kotlin/io/sentry/test/reflection.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/DuplicateEventDetectionEventProcessor.java
sentry/src/main/java/io/sentry/EventProcessor.java
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEvent.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Fix: Run event processors and enrich transactions with contexts
Event processors were not run for transactions, so contexts were missing.
Some contexts are heavy for Android, hence there's a flag to not do IO nor IPC if it's a transaction.
Spring User is also run, hence transactions for the Spring integration will contain the user info.
Some fields from Event were moved to BaseEvent so transactions contain more data like breadcrumbs, extra, etc...
running and unit tests

Fix: Run event processors and enrich transactions with contexts

---

CHANGELOG.md
sentry-samples/sentry-samples-spring/src/main/java/io/sentry/samples/spring/AppConfig.java
sentry-samples/sentry-samples-spring/src/main/java/io/sentry/samples/spring/AppInitializer.java
sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring-boot-starter/build.gradle.kts
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryProperties.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
sentry-spring/api/sentry-spring.api
sentry-spring/build.gradle.kts
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java
sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java
sentry-spring/src/main/java/io/sentry/spring/SpringSecuritySentryUserProvider.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt
sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserFilterTest.kt

Set user on transaction.
User is set on the scope in Servlet filter - `SentryUserFilter`. This filter must run after Spring security (or any other filter verifying authentication details) so that `SentryUserProvider` implementations can access the currently logged in user data.
In Spring Boot integration, `SentryUserFilter` is set to run:
- by default runs as the last filter (lowest precedence)
- user can explicitly define the order
In Spring integration, filter bean must be created manually and a corresponding `DelegatingFilterProxy` servlet filter must be registered.
Fixes #1335

Fix: set user on transaction

---

CHANGELOG.md
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt
sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt

Fix: Set Span status for OkHttp integration
Fixes #1421 
Unit tests.

Fix: Set Span status for OkHttp integration

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt

Fix: testing names and windows compatibility
Fixes #1393

Fix: testing names and windows compatibility

---

build.gradle.kts
buildSrc/src/main/java/Config.kt
gradle/wrapper/gradle-wrapper.properties
sentry-samples/sentry-samples-spring/build.gradle.kts

Bump: Gradle to 7.0 and plugins
Gradle 7 is less flaky when uploading artifacts to MC
See https://github.com/vanniktech/gradle-maven-publish-plugin/issues/232

Bump: Gradle to 7.0 and plugins

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/Installation.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt

Remove Settings.Secure.ANDROID_ID in favor of generated installationId
https://docs.sentry.io/product/security/mobile-privacy/
Fixes #1446
running it, tests always exists for non null user id

Remove Settings.Secure.ANDROID_ID in favor of generated installationId

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-android-timber/api/sentry-android-timber.api
sentry-android-timber/build.gradle.kts
sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberIntegration.kt
sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberIntegrationTest.kt

Fix: sentry-android-timber package sets sentry.java.android.timber as SDK name
fixes #1175

Fix: sentry-android-timber package sets sentry.java.android.timber as SDK name

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java
sentry-android-core/src/test/java/io/sentry/android/core/AppLifecycleIntegrationTest.kt

Fix: When AppLifecycleIntegration is closed, it should remove observer using UI thread
2021-05-04 16:20:05.210 27271-27444/xxx E/Sentry: Error while closing the Hub.
java.lang.IllegalStateException: Method removeObserver must be called on the main thread
at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
at androidx.lifecycle.LifecycleRegistry.removeObserver(LifecycleRegistry.java:219)
at io.sentry.android.core.AppLifecycleIntegration.close(AppLifecycleIntegration.java:94)
at io.sentry.core.Hub.close(Hub.java:246)
at io.sentry.core.Sentry.close(Sentry.java:216)
at io.sentry.core.HubAdapter.close(HubAdapter.java:57)
at io.sentry.core.ShutdownHookIntegration.lambda$register$0(ShutdownHookIntegration.java:25)
at …

Fix: When AppLifecycleIntegration is closed, it should remove observer using UI thread

---

CHANGELOG.md
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/Config.kt
gradle.properties
sentry-android-core/build.gradle.kts
sentry-android-ndk/build.gradle.kts
sentry-android-okhttp/build.gradle.kts
sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
sentry-android-timber/build.gradle.kts
sentry-android/build.gradle.kts
sentry-apache-http-client-5/src/main/java/io/sentry/transport/apache/ApacheHttpClientTransportFactory.java
sentry-samples/sentry-samples-android/build.gradle.kts
sentry-servlet/build.gradle.kts

Bump: AGP to 4.2.0
be compatible with latest AGPs
CI

Bump: AGP to 4.2.0

---

.gitignore
CHANGELOG.md
Makefile
build.gradle.kts
buildSrc/src/main/java/UnzipUtils.kt
gradle.properties
scripts/release.kts

Fix: Script to deploy to MC via mvn CLI
publishing the artifacts via Gradle is too flaky, we're publishing via the maven CLI now.
https://github.com/gradle/gradle/issues/17082
publishing https://github.com/getsentry/sentry-java/releases/tag/5.0.0-beta.2
work on Craft

Fix: Script to deploy to MC via mvn CLI

---

CHANGELOG.md
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/util/CollectionUtils.java
sentry/src/test/java/io/sentry/util/CollectionUtilsTest.kt

Fix: Fix NPE when adding Context Data with null values for log4j2
Fixes #1386
- [ x] I added tests to verify the changes

Fix: NPE when adding Context Data with null values for log4j2

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/util/ExceptionUtils.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/util/ExceptionUtilsTest.kt

Fix: associate event with transaction when thrown exception is not a direct cause
Fixes #1418
Unit tests.

Fix: associate event with transaction when thrown exception is not a direct cause

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java

Feat: Add breadcrumb in Spring RestTemplate integration
In the process of alignment `OkHttp` integration with Spring `RestTemplate` integration I noticed that we do not add breadcrumb for http request going through `RestTemplate`. With this change, breadcrumb is added no matter if there is an active ongoing transaction.
Unit tests.

Feat: Add breadcrumb in Spring RestTemplate integration

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Stack.java
sentry/src/test/java/io/sentry/StackTest.kt

Fix: Cloning Stack
The root item was added twice, first as exactly the same reference, second as a cloned item.
This fix ensures that root item is added only once as a clone.
Unit tests.

Fix: Cloning Stack

---

CHANGELOG.md
sentry-log4j2/api/sentry-log4j2.api
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt

Add option to enable debug mode in Log4j2 integration.
Fixes #1488
Simplify debugging in cases like https://stackoverflow.com/questions/67690759/why-does-sentry-not-work-with-log4j2-for-me
Unit tests.

Add option to enable debug mode in Log4j2 integration.

---

CHANGELOG.md
sentry-android-okhttp/api/sentry-android-okhttp.api
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt

Add secondary constructor to SentryOkHttpInterceptor.
Without secondary constructor it is inconvenient to pass `beforeSpan` in constructor without using named parameter or from Java.

Feat: Add secondary constructor to SentryOkHttpInterceptor

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/cache/EnvelopeCache.java

Ref: Deprecate cacheDirSize and add maxCacheItems
Fix #1162

Ref: Deprecate cacheDirSize and add maxCacheItems

---

CHANGELOG.md
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt

Fix: Do not append threads that come from the EnvelopeFileObserver
Fix https://github.com/getsentry/sentry-java/issues/1473

Fix: Do not append threads that come from the EnvelopeFileObserver

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/ShutdownHookIntegration.java
sentry/src/test/java/io/sentry/ShutdownHookIntegrationTest.kt

Fix: Graceful Shutdown flushes event instead of Closing SDK
Fix #1458

Fix: Graceful Shutdown flushes event instead of Closing SDK

---

CHANGELOG.md
sentry/src/main/java/io/sentry/DuplicateEventDetectionEventProcessor.java
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryBaseEvent.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/SentryEventTest.kt

Ref: Deprecate SentryBaseEvent#getOriginThrowable and add SentryBaseEvent#getThrowableMechanism
Fix https://github.com/getsentry/sentry-java/issues/1301

Ref: Deprecate SentryBaseEvent#getOriginThrowable and add SentryBaseEvent#getThrowableMechanism

---

CHANGELOG.md
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt

Fix: Append all threads if Hint is Cached but attachThreads is enabled
Ammend to #1501

Fix: Append all threads if Hint is Cached but attachThreads is enabled

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/main/java/io/sentry/SentryEnvelopeItemHeader.java
sentry/src/main/java/io/sentry/SentryEnvelopeItemHeaderAdapter.java
sentry/src/test/java/io/sentry/AttachmentTest.kt
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
sentry/src/test/java/io/sentry/SentryEnvelopeTest.kt
sentry/src/test/resources/envelope-event-attachment.txt

Fix: Add attachmentType to envelope ser/deser.
Extract from https://github.com/getsentry/sentry-java/pull/1256/files

Fix: Add attachmentType to envelope ser/deser.

---

CHANGELOG.md

Craft's [Changelog Policies](https://github.com/getsentry/craft#changelog-policies) show valid examples of changelogs. Versions should be in heading level 2 (instead of the current 1). This will allow automating the release process using Craft.

ref(changelog): Make versions heading level 2

---

CHANGELOG.md
scripts/bump-version.sh

At the moment, `buildVersionCode` and `versionName` have to be updated manually before doing a release. This PR adds a version bumping script, run by Craft on [`prepare`](https://github.com/getsentry/craft#pre-release-command).
- `buildVersionCode` will be incremented by 1.
- `versionName` will be the new version to prepare by Craft. For example, `craft prepare 6.0.0` will set `versionName=6.0.0`, and `craft prepare 6.1.0-alpha.1` will set `versionName=6.1.0-alpha.1`.
Note [Changelog Policies](6.1.0-alpha.1). Current policy is `simple`, so there must be an entry in the changelog with a matching version name for the new release passed to Craft; if not, the command will fail.

feat(release): Delegate version bumping to Craft

---

.craft.yml

Setting Craft's [Changelog Policy](https://github.com/getsentry/craft#changelog-policies) from `simple` to `auto`. After this change, changelog entries can be added to `Unreleased` and Craft will take care of renaming that entry to the new version (while preparing).

ref(release): Changelog policy to auto

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/AndroidManifest.xml
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
sentry-android-core/src/main/java/io/sentry/android/core/AppStartState.java
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/AppStartStateTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/ISpan.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/NoOpSpan.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/protocol/MeasurementValue.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Feat: App start metric
extract from https://github.com/getsentry/sentry-java/pull/1466

Feat: Measure app start time

---

README.md

Do we have a min API for this? Not on the gradle file

kotlin-extensions to readme

---

CHANGELOG.md
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt

Collect markers from logger system in log4j2 and logback appenders.
Adds useful context to logged errors, some more discussion in #1547 
Running test suite for the relevant libraries. 
The change should probably be documented on these pages:
- https://docs.sentry.io/platforms/java/guides/logback/usage/advanced-usage/
- https://docs.sentry.io/platforms/java/guides/log4j2/advanced_usage/
Some inspiration could be had from this docs from the legacy sdk:
- https://docs.sentry.io/platforms/java/guides/logback/legacy/logback/

Capture markers in log4j2 and logback appenders

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt

Fix handling missing Spring Security on classpath on Java 8.
`@ConditionalOnClass` placed on methods ends up with an exception when used with Java 8. This behavior does not exist with Java 11+.
Fixes #1543
Fixes #1546
This bug is related with how classes are loaded, and the test with filtered class does not exactly reproduces the issue. To reproduce this issue we would need to add a separate Gradle module that has no Spring Security on the classpath. Not sure if it's worth it.

Fix handling missing Spring Security on classpath on Java 8.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringIntegrationTest.kt

Set mechanism type in SentryExceptionResolver.
Fixes #1525

Set mechanism type in SentryExceptionResolver.

---

CHANGELOG.md
sentry-android-ndk/src/main/jni/sentry.c

This uses a different method to get string contents from JNI into native options, and avoids excessive stack allocation.

fix: Use a different method to get strings from JNI

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Scope.java
sentry/src/test/java/io/sentry/ScopeTest.kt

We want to expose a method to clear the attachments on the scope.
getsentry/sentry-java#1517
I added a test to ScopeTest to verify that the `clearAttachments` method really clears all attachments.

feat: Add clearAttachments to Scope

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

Assign lastEventId only if event has been sent successfully
Fixes #1414

Assign lastEventId only if event was queued for submission

---

scripts/post-release.sh

After updating the changelog entry policy to `auto` (see https://github.com/getsentry/sentry-java/pull/1520), Craft renames the `Unreleased` entry to the actual version being released. This PR adds the `post-release.sh` script, run after Craft has finished the release (see [docs](https://github.com/getsentry/craft#post-release-command)), creates a new empty entry in the changelog, for future commits.

fix(craft): Add empty `Unreleased` entry to the changelog after release

---

scripts/bump-version.sh
scripts/post-release.sh

Incrementing the version name before the release sets a fixed version until the next release it's made. For testing purposes, it's interesting to have a different version name that doesn't match the name of the version in production (ending with `-SNAPSHOT`). Versions are incremented by increasing by one the last numeric value; for example, `1.2.3` will become `1.2.4`, and `1.2.5-beta.1` will become `1.2.5-beta.2`. The first version in these examples is the released version (the argument Craft takes). Note, however, that versions must end with a number: `1.2.3-alpha` is a semantic version but not compatible with this post-release script (doesn't end with a number), and `1.2.3-alpha.0` should be used instead.
Once incremented the version name, the version code has also to be incremented to …

fix(craft): Increment versions in post-release

---

scripts/bump-version.sh
scripts/post-release.sh

Adds a missing and required variable to `scripts/post-release.sh`, run by Craft after a release.

fix(release): Add missing var to post-release script

---

.craft.yml

This PR adds the `symbol-collector` target to support https://github.com/getsentry/craft/pull/266. It also changes the target order, so that:
- `symbol-collector` runs before `maven`, since the former is reentrant and the latter isn't.
- `github` and `registry` targets go after `symbol-collector` and `maven`, since the first two should only be run once the actual release has been made.

feat(craft): Add `symbol-collector` target

---

CHANGELOG.md

Updates sentry-native to 0.4.11
fixes #1561
may help with: #1549 and #1477

feat: Update sentry-native to 0.4.11

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryTraceHeader.java
sentry/src/main/java/io/sentry/exception/InvalidSentryTraceHeaderException.java
sentry/src/test/java/io/sentry/SentryTraceHeaderTest.kt

Fix: Do not throw IAE when tracing header contain invalid trace id.
Fixes #1604
Unit tests

Fix: Do not throw IAE when tracing header contain invalid trace id.

---

CHANGELOG.md
sentry-log4j2/api/sentry-log4j2.api
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-logback/api/sentry-logback.api
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java

Make SentryAppender non-final for Log4j2 and Logback
Users will be able to customize the appenders it if they need it. See #1602
Did a full build (I had to disable OutboxSenderTest class, `deserialize sample envelope with event and two attachments` test, SentryWebfluxIntegrationTest (due to an Error while closing the hub),  but I believe those are not related to to my changes at all.

Make SentryAppender non-final for Log4j2 and Logback (#1602)

---

sentry/src/main/java/io/sentry/ISpan.java

The code comment for toTraceHeader was not accurate.
This is fixed now.
We noticed that in a PR for sentry-cocoa: https://github.com/getsentry/sentry-cocoa/pull/1213#discussion_r668664485
CI.

docs: Fix code doc for toTraceHeader

---

CHANGELOG.md
README.md
buildSrc/src/main/java/Config.kt
sentry-android-fragment/build.gradle.kts

https://mvnrepository.com/artifact/androidx.fragment/fragment and https://androidx.tech/artifacts/fragment/fragment/ state min API 14
Fix https://github.com/getsentry/sentry-java/issues/1607
CI

Fix: set min sdk version of sentry-android-fragment to API 14

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryEnvelopeItemHeaderAdapter.java
sentry/src/test/java/io/sentry/SentryEnvelopeTest.kt
sentry/src/test/resources/envelope-feedback.txt

Fix: Ser/Deser of the UserFeedback from cached envelope #1611
Fix https://github.com/getsentry/sentry-dart/issues/534

Fix: Ser/Deser of the UserFeedback from cached envelope

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-android-core/api/sentry-android-core.api
sentry-android-core/build.gradle.kts
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesState.java
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
sentry-android-core/src/main/java/io/sentry/android/core/AppStartState.java
sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityFramesTrackerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/SpanFinishedCallback.java
sentry/src/main/java/io/sentry/TransactionFinishedCallback.java
sentry/src/main/java/io/sentry/TransactionListener.java
sentry/src/main/java/io/sentry/protocol/MeasurementValue.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Feat: Slow/Frozen frames metrics
Closes https://github.com/getsentry/sentry-java/pull/1466

Feat: Slow/Frozen frames metrics

---

CHANGELOG.md
sentry-openfeign/api/sentry-openfeign.api
sentry-openfeign/src/main/java/io/sentry/openfeign/SentryCapability.java

Add more convenient way to pass `BeforeSpanCallback` in OpenFeign integration.
There was no way to pass `BeforeSpanCallback` without passing also a `Hub`.

Add more convenient way to pass `BeforeSpanCallback` in OpenFeign integration.

---

build.gradle.kts
buildSrc/src/main/java/Config.kt
sentry-servlet/build.gradle.kts
sentry-spring-boot-starter/build.gradle.kts
sentry-spring/build.gradle.kts

Use plugins {} block for applying plugins
Apply plugin is deprecated in Gradle 7.0
Fixes #1453

Use plugins {} block for applying plugins

---

CHANGELOG.md
sentry/src/main/java/io/sentry/config/CompositePropertiesProvider.java
sentry/src/test/java/io/sentry/config/CompositePropertiesProviderTest.kt

Merge external map properties
Fixes #874
Now tags can be set in multiple places: some in properties file, some in env variables. The resulting options will contain tags from all places.
Unit tests
Not breaking in terms of compilation, but resulting tags can differ if they were set in different places (unlikely though).
The order of loading properties can (and probably should) be changed. Providers order by priority I think should be:
- system property
- properties files
- environment variables

Merge external map properties

---

CHANGELOG.md
sentry-android-okhttp/api/sentry-android-okhttp.api
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt

Add secondary constructor taking `IHub` to `SentryOkHttpInterceptor`.
For the sake of improving Java compatiblity when users want to set only `IHub` and skip `BeforeSendCallback`.
Fixes #1526

Add secondary constructor taking `IHub` to `SentryOkHttpInterceptor`.

---

CHANGELOG.md
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/SentryTaskDecorator.java
sentry-spring/src/test/kotlin/io/sentry/spring/mvc/SentrySpringIntegrationTest.kt

Add support for async methods in Spring MVC.
Using the same technique as for coroutines and Webflux, using a task decorator propagates Hub with Scope to the executing thread in async tasks.
Fixes #1226
Fixes #1107
Sample how it can be used: https://github.com/maciej-scratches/sentry-spring-mvc-async-controller/blob/master/src/main/java/com/example/springasynccontroller/SpringAsyncControllerApplication.java
Integration tests, sample project.
Add reference docs.

Add support for async methods in Spring MVC.

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentrySpringFilter.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringFilterTest.kt

Fix: Make sure scope is popped when processing request results in exception
In case of error, the scope has not been popped.
Unit tests.

Fix: Make sure scope is popped when processing request results in exception

---

sentry-android-ndk/build.gradle.kts
settings.gradle.kts

The previous way of bootstrapping the native submodule didn't really work for me (the `sentry-native` folder was always empty after a gradle sync, hence `cmake` couldn't succeed)
* `rm -rf sentry-java`
* `git clone git@github.com:getsentry/sentry-java.git`
* `idea sentry-java`
* Do a gradle sync -> shouldn't fail

fix: Properly bootstrap ndk

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Scope.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Fix: Do not drop Contexts key if Collection, Array or Char
```
Sentry.configureScope(scope -> {
scope.setContexts("inventory", new String[] {"big potion", "small potion"});
});
```
would be dropped because it'd fall to `setContexts(String, Object)` but reflection would make an array instead of an object and array as a value, hence adding convenient method for the missing Java Data types

Fix: Do not drop Contexts key if Collection, Array or Char

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java

Add explicit support for Servlet API 3.1 (used by Tomcat 8.5), fix classes that previously relied on default `javax.servlet.Filter` methods introduced in Servlet 4.0 specs. 
Fixes #1677
Built a sample war file, deployed to Tomcat 8.5.

Fix Servlet 3.1 compatibility issue

---

sentry/api/sentry.api
sentry/src/main/java/io/sentry/JsonObjectReader.java
sentry/src/main/java/io/sentry/protocol/Mechanism.java
sentry/src/main/java/io/sentry/protocol/SentryException.java
sentry/src/main/java/io/sentry/protocol/SentryStackFrame.java
sentry/src/main/java/io/sentry/protocol/SentryStackTrace.java
sentry/src/main/java/io/sentry/protocol/SentryThread.java
sentry/src/test/java/io/sentry/JsonUnknownSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/MechanismSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/SentryExceptionSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/SentryStackFrameSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/SentryStackTraceSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/SentryThreadSerializationTest.kt
sentry/src/test/resources/gson/mechanism.json
sentry/src/test/resources/gson/sentry_exception.json
sentry/src/test/resources/gson/sentry_stack_frame.json
sentry/src/test/resources/gson/sentry_stack_trace.json
sentry/src/test/resources/gson/sentry_thread.json

- Implement serialization/deserialization for `SentryThread`
- Implement serialization/deserialization for `SentryStackTrace`
- Implement serialization/deserialization for `SentryStackFrame`
- Change `JsonUnknownSerializationTest` to parameterized test to avoid duplication.
- Added tests.

Vendor JSON: SentryThread

---

CHANGELOG.md
sentry-android-core/proguard-rules.pro

Updated proguard rule to target library enums only.
This is a consumer proguard file, which means it is included into consumer application proguard config, and if we target `*`, it will apply to each class of consumer application too. This unreasonably prevents obfuscation of consumer application enums.
Fixes #1684
Didn't test.
I think it's a breaking change because consumer application could accidentally rely on this rule, and removing it may break obfucated code.

Update proguard keep rule for enums

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SpanContext.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/OutboxSenderTest.kt
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Move tags from `transaction.contexts.trace.tags` to `transaction.tags`.
Fixes #1693
The implementation could be cleaner - like introducing a dedicated `TraceContext` object, but this would mean we introduce a breaking change - something to keep in mind for 6.0.
Unit tests.

Fix: Move tags from transaction.contexts.trace.tags to transaction.tags

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt
sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanWebClientCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientWebRequestFilter.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/TracingOrigins.java
sentry/src/test/java/io/sentry/SentryOptionsTest.kt
sentry/src/test/java/io/sentry/TracingOriginsTest.kt

Add `tracingOrigins` to `SentryOptions` and respect it in OkHttp, WebClient and RestTemplate integrations.
Fixes #1697
Fixes #1585
Integration tests.

Feat: Add option to filter which origins receive tracing headers

---

CHANGELOG.md
sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Breadcrumb.java
sentry/src/test/java/io/sentry/BreadcrumbTest.kt

Add static helper methods for creating breadcrumbs, that render in special way in the UI.
Breadcrumbs created using these methods look following:
The question is if there is a value in having separate UI and User breadcrumb - as far as I can see they render the same way.
Fixes #361
Unit tests.

Feat: Add static helpers for creating breadcrumbs.

---

sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt
sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
sentry-openfeign/src/main/java/io/sentry/openfeign/SentryFeignClient.java
sentry-openfeign/src/test/kotlin/io/sentry/openfeign/SentryFeignClientTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SpanContext.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Fix: drop spans in BeforeSpanCallback. #1713
Fixes #1708

Fix: drop spans in BeforeSpanCallback.

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

Should not capture unfinished transaction.
Fixes #1704
Unit tests.

Fix: Should not capture unfinished transaction

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ISpan.java
sentry/src/main/java/io/sentry/NoOpSpan.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/main/java/io/sentry/protocol/SentrySpan.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/test/java/io/sentry/GsonSerializerTest.kt
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Add "data" to spans.
Fixes #1233

Feat: Add "data" to spans

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java
sentry/src/test/java/io/sentry/HubTest.kt

Fix: Don't set lastEventId for transactions
Fixes #1709
Unit tests.

Fix: Don't set lastEventId for transactions

---

CHANGELOG.md
sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt
sentry-apollo/src/test/java/io/sentry/apollo/SentryApolloInterceptorTest.kt

Feat: Add breadcrumbs for the Apollo integration
Fixes #1721
Unit tests.

Feat: Add breadcrumbs for the Apollo integration

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt

Fix: ActivityLifecycleIntegration#appStartSpan memory leak
#1731
unit test and leak canary

Fix: ActivityLifecycleIntegration#appStartSpan memory leak

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
sentry-android-core/src/test/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegrationTest.kt

Fix: Handle exception if Context.registerReceiver throws
Caused by: java.lang.SecurityException: 
at android.os.Parcel.createExceptionOrNull (Parcel.java:2385)
at android.os.Parcel.createException (Parcel.java:2369)
at android.os.Parcel.readException (Parcel.java:2352)
at android.os.Parcel.readException (Parcel.java:2294)
at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature (IActivityManager.java:6381)
at android.app.ContextImpl.registerReceiverInternal (ContextImpl.java:1696)
at android.app.ContextImpl.registerReceiver (ContextImpl.java:1650)
at android.app.ContextImpl.registerReceiver (ContextImpl.java:1638)
at android.content.ContextWrapper.registerReceiver (ContextWrapper.java:686)
at io.sentry.android.core.SystemEventsBreadcrumbsIntegration.register …

Fix: Handle exception if Context.registerReceiver throws

---

CHANGELOG.md
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryCrashLastRunState.java
sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/SentryCrashLastRunStateTest.kt
sentry/src/test/java/io/sentry/SentryTest.kt
sentry/src/test/java/io/sentry/cache/EnvelopeCacheTest.kt

Crashed last run
Closes https://github.com/getsentry/sentry-java/issues/1125
running and unit tests, also by the Unity integration

Crashed last run

---

CHANGELOG.md
sentry/src/main/java/io/sentry/JsonSerializer.java

- Log serialisable objects (with pretty printing)
- Serialize any object, not just `JsonSerializable`
Closes #1792
This functionality was lost when replacing GSON.
- Checked wether serialized object was logged correctly.

Debug log serializable objects

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java

Fix: ActivityFramesTracker does not throw if Activity has no observers
Closes https://github.com/getsentry/sentry-java/issues/1798

Fix: ActivityFramesTracker does not throw if Activity has no observers

---

CHANGELOG.md
sentry-graphql/api/sentry-graphql.api
sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java

Feat: Add secondary constructor to `SentryInstrumentation`.
It wasn't possible to pass `BeforeSpanCallback` without passing the `Hub`.

Feat: Add secondary constructor to `SentryInstrumentation`.

---

CHANGELOG.md
sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt
sentry-android-fragment/src/test/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacksTest.kt

Fix: Do not start fragment span if not added to the Activity
Closes https://github.com/getsentry/sentry-java/issues/1787
running https://github.com/LouisFn/SentryFrozenFrame and repo's sample with added/visible fragments

Fix: Do not start fragment span if not added to the Activity

---

CHANGELOG.md
sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt

Rename Fragment span operation from `ui.fragment.load` to `ui.load`
Closes https://github.com/getsentry/sentry-java/issues/1820

Ref: Rename Fragment span operation from `ui.fragment.load` to `ui.load`

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/protocol/Device.java

Feat: Add locale to device context and deprecate language
`language` now returns only the language eg `en` instead of `en_US`, since the `language` field was never indexed, its not a breaking change on discover and alerts
`language` was actually the `locale`, and `locale` was missing.
Closes https://github.com/getsentry/sentry-java/issues/1834
unit tests
add Support for https://develop.sentry.dev/sdk/event-payloads/contexts/#culture-context

Feat: Add locale to device context and deprecate language

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt

Bump log4j-api,log4j-core from 2.13.3 to 2.15.0
**CVE-2021-44228**
Log4j versions prior to 2.15.0 are subject to a remote code execution vulnerability via the ldap JNDI parser.

Bump: log4j to 2.15.0

---

.github/workflows/build.yml

Default behavior is to warn and one must read the build detail to spot that.
Example: A build that was successful, now fails with:

chore(ci): break ci if missing artifact

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/instrumentation/file/FileIOSpanManager.java
sentry/src/main/java/io/sentry/instrumentation/file/FileInputStreamInitData.java
sentry/src/main/java/io/sentry/instrumentation/file/FileOutputStreamInitData.java
sentry/src/main/java/io/sentry/instrumentation/file/SentryFileInputStream.java
sentry/src/main/java/io/sentry/instrumentation/file/SentryFileOutputStream.java
sentry/src/main/java/io/sentry/util/StringUtils.java
sentry/src/test/java/io/sentry/instrumentation/file/SentryFileInputStreamTest.kt
sentry/src/test/java/io/sentry/instrumentation/file/SentryFileOutputStreamTest.kt
sentry/src/test/java/io/sentry/util/StringUtilsTest.kt

* Added `SentryFileInputStream` implementation for `FileInputStream` instrumentation
* Added `SentryFileOutputStream` implementation for `FileOutputStream` instrumentation
This is a supporting PR with runtime classes for File I/O instrumentation see https://github.com/getsentry/sentry-android-gradle-plugin/pull/239
* Will follow up with another PR for `FileReader/Writer`
* Will update docs to show how to manually use it

feat: Add runtime classes for FileIOStream instrumentation

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt

Bump log4j-api,log4j-core from 2.15.0 to 2.16.0
[CVE 2021-45046](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45046)
Apache Log4j2 Thread Context Message Pattern and Context Lookup Pattern vulnerable to a denial of service attack.

Bump: log4j to 2.16.0

---

.github/workflows/build.yml

Bump CI Actions

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
sentry-android-core/src/main/java/io/sentry/android/core/AppStartState.java

Fix: Make App start cold/warm visible to Hybrid SDKs
https://github.com/getsentry/sentry-react-native/issues/1968
React native reads the Cold or Warm start from the Android SDK, but the Android SDK only sets it if performance is enabled on the Android SDK as well, by default, performance is not enabled, only on the RN SDK, hence we have to flip the flag anyway, even if performance is disabled on the Android SDK.

Fix: Make App start cold/warm visible to Hybrid SDKs

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt

Bump log4j-api, log4j-core from 2.16.0 to 2.17.0
[CVE-2021-45105](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45105)
Apache Log4j2 does not always protect from infinite recursion in lookup evaluation

Bump: log4j to 2.17.0

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt

Upgrade logback to 1.2.9 to address LOGBACK-1591/CVE-2021-42550
details https://github.com/getsentry/sentry-java/pull/1849

Upgrade logback to 1.2.9 to address LOGBACK-1591/CVE-2021-42550

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt

Do not create SentryExceptionResolver bean when Spring MVC is not on the classpath
Fixes #1863
Integration test.

Fix: Do not create SentryExceptionResolver bean when Spring MVC is not on the classpath

---

CHANGELOG.md
sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SentryInitializer.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryOptions.java

Ref: Add shutdownTimeoutMillis in favor of shutdownTimeout
Closes https://github.com/getsentry/sentry-java/issues/1530

Ref: Add shutdownTimeoutMillis in favor of shutdownTimeout

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/test/java/io/sentry/AttachmentTest.kt
sentry/src/test/java/io/sentry/JsonSerializerTest.kt

Ref: Remove Attachment ContentType since the Server infers it
Closes https://github.com/getsentry/sentry-cocoa/issues/1196

Ref: Remove Attachment ContentType since the Server infers it

---

CHANGELOG.md
sentry-servlet/build.gradle.kts

Change scope of servlet-api to compileOnly.
`servlet-api` should be a compile dependency, users should include servlet-api independently or the application server application runs on provides this dependency in runtime.
Fixes #1878

Fix: Change scope of servlet-api to compileOnly.

---

CHANGELOG.md
sentry-openfeign/src/main/java/io/sentry/openfeign/SentryFeignClient.java
sentry-openfeign/src/test/kotlin/io/sentry/openfeign/SentryFeignClientTest.kt

When response body is null, set size to 0
in a same fashion "request_body_size" is set.
Add test.
Add note to the changelog
Closes #1883 , see description there
I wrote a test.
Had no time to build the project and run the tests locally, TBH

Fix NPE while adding "response_body_size" breadcrumb

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java
sentry/src/test/java/io/sentry/UncaughtExceptionHandlerIntegrationTest.kt

Adds
```java
options.printUncaughtStackTrace
```
#1077

Add options.printUncaughtStackTrace

---

CHANGELOG.md
sentry-android-timber/api/sentry-android-timber.api
sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt
sentry-samples/sentry-samples-android/build.gradle.kts
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MyApplication.java
sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
sentry-samples/sentry-samples-android/src/main/res/values/strings.xml

* Overridden all Timber.Tree methods to have full control over the log message
* Supply `formatted` and `params` fields if the log-call was made with args
* Do not include stackframes into a message
How this looks now:
Grouping seems to work as well:
Closes #1177 
1. We can't access tag from Timber because it's [package-private](https://github.com/JakeWharton/timber/blob/84b157605552e7b30f0d20e105d383b48ce8a030/timber/src/main/java/timber/log/Timber.java#L377-L386), so I had to drop it.
2. Since we set the Message ourselves, the stacktraces are not reported as breadcrumbs anymore (previously, Timber default implementation would put a stacktrace into a message variable and we would record a breadcrumb with the exception) - should we still do this?

fix: Do not include stacktrace into Timber message

---

CHANGELOG.md
sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/SentryInitBeanPostProcessorTest.kt
sentry/src/main/java/io/sentry/HostnameCache.java
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/Sentry.java

Fix potential memory leaks - happening either when Sentry works in servlet environment on application undeployment - or when more than one integration is active.
Running a sample application. I am not sure if there is a way to write a test for that.

Fix potential memory leaks.

---

.craft.yml
scripts/post-release.sh

We don't rely on version numbers here, so we can skip those. This will make `-u` flag happy (unbound variable), thus it should make script runner happy.
Possibly closes https://github.com/getsentry/sentry-java/issues/1817

ci: Bump craft and update post-release script

---

CHANGELOG.md
sentry-openfeign/src/main/java/io/sentry/openfeign/SentryFeignClient.java

Closes https://github.com/getsentry/sentry-java/issues/1907 , see description there
Tested by researching API of dependency (OpenFeign)

Fix NPE while adding "response_body_size" breadcrumb (#1907)

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/NdkIntegrationTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
sentry/src/main/java/io/sentry/SentryOptions.java

Feat: Enable enableScopeSync by default for Android
Closes https://github.com/getsentry/sentry-java/issues/1914

Feat: Enable enableScopeSync by default for Android

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java
sentry-android-core/src/main/java/io/sentry/android/core/LoadClass.java

Ref: Make ActivityFramesTracker public to be used by Hybrid SDKs
https://github.com/getsentry/sentry-dart/pull/772/files#r816056795
Also https://github.com/getsentry/sentry-java/pull/1922

Ref: Make ActivityFramesTracker public to be used by Hybrid SDKs

---

sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java

docs: Fix typo in SentryAndroidOptions

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/main/java/io/sentry/Span.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt
sentry/src/test/java/io/sentry/SpanTest.kt

Fix: If transaction or span is finished, do not allow to mutate
Closes https://github.com/getsentry/sentry-java/issues/1840

Fix: If transaction or span is finished, do not allow to mutate

---

CHANGELOG.md
sentry-android-core/proguard-rules.pro

fix: Exclude classes that we are checking at runtime from obfuscation

---

scripts/post-release.sh

Prevent it from adding `.installation` file and fail quick on the first error.

misc: Update post-release script

---

CHANGELOG.md
sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt

Closes https://github.com/getsentry/sentry-java/issues/1956

Fix: Sentry Timber integration does not submit msg.formatted breadcrumbs

---

CHANGELOG.md
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
sentry-log4j2/api/sentry-log4j2.api
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
sentry-samples/sentry-samples-jul/src/main/resources/sentry.properties
sentry-samples/sentry-samples-log4j2/src/main/java/io/sentry/samples/log4j2/Main.java
sentry-samples/sentry-samples-log4j2/src/main/resources/log4j2.xml
sentry-samples/sentry-samples-logback/src/main/java/io/sentry/samples/logback/Main.java
sentry-samples/sentry-samples-logback/src/main/resources/logback.xml
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ExternalOptions.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
sentry/src/test/java/io/sentry/SentryOptionsTest.kt

Add option to specify MDC tag names that are mean to be applied as Sentry tags to Sentry events instead of putting into event contexts as we used to do.
Fixes #1148

Pass MDC tags as Sentry tags 

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java

fix: ANR watcher wont crash on sec excep

---

README.md

Added https://blog.sentry.io/2022/03/30/android-manifest-placeholders/
Using bullet list to reduce spacing.

blog android manifest on readme

---

.github/workflows/release.yml
CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/main/java/io/sentry/android/core/ScreenshotEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ScreenshotEventProcessorTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Attachment.java
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/TypeCheckHint.java
sentry/src/test/java/io/sentry/AttachmentTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

Feat: screenshots
https://develop.sentry.dev/sdk/features/#screenshots=
Users may want to see what's in the screen when there's an error or crash.
Running and unit tests

Feat: screenshots

---

CHANGELOG.md
sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt

Brings back `TimberTag`. Closes #1900
We are relying heavily on `TimberTag` value. One of our dependencies is abusing Timber logging. We were using this tag to filter out these events. This is a blocker to upgrade Sentry for us.
I decided not to use reflection, since retrieving value is not enough. We would also have to write `tag` clearing logic via reflection.
Pros: 
- This approach will not break if internal Timber's tag management logic change in the future.
- No need to write tag clearing logic
Cons:
- Timber will format `message` string, which we don't use (performance)
Unit test

Fix: Add TimberTag

---

CHANGELOG.md
sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt

fix: Timber throwing on args usage

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/test/java/io/sentry/UncaughtExceptionHandlerIntegrationTest.kt

Continuation of https://github.com/getsentry/sentry-java/pull/1890 and #1750

Ref: Make options.printUncaughtStackTrace primitive type

---

.craft.yml
.github/ISSUE_TEMPLATE/bug_report_java.yml
CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-servlet-jakarta/api/sentry-servlet-jakarta.api
sentry-servlet-jakarta/build.gradle.kts
sentry-servlet-jakarta/src/main/java/io/sentry/servlet/jakarta/SentryRequestHttpServletRequestProcessor.java
sentry-servlet-jakarta/src/main/java/io/sentry/servlet/jakarta/SentryServletContainerInitializer.java
sentry-servlet-jakarta/src/main/java/io/sentry/servlet/jakarta/SentryServletRequestListener.java
sentry-servlet-jakarta/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
sentry-servlet-jakarta/src/test/kotlin/io/sentry/servlet/jakarta/SentryRequestHttpServletRequestProcessorTest.kt
sentry-servlet-jakarta/src/test/kotlin/io/sentry/servlet/jakarta/SentryServletContainerInitializerTest.kt
sentry-servlet-jakarta/src/test/kotlin/io/sentry/servlet/jakarta/SentryServletRequestListenerTest.kt
settings.gradle.kts

Add `sentry-servlet-jakarta` module to support `jakarta.servlet-api` which has been moved from `javax.servlet-api`.
Partially fixes https://github.com/getsentry/sentry-java/issues/1789
Spring and Spring Boot require more investigation: https://github.com/getsentry/sentry-java/issues/1984

Add sentry-servlet-jakarta module

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-apache-http-client-5/build.gradle.kts
sentry-servlet-jakarta/build.gradle.kts
sentry-servlet/build.gradle.kts
sentry-spring-boot-starter/build.gradle.kts
sentry-spring/build.gradle.kts

Upgrade Spring Boot dependency to 2.5.13
Fixes #2010

Upgrade Spring Boot dependency to 2.5.13

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryClient.java

Event drop vs session update inconsistencies have been discussed in the Client Infra TSC. Python implementation has been updated to serve as reference implementation. We now only want to update the session when an event is dropped due to sampling but not if it is dropped due to any other filtering mechanism (`beforeSend`, `eventProcessor`, `ignoredExceptionsForType`). Also the order of the filtering mechanisms should be aligned across SDKs.
Fixes: https://github.com/getsentry/sentry-java/issues/1916
More Info:
* https://github.com/getsentry/develop/pull/551
* https://github.com/getsentry/develop/issues/537
* https://github.com/getsentry/sentry-python/pull/1390
* https://github.com/getsentry/sentry-python/pull/1394
* Clarify some open questions regarding early return vs sending the session …

Change order of event filtering mechanisms

---

CHANGELOG.md
CONTRIBUTING.md
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt

Enables users to override the SDK info
This allows other SDKs that use sentry-cocoa internally to identify the events. Enables https://github.com/getsentry/sentry-unity/issues/616
Added a test case

Feat: Allow setting SDK info (name & version) in manifest

---

CHANGELOG.md
gradle.properties
sentry-android-ndk/build.gradle.kts

Enables integrations, e.g. sentry-unity SDK, to override the native SDK name reported in errors
not sure how to test this except manually - are there some integration tests already that this could be included in?

Feat: Android native SDK name override

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Also apply changes from #2001 and #2002 to `5.x`.
To align event filter order and update of sessions for dropped events across SDKs (https://github.com/getsentry/develop/pull/551)
Unit Tests
- New release after merge

Change order of event filtering mechanisms and only send session update for dropped events if session state changed

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt

SentryThread.current flag will not be overridden by DefaultAndroidEventProcessor if already true
Fixes https://github.com/getsentry/sentry-java/issues/2047
Unit Test

SentryThread.current flag will not be overridden by DefaultAndroidEventProcessor if already set

---

CHANGELOG.md
sentry/src/main/java/io/sentry/ISerializer.java
sentry/src/main/java/io/sentry/JsonSerializer.java
sentry/src/test/java/io/sentry/JsonSerializerTest.kt

No longer (auto) close the `OutputStream` that is passed into `JsonSerializer`. This caused problems when passing in `System.out` from `StdoutTransport` as it closed the stream.
Fixes #2027 for `6.x`
* Unit Test
* code sample

No longer close OutputStream that is passed into JsonSerializer

---

CHANGELOG.md
sentry/src/main/java/io/sentry/JsonReflectionObjectSerializer.java
sentry/src/test/java/io/sentry/JsonReflectionObjectSerializerTest.kt
sentry/src/test/java/io/sentry/JsonSerializerTest.kt

Handle `Number` inside `JsonReflectionObjectSerializer` which includes `Long`.
Fixes https://github.com/getsentry/sentry-java/issues/2044
Unit Test

Fix serialization of Long inside of Request.data

---

buildSrc/src/main/java/Config.kt
sentry-samples/sentry-samples-jul/build.gradle.kts
sentry-samples/sentry-samples-jul/src/main/java/io/sentry/samples/jul/Main.java
sentry-samples/sentry-samples-jul/src/main/resources/logging.properties

Improve jul sample for easier debugging inside IDE
This way it's easier to start from IDE in debugging mode. Code before didn't use `logging.properties` in that case and handler also wasn't used when starting from IDE.
Also replaced logback dependency with slf4j to get access to `MDC`.
locally

Improve jul sample for easier debugging inside IDE

---

sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
sentry-spring/api/sentry-spring.api
sentry-spring/build.gradle.kts
sentry-spring/src/main/java/io/sentry/spring/ContextTagsEventProcessor.java
sentry-spring/src/test/kotlin/io/sentry/spring/ContextTagsEventProcessorTest.kt

Move ContextTagsEventProcessor from spring boot to spring module
So Spring (without boot) can also use the `ContextTagsEventProcessor`

Move ContextTagsEventProcessor from spring boot to spring module

---

CHANGELOG.md

Fix triple `Fixes` heading in `6.0.0-beta.4` changelog as well as links to issues on some of the entries.
Consistency

Fix changelog for 6.0.0-beta.4

---

CHANGELOG.md
sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java

No longer used the options property in SentryAppender, instead get Options from HubAdapter.
Fix https://github.com/getsentry/sentry-java/issues/2043 for Logback
Demo Code

Calling Sentry.init and specifying contextTags now has an effect on the Logback SentryAppender

---

CHANGELOG.md
sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java

No longer used the `contextTags` property in `SentryAppender`, instead get via Options from HubAdapter.
Fix https://github.com/getsentry/sentry-java/issues/2043 for Log4j
Demo code

Calling Sentry.init and specifying contextTags now has an effect on the Log4j SentryAppender

---

CHANGELOG.md
sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java

No longer used the options property in SentryAppender, instead get Options from HubAdapter.
Fix #2043 for jul
Demo Code

Calling Sentry.init and specifying contextTags now has an effect on the jul SentryAppender

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/test/java/io/sentry/SentryTest.kt

When a call to `Sentry` happens before `Sentry.init`, the `currentHub` is set to a `NoOpHub`. If `Sentry.init` is then called in a different thread, the thread where `Sentry` was called before `init` is poisoned without this change. By checking if the `currentHub` is a `NoOpHub` we can allow the poisoned thread to self heal.
Happened to a customer who set up a thread pool and had executions happen before being able to initialize Sentry.
Unit Test
Discuss if this has any consequences I can't see.
Resolves #2079

Sentry recovers after a Thread had currentHub set to a NoOpHub

---

CHANGELOG.md
sentry-android-core/proguard-rules.pro

To mitigate failures with R8 on AGP 7.3.0-betaX and 7.4.0-alphaX https://issuetracker.google.com/issues/235733922

Workaround R8 bug by adding a new proguard rule

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/SentryOptions.java

Allows developers to deserialize `ExternalOptions` and then merge them into `SentryOptions`.
Closes https://github.com/getsentry/sentry-java/issues/2086
-

SentryOptions#merge is now public and can be used to load ExternalOptions

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt

Allow opting out of device info collection that requires Inter-Process Communication (IPC)
A way of avoiding https://github.com/getsentry/sentry-java/issues/2095

Allow opting out of device info collection that requires Inter-Process Communication (IPC)

---

sentry/src/main/java/io/sentry/vendor/gson/stream/JsonReader.java

Fix javadoc in `JsonReader`
Release build for `6.1.1` failed due to javadoc not being able to generate docs.
* Release build: https://github.com/getsentry/publish/runs/6937404260?check_suite_focus=true
* Build of the release commit: https://github.com/getsentry/sentry-java/runs/6937346695?check_suite_focus=true
* Release commit: https://github.com/getsentry/sentry-java/commit/07534f52d4aa7e181ab6938aa4415b0e46970d75
Ran `./gradlew aggregateJavadocs` locally.

Fix javadoc in JsonReader

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Baggage.java
sentry/src/test/java/io/sentry/BaggageTest.kt

Use charset string directly as StandardCharsets is not available on earlier Android versions
> Field requires API level 19 (current min is 16): java.nio.charset.StandardCharsets#UTF_8

Use charset string to support Android 16

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/LifecycleWatcher.java
sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/SentryGestureListener.java
sentry-android-core/src/test/java/io/sentry/android/core/LifecycleWatcherTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/internal/gestures/SentryGestureListenerTracingTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ITransaction.java
sentry/src/main/java/io/sentry/NoOpTransaction.java
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt

`Timer` was created for every transaction which caused a new thread to be spawned each time. With this PR the `Timer` is only created in `SentryTracer` if `idleTimeout` is set there. When the transaction is finished, the timer is cancelled.
Fixes https://github.com/getsentry/sentry-java/issues/2115
- Spring Boot App with transactions, before PR threads would be spawned, with code from PR no timer threads are spawned

Fix thread leak due to `Timer` being created and never cancelled

---

.craft.yml

Add new modules to craft.yml

---

sentry-android-navigation/src/main/java/io/sentry/android/navigation/SentryNavigationListener.kt
sentry-compose/api/android/sentry-compose.api
sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryNavigationIntegration.kt
sentry-compose/src/androidTest/kotlin/io/sentry/compose/SentryLifecycleObserverTest.kt

* Adds KDoc for new integrations
* Adds boolean flags for `withSentryObservableEffect` composable to control breadcrumbs and tracing

Add KDoc and boolean flags for compose integration

---

CHANGELOG.md
sentry/src/main/java/io/sentry/TraceContext.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt

See https://github.com/getsentry/develop/pull/625
Replaces https://github.com/getsentry/sentry-java/pull/2145 and not only skips `userId` in `baggage` but also in the envelope header `trace`.

Only send userid in Dynamic Sampling Context if sendDefaultPii is true

---

CHANGELOG.md
sentry/src/main/java/io/sentry/TraceContext.java
sentry/src/test/java/io/sentry/SentryTracerTest.kt

Remove userId from baggage due to PII
https://github.com/getsentry/team-mobile/issues/23#issuecomment-1175091426
Commented out tests

Remove userId from baggage due to PII

---

.craft.yml
Makefile
build.gradle.kts
buildSrc/src/main/java/Config.kt
buildSrc/src/main/java/Publication.kt
sentry-compose/build.gradle.kts
sentry-compose/gradle.properties

Configure multiplatform distributions to publish compose artifacts. The maven-publish task spits out everything into the same folder for all targets (common, android and desktop), so we have to manually configure the distribution task to pick up from the correct locations for each target. There's also a different artifact gonna be publish for each target, that's why the release registry has to be updated as well:
https://github.com/getsentry/sentry-release-registry/pull/79

feat: Configure publishing for compose multiplatform artifacts

---

CHANGELOG.md
sentry-android-core/build.gradle.kts
sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
sentry-android-fragment/build.gradle.kts
sentry-android-okhttp/build.gradle.kts
sentry-android-timber/build.gradle.kts
sentry-samples/sentry-samples-android/build.gradle.kts

Switch to compileOnly upstream dependencies in integrations, so we do not override user-defined version and use what they actually have on their classpath.
Closes #2125 
Tested manually here and on SAGP
@adinauer I'm not sure if you want to do this for backend things, I think it can also be applicable there? We could create another issue, for now I'm afraid of breaking something there

feat: Make upstream dependencies compileOnly in integrations

---

CHANGELOG.md
sentry-spring-boot-starter/src/main/resources/META-INF/spring.factories

Remove extra space from `spring.factories` causing issues in old versions of Spring Boot
Fixes #2178

Remove extra space from `spring.factories` causing issues in old versions of Spring Boot

---

scripts/update-gradle.sh

Ensures updater workflow doesn't fail because `./gradlew --version` reports a different version than the tag on github.com/gradle/gradle, when the tag ends with a zero.

fix: update-gradle.sh

---

CHANGELOG.md
sentry/src/main/java/io/sentry/SentryTracer.java

NPE caused by `timer` becoming `null` after acquiring the `synchronized` lock. Now we check again after acquiring the lock to ensure this doesn't happen.
Fixes #2196

Prevent NPE by checking SentryTracer.timer for null again inside synchronized

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java

Wrap `Activity` with `WeakReference` in `ActivityLifecycleIntegration` to not strongly hold on to it for the `TransactionFinishedCallback`.
Fixes #2201 
Emulator

Weakly reference Activity for transaction finished callback

---

sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/TransactionContext.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/main/java/io/sentry/protocol/TransactionInfo.java
sentry/src/main/java/io/sentry/protocol/TransactionNameSource.java
sentry/src/test/java/io/sentry/protocol/SentryTransactionSerializationTest.kt

To avoid serialization problems, e.g. when a cross platform SDK has sources the Java SDK doesn't know about.

Transaction source as String instead of enum

---

sentry-spring/api/sentry-spring.api
sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
sentry-spring/src/main/java/io/sentry/spring/tracing/SpringMvcTransactionNameProvider.java
sentry-spring/src/main/java/io/sentry/spring/tracing/TransactionNameProvider.java
sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/TransactionContext.java
sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
sentry/src/main/java/io/sentry/protocol/TransactionInfo.java
sentry/src/main/java/io/sentry/protocol/TransactionNameSource.java
sentry/src/test/java/io/sentry/protocol/SentryTransactionSerializationTest.kt

Add internal method to `TransactionNameProvider` so we can set the source. Defaults to `CUSTOM` but can be overriden by us.
So we can have the most accurate `source` possible. Not sure I like having the internal default method on the interface though. WDYT?

TransactionNameProvider source

---

sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/ProfilingActivity.kt
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/ProfilingListAdapter.kt
sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
sentry-samples/sentry-samples-android/src/main/res/layout/activity_profiling.xml
sentry-samples/sentry-samples-android/src/main/res/layout/profiling_item_list.xml
sentry-samples/sentry-samples-android/src/main/res/values/strings.xml

Few additions to the Android sample app:
- Added profiling activity with size printed on screen
- Enabled profiling
- auto user interaction instrumentation should be disabled when testing the manual profile (creates concurrent transactions not currently supported by profiling)
There was no clear way to answer the "How big is a profile?" question.
Now we can have a way to know, depending on length and number of working threads, how big is the profiling trace file, how big is the created envelope item, and how big is the actual data sent to Sentry (the item compressed with gzip).
Also, we can now feed different profiles by running the sample app and editing the dsn.
No way 😄

Add profiling activity to Android sample app

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ProfilingTraceData.java

Added cpu architecture in profiles envelope payload
Profiles environment defaults to "production"
- cpu architecture was requested to be added to the profiles data.
- We found that profiles didn't have any environment, even if the transaction had one set. I figured out it was set in the transaction in the `MainProcessor` in case it's null, so i added the same logic to the profiles, too.
I added assertions on these fields to the ui test that sends a profile envelope

added cpu architecture and default environment in profiles envelope

---

sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java

Guess changelog is not needed since the bug hasn't been released yet
Messed up a refactoring
Start timestamp was set after calling `startTransaction` so had no effect. This fixes it.

Fix start timestamp not set in ActivityLifecycleIntegration

---

CHANGELOG.md
sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpanRestTemplateCustomizerTest.kt
sentry-spring/src/main/java/io/sentry/spring/tracing/SentrySpanClientHttpRequestInterceptor.java

Add `baggage` header to outgoing `RestTemplate` calls.
To support Dynamic Sampling for outgoing requests using `RestTemplate`
See #2205
Unit Test

Add baggage header to RestTemplate

---

CHANGELOG.md
sentry/src/main/java/io/sentry/JsonObjectSerializer.java
sentry/src/main/java/io/sentry/JsonReflectionObjectSerializer.java
sentry/src/test/java/io/sentry/JsonObjectSerializerTest.kt
sentry/src/test/java/io/sentry/JsonReflectionObjectSerializerTest.kt

Use `toString()` for enum entries being serialized.
`JsonReflectionObjectSerializer` would consume lots of memory when serializing an enum entry where the enum has more than just a few entries.
Fixes #2219 
Unit Test

Use toString for enum serialization

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java

The `Hub` holds on to a `WeakHashMap` called `throwableToSpan` which maps root causes of exceptions to `Span`s. The memory leak was caused by the `Span` holding a strong reference to the `throwable` which contains the root cause that is also used as the key for the `WeakHashMap`. This means the value of the `WeakHashMap` was causing its own key not to be garbage collected and the memory was never freed.
The fix is to weakly hold on to the `Span` so it can be garbage collected and thus also the key can be garbage collected afterwards.
Fixes #2225 
Manual testing using debugger on a modified sample application, then using `visualvm` to trigger GC manually.

Fix memory leak caused by throwableToSpan

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/util/CollectionUtils.java

We want to support concurrent transactions. In order to do it, we are going to add the list of transactions occurred during a profile.
This pr adds the list of transactions occurred during a profile to the data sent in the envelope payload.
This is the second part of concurrent profiling support, after [this pr](https://github.com/getsentry/sentry-java/pull/2216) 
We want to avoid situations where the user cannot profile his transaction due to automatic transactions occurring at the same time, as pointed in [this issue](https://github.com/getsentry/sentry-java/issues/2209)
The strategy we will follow is described [here](https://www.notion.so/sentry/Profiling-concurrent-transactions-37da1625332e40799dc0e0bae90ced63)
Added unit test to check concurrent profiling logic
Added ui test to check …

Concurrent profiling 2 - added list of transactions

---

CHANGELOG.md
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/ProfilingActivity.kt
sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
sentry/src/test/java/io/sentry/SentryClientTest.kt

Added a check on the sampled profile not to be empty in order to be sent
We received few profiles without any content. There is already a check if the profiling trace file doesn't exists or cannot be read, but no check if it is empty. I couldn't be able to reproduce the issue, other than changing the content of the file right before being sent. 
However, this should fix it
I added both a Unit and a Ui test to check empty profiles are discarded

Avoid sending empty profiles

---

CHANGELOG.md
gradle.properties
sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java

This came up through Unity. In some cases, Unity projects resolve their own external dependencies via adding and including `arr` files. This seems to lead to issues during runtime when the AppLifecycleIntegration tries to add its observer and results in an `AbstractMethodError`.
To deal with the `AbstractMethodError` gracefully, we can catch the error instead and bail before we create the watcher.
```
2022/08/22 15:26:47.122 30530 30530 Error AndroidRuntime FATAL EXCEPTION: main
2022/08/22 15:26:47.122 30530 30530 Error AndroidRuntime Process: studio.banditos.banditos5, PID: 30530
2022/08/22 15:26:47.122 30530 30530 Error AndroidRuntime java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
2022/08/22 …
```

fix: AbstractMethodError when getting Lifecycle

---

sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ProfilingTransactionData.java

add cpu start/end timestamps to transactions in profile envelope payloads
added ui test to check times are different
Profiling traces have a clock field to indicate how timestamps were captured in the trace itself and it can be dual/cpu/wall/global time.
If the timestamps are cpu time, there's no way to filter the trace based on start/end timestamps, as the payload only sends wall time.
I added a ui test to check correctness of cpu timestamps

add cpu start/end timestamps to concurrent profiling transactions

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/ProfilingTraceData.java

We are adding the truncation reason in case a profile is truncated.
If no truncation occurs, we will send `normal`, while if a timeout occurs, we will send `timeout` as `truncation_reason` in the envelope payload.
The backend was unable to understand if a profile was terminated on purpose or due to an error.
Added a ui and unit test

Concurrent profiling 3 - truncation reason

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Baggage.java
sentry/src/main/java/io/sentry/protocol/User.java
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/protocol/UserSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/UserTest.kt
sentry/src/test/resources/json/sentry_base_event.json
sentry/src/test/resources/json/sentry_event.json
sentry/src/test/resources/json/sentry_transaction.json
sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
sentry/src/test/resources/json/sentry_transaction_no_measurement_unit.json
sentry/src/test/resources/json/user_legacy.json

`data` is now used instead of `other` on `User`. Can still parse `other` from JSON but will move it to `data`.
This way the custom properties will show up the same way in the UI as they do on other SDKs (e.g. JS).
Closes #2242

Replace user `other` with `data`

---

CHANGELOG.md
sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Baggage.java
sentry/src/main/java/io/sentry/protocol/User.java
sentry/src/test/java/io/sentry/ScopeTest.kt
sentry/src/test/java/io/sentry/protocol/UserSerializationTest.kt
sentry/src/test/java/io/sentry/protocol/UserTest.kt
sentry/src/test/resources/json/sentry_base_event.json
sentry/src/test/resources/json/sentry_event.json
sentry/src/test/resources/json/sentry_transaction.json
sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
sentry/src/test/resources/json/sentry_transaction_no_measurement_unit.json
sentry/src/test/resources/json/user_legacy.json

User segment is now a top level property.
Closes #2240

Make user segment a top level property

---

.github/workflows/add-platform-label.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/format-code.yml
.github/workflows/generate-javadocs.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/integration-tests-benchmarks.yml
.github/workflows/integration-tests-ui.yml

closes #1442
used: `pin-github-action --allow 'actions/*,getsentry/*' build.yml` (and other files) & manually reverted some formatting changes it's making (line breaks on long lines)...
There should be no need to do this again + new PRs will automatically get a failure through Danger.

chore: update & pin GHA dependencies

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityFramesTrackerTest.kt

Fixes the wrong reporting of frames by snapshotting slow and frozen frame values at the start and end, then calculating a delta.
Fixes #2264 
Sample App; Unit Tests
Once merged, release `6.4.3` then merge `6.4.x` into `main`.

Fix slow and frozen frames tracking

---

CHANGELOG.md
buildSrc/src/main/java/Config.kt
sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/boot/SecurityConfiguration.java
sentry-samples/sentry-samples-spring/src/main/java/io/sentry/samples/spring/SecurityConfiguration.java

Should also get rid of dependabot warnings regarding vulnerable dependencies.
Note: we marked the dependencies as provided so we don't actually drag in old versions.

Bump spring to 2.7.4

---

CHANGELOG.md
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Baggage.java
sentry/src/test/java/io/sentry/BaggageTest.kt

Remove `ILogger` param from public facing API when creating a `Baggage` object from header String(s).
Retrieving options / logger is only possible using methods marked as `@ApiStatus.Internal` so instead we skip the param and retrieve it inside using `HubAdapter.getInstance().getOptions().getLogger()`.

Improve public facing API for creating Baggage from header

---

CHANGELOG.md
sentry-android-core/api/sentry-android-core.api
sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java
sentry-android-core/src/test/java/io/sentry/android/core/ActivityFramesTrackerTest.kt

androidx.core.app.FrameMetricsAggregator is not thread safe, calling .remove() from a background thread may cause a
ConcurrentModificationException
Ensure calling .remove() is done on the UI thread.
SentryTracer uses a `Timer` and `TimerTask` to finish open Transactions on a background thread. Finishing a transaction also triggers the calculation of the frame metrics as well as unregistering the activity from metric collection (`FrameMetricsAggregator.remove(activity)`), FrameMetricsAggregator is not thread safe, causing sporadic `ConcurrentModificationException`s.
Ensured current tests are not breaking, otherwise it's hard to test a ConcurrentModificationException.

Fix ConcurrentModificationException due to FrameMetricsAggregator manipulation

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/TracesSampler.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/SentryTest.kt
sentry/src/test/java/io/sentry/TracesSamplerTest.kt

Try/Catches callback executions and add logging in case of errors.
If certain callbacks provided via the Sentry, Hub or SentryOptions crash during execution, it could crash the whole application. So let's catch 'em all 😄 
Related issues:
* https://github.com/getsentry/sentry-java/issues/2123
* https://github.com/getsentry/team-mobile/issues/21
Callbacks which were already handled:
* BeforeSendCallback
* BeforeBreadcrumbCallback
Callbacks:
* SentryOptions.TracesSamplerCallback
* SentryOptions.ProfilesSamplerCallback
* OptionsConfiguration.configure
* Hub.captureMessage
* Hub.captureException
* Hub.captureEvent
* Hub.withScope
* Hub.configureScope
Added tests where required
- [ x ] I reviewed the submitted code
- [ x ] I added tests to verify the changes
- [ x ] I updated the docs if needed …

fix(java): Ensure potential callback exceptions are caught #2123

---

CHANGELOG.md
sentry-android-core/src/test/java/io/sentry/android/core/SendCachedEnvelopeIntegrationTest.kt
sentry/src/main/java/io/sentry/instrumentation/file/SentryFileOutputStream.java
sentry/src/main/java/io/sentry/instrumentation/file/SentryFileWriter.java
sentry/src/test/java/io/sentry/instrumentation/file/SentryFileOutputStreamTest.kt
sentry/src/test/java/io/sentry/instrumentation/file/SentryFileWriterTest.kt

A very nasty bug 🙈 
Closes https://github.com/getsentry/sentry-android-gradle-plugin/issues/387
With a unit test case

Fix SentryFileWriter and SentryFileOutputStream append overwrites file contents

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/MockRelay.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/Hub.java
sentry/src/main/java/io/sentry/HubAdapter.java
sentry/src/main/java/io/sentry/IHub.java
sentry/src/main/java/io/sentry/ISentryClient.java
sentry/src/main/java/io/sentry/ITransactionProfiler.java
sentry/src/main/java/io/sentry/NoOpHub.java
sentry/src/main/java/io/sentry/NoOpSentryClient.java
sentry/src/main/java/io/sentry/NoOpTransactionProfiler.java
sentry/src/main/java/io/sentry/SentryClient.java
sentry/src/main/java/io/sentry/SentryEnvelope.java
sentry/src/main/java/io/sentry/SentryTracer.java
sentry/src/test/java/io/sentry/HubTest.kt
sentry/src/test/java/io/sentry/NoOpTransactionProfilerTest.kt
sentry/src/test/java/io/sentry/SentryClientTest.kt

The `AndroidTransactionProfiler` now directly sends profile envelopes. This means we don't have to pass the `ProfileTraceData` anymore anyway. 
So we could drop the old timed out profiles handling, as they are directly sent when they time out
This change allows profiles to be sent independently from transactions.
It also fixes and simplify timed out profiles handling. Previously we had to wait for a transaction to finish to attach the timed out profile to it and send the envelope. Now the envelope is sent as soon as the profile times out.
I added a ui test to check the profile is sent on timeout without finishing the transaction
I added few unit tests to check the `captureProfile` method of the hub is called by the profiler itself.

Profile envelopes sent directly from profiler

---

CHANGELOG.md
sentry/src/main/java/io/sentry/TransactionContext.java
sentry/src/test/java/io/sentry/TransactionContextTest.kt

When introducing `baggage` we ignored the `sampled` decision coming in via `sentry-trace`. This caused incoming `sampled=false` to not be honored.
Fixes #2308 
Unit Tests

Respect incoming parent sampled decision when continuing a trace

---

CHANGELOG.md
sentry-compose/api/android/sentry-compose.api
sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryNavigationIntegration.kt

Overload withSentryObservableEffect to provide compose instrumentation hook
In order to auto-instrument navigation in Jetpack Compose we simply want to adapt the original `rememberNavController` call with our sentry specific navigation listeners. This way the required bytecode changes can be kept to a minimum.
Related to [#2319](https://github.com/getsentry/sentry-java/issues/2319)
Right now just manually, need to investigate how all this Android specifics can be tested.

Overload withSentryObservableEffect to provide compose instrumentation hook

---

CHANGELOG.md
sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt

Use correct set-cookie for the HTTP Client response object
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

Use correct set-cookie for the HTTP Client response object

---

CHANGELOG.md
sentry/src/main/java/io/sentry/Scope.java
sentry/src/main/java/io/sentry/SynchronizedQueue.java
sentry/src/test/java/io/sentry/ScopeTest.kt

Ensure that the breadcrumbs are copied in a thread safe manner when cloning a Scope.
This fixes a top crash we saw in the Google Play SDK Console.  
Related issues
* #2323
* #2183
If you know any better way to test this please let me know! (The test reliably crashed for me until I implemented the fix).

Fix NoSuchElementException in CircularFifoQueue when cloning a Scope

---

.sauce/sentry-uitest-android-benchmark.yml
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/BaseUiTest.kt
sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
sentry-android-integration-tests/sentry-uitest-android/src/main/java/io/sentry/uitest/android/ProfilingSampleActivity.kt

Added window.setSustainedPerformanceMode(true) on benchmark activity, to get better results. 
Reduced espresso default timeout to 10 seconds
Updated list of devices for benchmarks
`setSustainedPerformanceMode` is one of the things the android benchmark runner (which we cannot use due to problems on Saucelabs) does. It tries to limit the thermal throttling by reducing the overall performance. https://developer.android.com/reference/kotlin/androidx/benchmark/junit4/AndroidBenchmarkRunner#clock-stability
This will result in more predictable benchmarks, as currently there are few runs failing.
Saucelabs devices for benchmarks were updated: the Google Pixel 3 was replaced because consistently timing out

Call setSustainedPerformanceMode for better benchmarks

---

CHANGELOG.md
sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
sentry-android-core/src/main/java/io/sentry/android/core/internal/modules/AssetsModulesLoader.java
sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
sentry-android-core/src/test/java/io/sentry/android/core/internal/modules/AssetsModulesLoaderTest.kt
sentry/api/sentry.api
sentry/src/main/java/io/sentry/MainEventProcessor.java
sentry/src/main/java/io/sentry/Sentry.java
sentry/src/main/java/io/sentry/SentryOptions.java
sentry/src/main/java/io/sentry/internal/modules/IModulesLoader.java
sentry/src/main/java/io/sentry/internal/modules/ModulesLoader.java
sentry/src/main/java/io/sentry/internal/modules/NoOpModulesLoader.java
sentry/src/main/java/io/sentry/internal/modules/ResourcesModulesLoader.java
sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
sentry/src/test/java/io/sentry/SentryTest.kt
sentry/src/test/java/io/sentry/internal/modules/ResourcesModulesLoaderTest.kt

* Adds platform-specific dependencies readers for Java and Android, that parse `sentry-external-modules.txt` file ingested by the gradle plugin into the final jar/apk
* Sends those dependencies as part of every SentryEvent
Closes #1470 
Relates to https://github.com/getsentry/sentry-android-gradle-plugin/pull/396
Part of https://github.com/getsentry/team-mobile/issues/54

Populate event.modules with dependencies metadata
