getsentry/sentry-java

- .github/workflows/gradle-wrapper-validation.yml
- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/Gpu.java
- sentry/src/test/java/io/sentry/protocol/GpuSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/GpuTest.kt
- sentry/src/test/resources/json/contexts.json
- sentry/src/test/resources/json/gpu.json
- sentry/src/test/resources/json/sentry_base_event.json
- sentry/src/test/resources/json/sentry_event.json
- sentry/src/test/resources/json/sentry_transaction.json
- sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
- sentry/src/test/resources/json/sentry_transaction_no_measurement_unit.json
`gpu.vendorId` was defined as an Int, should be a String.
This is a breaking change but I'm wondering if anyone is using it. We could introduce a `@Deprecated void setVendorId(int vendorId) { setVendorId(String.valueOf(vendorId)); }` to minimize the impact, but I'm not sure if it's worth it.
Mobile Issue: https://github.com/getsentry/team-mobile/issues/67
Dart: https://github.com/getsentry/sentry-dart/pull/1112
> VendorId should be a String

- .sauce/sentry-uitest-android-benchmark-lite.yml
- .sauce/sentry-uitest-android-benchmark.yml
- buildSrc/src/main/java/Config.kt
updated ui test dependencies for Android 13
updated benchmark device
Ui test dependencies have been updated to work better on Android 13 (ui interactions through espresso was not working)
A device on Saucelabs is giving an error for a "Don't keep activities" developer option, which we have no control over. So we are changing it with another device with similar spec (Google Pixel 2 -> Oneplus Nord N200)
> updated ui test dependencies and benchmark device

- CHANGELOG.md
- CONTRIBUTING.md
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
> fix: don't sent device name if DefaultPII is disabled

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SpanId.java
- sentry/src/main/java/io/sentry/protocol/SentryId.java
- sentry/src/main/java/io/sentry/util/StringUtils.java
- sentry/src/test/java/io/sentry/protocol/SentryIdTest.kt
- sentry/src/test/java/io/sentry/util/StringUtilsTest.kt
We tested it with Bruno and indeed it returns a corrupted UUID on his device, no matter which method is used to instantiate the UUID:
So this is just a band aid for those cases
Closes #2325
> Fix corrupted UUID on Motorola devices

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/ProfilingActivity.kt
Removed a useless file exist check in AndroidTransactionProfiler
Offloaded AndroidTransactionProfiler methods to background threads using executor service
When using Android Strict Mode, the file io that was happening in the main thread (file existence checks) were generating warnings, as in this [issue](https://github.com/getsentry/sentry-java/issues/2317)
Closes #2317
I updated the unit tests
> Remove profiler main thread io

- CHANGELOG.md
- sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java
- sentry/src/test/java/io/sentry/UncaughtExceptionHandlerIntegrationTest.kt
We were trying to flush the event to disk, even though the event was dropped and we never called `markFlushed`, hence it was blocking for 15seconds everytime the event is dropped 🙈 
Closes #2346
> Fix ANR on dropped uncaught exception events

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/main/java/io/sentry/android/core/cache/AndroidEnvelopeCache.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
Right now some integrations are created between default/auto-init and the custom `SentryOptions.configure` callback. If an integration copies references from `SentryOptions` it can hold a stale configuration, as the  `SentryOptions.configure` block can change any option afterwards.
This is a quick fix, I guess in the long run we should take a look into streamlining the overall SDK init process to avoid these kind of issues.
This PR splits up the `AndroidOptionsInitializer.init` method into two parts:
- `loadDefaultAndMetadataOptions()`
- `initializeIntegrationsAndProcessors()`
This allows us to execute execute the custom `OptionsConfiguration.configure()` callback in-between, which ensures all options are set before any integrations and processors are created.
Fixes …
> Fix ensure all options are processed before integrations are loaded

- CHANGELOG.md
- sentry-android-core/proguard-rules.pro
- sentry-android-fragment/proguard-rules.pro
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt
- sentry-android-fragment/src/test/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacksTest.kt
- sentry-android-timber/proguard-rules.pro
While using minified builds I noticed that timber and fragment integrations do not get autoinstalled. Turns out it's because we're checking for presence of upstream dependencies classes (e.g. `timber.log.Timber`), but the get obfuscated too indeed. So this PR will keep their names so we can successfully check them. Along the way fixed another 2 issues:
* Use canonicalName instead of simpleName in Fragment Integration for better de-obfuscation
* Keep `io.sentry` package name to filter ouе our frames from stacktraces when sending the crashes. This adds ~5kb for the final apk size, but I guess this is not a big price.
Closes #2362
> Fix R8 config

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-samples/sentry-samples-spring-boot-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-jakarta/build.gradle.kts
- sentry-spring-boot-starter-jakarta/build.gradle.kts
- sentry-spring-jakarta/build.gradle.kts
- settings.gradle.kts
Spring Boot v3 has been released a few hours ago. This PR updates the repo to the proper release version and removes the milestone repositories.
with `make compile`
> Bump Spring Boot Jakarta to 3.0.0 release

- CHANGELOG.md
- sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
- sentry-samples/sentry-samples-servlet/src/main/java/io/sentry/samples/servlet/SentryInitializer.java
- sentry-spring-boot-starter-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot-starter-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryInitBeanPostProcessor.java
- sentry-spring/src/main/java/io/sentry/spring/SentryInitBeanPostProcessor.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/SentryClientTest.kt
Similar to `beforeSend` for errors `beforeSendTransaction` allows users to change and filter transactions.
Closes #2358 
Unit tests, ran sample
> Add beforeSendTransaction which allows users to filter and change transactions

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-agent/README.md
- sentry-opentelemetry/sentry-opentelemetry-agentcustomization/src/main/java/io/sentry/opentelemetry/SentryAutoConfigurationCustomizerProvider.java
Restore default exporter configuration for Sentry OpenTelemetry Java Agent.
To not confuse users who could use the Sentry Java Agent as drop in replacement for the original OpenTelemetry Java Agent we want to keep the default exporter settings and document how to get rid of ERROR messages in the logs.
Manually
> No longer disable OpenTelemetry exporters in default Java Agent config

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-agentcustomization/src/main/java/io/sentry/opentelemetry/SentryAutoConfigurationCustomizerProvider.java
- sentry-opentelemetry/sentry-opentelemetry-core/api/sentry-opentelemetry-core.api
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OpenTelemetryLinkErrorEventProcessor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentryPropagator.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanProcessor.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentrySpanStorage.java
Retrieve current `Span` from OpenTelemetry, then look up the Sentry span via `spanId` and add `traceId`, `spanId`, `parentSpanId` and `op` to the error events context keyed `"trace"`.
Had to move `SentrySpanStorage` from `sentry-opentelemetry-core` module to `sentry` module to avoid yet another module just for providing `SentrySpanStorage` in the bootstrap classloader.
With this change, Sentry UI can now show a link from transaction to error event and vice versa.
Manually via Spring Boot Sample
> Add OpenTelemetryLinkErrorEventProcessor for linking errors to traces created via OpenTelemetry

- .sauce/sentry-uitest-android-benchmark-lite.yml
- .sauce/sentry-uitest-android-benchmark.yml
- .sauce/sentry-uitest-android-ui.yml
- buildSrc/src/main/java/Config.kt
- sentry-android-integration-tests/sentry-uitest-android-benchmark/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/RelayAsserter.kt
- sentry-test-support/src/main/kotlin/io/sentry/Assertions.kt
ui tests now search the envelope among all the ones sent to the mock relay server and make assertion on them, instead of relying on the order the envelopes were created
added androidx test orchestrator to saucelabs configuration with "clearPackageData" option enabled 
updated androidx orchestrator dependency
renamed transactions in tests to be more useful
The ui tests were flaky, as sometimes (rarely) the envelopes were not sent in the creation order, causing https://github.com/getsentry/sentry-java/issues/2396
- [] I added tests to verify the changes
- [] I updated the docs if needed
> Fix Android ui flaky tests checking order of envelopes

- sentry-compose/build.gradle.kts
This will produce artifacts for `sentry-compose`, `sentry-compose-android`, `sentry-compose-desktop`
> Revert sourcesets config to produce same modules as before

- scripts/update-gradle.sh
Should fix https://github.com/getsentry/sentry-java/actions/runs/3730123923/jobs/6326807766
> ci: specify explicit java version in update-gradle.sh

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidMemoryCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidMemoryCollectorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/IMemoryCollector.java
- sentry/src/main/java/io/sentry/JavaMemoryCollector.java
- sentry/src/main/java/io/sentry/MemoryCollectionData.java
- sentry/src/main/java/io/sentry/NoOpMemoryCollector.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/JavaMemoryCollectorTest.kt
- sentry/src/test/java/io/sentry/NoOpMemoryCollectorTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/TransactionPerformanceCollectorTest.kt
Added a MemoryCollector, with different implementations for Java and Android, set in SentryOptions
Added TransactionPerformanceCollector, that uses the MemoryCollector, to collect performance data while a transaction is running.
Collected data is a list of objects containing a timestamp, java heap memory usage and native memory usage (only on Android)
We want to build a POC to get the memory usage data as a time series while a transaction runs.
Unit tests
> Collect memory usage in transactions

- CHANGELOG.md
- sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberIntegration.kt
- sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberIntegrationTest.kt
We should not override the sdk version/name, because Timber is just an integration as opposed to other "sdk-like" things, like spring-boot or log4j. We can still query the `packages` and see who's using timber (and soon, `integrations`). 
This way we avoid the weird `sentry.java.android.timber` name in the SDK description (should be `sentry.java.android`)
Closes #1893
> Don't override sdk version with timber

- CHANGELOG.md
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/tracing/SentryTracingFilter.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/tracing/SentryTracingFilterTest.kt
- sentry-spring/src/main/java/io/sentry/spring/tracing/SentryTracingFilter.java
- sentry-spring/src/test/kotlin/io/sentry/spring/tracing/SentryTracingFilterTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
`traceOptionsRequests` defaults to `true` for now. I think we should change this to `false` only in the next major release.
Allows us to fix https://github.com/getsentry/sentry-java/issues/2231 in the next major by flipping the default to `false`.
Unit Tests, manually
> Add `traceOptionsRequests` option to disable tracing of OPTIONS requests

- CHANGELOG.md
- sentry-servlet-jakarta/src/main/java/io/sentry/servlet/jakarta/SentryRequestHttpServletRequestProcessor.java
- sentry-servlet/src/main/java/io/sentry/servlet/SentryRequestHttpServletRequestProcessor.java
- sentry/src/main/java/io/sentry/util/HttpUtils.java
Use `HttpUtils` where it wasn't before and add more headers that are considered sensitive.
Fixes #2454
> Extend list of HTTP headers considered sensitive

- CHANGELOG.md
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/TransactionPerformanceCollectorTest.kt
Timer was created even if performance wasn't enabled. Also Timer prevented shutdown.
Fixes #2477 
- @stefanosiano can you please help test if this still works correctly
> Create timer in `TransactionPerformanceCollector` lazily

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/EmptySecureContentProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/ContentProviderSecurityChecker.java
The changes contained in https://github.com/getsentry/sentry-java/pull/2466 that were merged and released in [6.12.0](https://github.com/getsentry/sentry-java/releases/tag/6.12.0) were not enough to pass [Data/Secure theorem](https://www.securetheorem.com/) security scans.
This is either due to...
- The security scans expecting exact copy-paste of their suggested code 
- OR it expects the security checks to also be applied to `insert`, `update`, and `delete` ContentProvider functions
- The security check was, and is currently, only applied to the `query` function.
In order to completely fix the **potential** security vulnerability described in https://github.com/getsentry/sentry-java/issues/2460, we should also apply the security checks to the `insert`, `update`, and `delete` functions of …
> Expand fix for potential Privilege Escalation via Content Provider (CVE-2018-9492)

- CHANGELOG.md
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DefaultTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/NoOpTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/TransactionPerformanceCollectorTest.kt
Extracted `TransactionPerformanceCollector` interface and renamed previous `TransactionPerformanceCollector` to `DefaultTransactionPerformanceCollector`. Use `NoOpTransactionPerformanceCollector` as default in `SentryOptions`
Quick fix for #2496 disabling `TransactionPerformanceCollector` by replacing it with a `NoOp` variant.
- run spring boot sample
- `wrk -t2 -c100 -d30s http://user:password@localhost:8080/person/9`
- visualvm heapdump analysis
- figure out why `performanceDataMap` isn't cleaned up and keeps growing, then re-enable `DefaultTransactionPerformanceCollector`
> Prevent OOM by disabling TransactionPerformanceCollector for now

- CHANGELOG.md
- sentry/src/main/java/io/sentry/DefaultTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/TransactionPerformanceCollectorTest.kt
DefaultTransactionPerformanceCollector was calling setup() on main thread, and we moved it to a background thread.
Since one of the collectors reads files during setup(), calling it in the main thread would make Android complain if strict mode is applied.
Unit test
> Fix performance collector setup called in main thread

- CHANGELOG.md
- sentry-bom/build.gradle.kts
sentry-bom was containing [wrong artifacts](https://repo.maven.apache.org/maven2/io/sentry/sentry-bom/6.13.0/sentry-bom-6.13.0.pom) (e.g. test dependencies, test apps, missing compose artifacts, etc.). This PR fixes it.
Closes https://github.com/getsentry/sentry-java/discussions/2503
Manually `./gradlew publishToMavenLocal`. The result can be checked here 
[sentry-bom-6.13.0.txt](https://github.com/getsentry/sentry-java/files/10544041/sentry-bom-6.13.0.txt)
> Fix Sentry BOM containing wrong artifacts

- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ViewHierarchyEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/ViewHierarchyEventProcessorTest.kt
Even more simple interface for hybrid SDKs.
https://github.com/getsentry/sentry-react-native/pull/2708#discussion_r1092127981
integration tests
> chore(internal): Add snapshot view hierarchy as byte array

- sentry-android-core/src/main/java/io/sentry/android/core/ViewHierarchyEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/ViewHierarchyEventProcessorTest.kt
The view hierarchy the same way as screenshots would appear twice if not checked for hybrid sdks.
- https://github.com/getsentry/sentry-react-native/pull/2708
unit tests
> fix(internal): Do not attach view hierarchy to hybrid sdks events

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidCpuCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidMemoryCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidCpuCollectorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidMemoryCollectorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DefaultTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/ICollector.java
- sentry/src/main/java/io/sentry/ITransactionProfiler.java
- sentry/src/main/java/io/sentry/JavaMemoryCollector.java
- sentry/src/main/java/io/sentry/NoOpTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/NoOpTransactionProfiler.java
- sentry/src/main/java/io/sentry/PerformanceCollectionData.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/DefaultTransactionPerformanceCollectorTest.kt
- sentry/src/test/java/io/sentry/JavaMemoryCollectorTest.kt
- sentry/src/test/java/io/sentry/PerformanceCollectionDataTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
PerformanceCollectionData now contains single values instead of lists
ICollectors now work on a single instance of PerformanceCollectionData instead than a list
TransactionPerformanceCollector:
* is now set in Android options
* a NoOpTransactionPerformanceCollector is set in Java options
* deletes data after 30 seconds
* collect data only if a profile is sampled
We collect data about cpu and memory usage during transactions. This caused [oom error in java backend](https://github.com/getsentry/sentry-java/issues/2496).  
As a workaround, the data collection [was disabled](https://github.com/getsentry/sentry-java/pull/2498).   
We are now enabling the data collection only on the Android SDK, and only if a profile is sampled, since we send this data only in profiles, at the moment.
Several …
> Fix transaction performance collector oom

- CHANGELOG.md
- sentry/src/main/java/io/sentry/ShutdownHookIntegration.java
- sentry/src/test/java/io/sentry/ShutdownHookIntegrationTest.kt
Ignore "Shutdown in progress" `IllegalStateException` when removing the shutdown hook. This was also present in older versions of the SDK (https://github.com/getsentry/sentry-java/pull/550/files).
Came up again recently in #2465 and also happened in tests before #1574 and #1663
Unit Test
- [x I added tests to verify the changes.
- [-] I updated the docs if needed.
- [-] Review from the native team if needed.
> Ignore Shutdown in progress when closing ShutdownHookIntegration

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppStartState.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
This way the appstart start/end times are properly tracked, even if the
SDK is not initialized yet. In case of a deferred SDK init, the app
start span will be attached to the first tracked Activity after SDK
init.
Fixes https://github.com/getsentry/sentry-java/issues/2518
Unit tests
> Fix app start span end-time is wrong if SDK init is deferred

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
- sentry-spring-boot-starter-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot-starter-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/TracesSampler.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTracingTest.kt
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
Adds a new `enableTracing` option. If set to true, performance is enabled, even if no `tracesSampleRate` or `tracesSampler` have been configured. For now we set a default `tracesSampleRate` of `1.0` if none has been configured explicitly. If `enableTracing` is set to `false` performance is disabled, regardless of `tracesSampleRate` and `tracesSampler` options. The default for `enableTracing` is `null` meaning existing behaviour remains unchanged (setting either `tracesSampleRate` or `tracesSampler` enables performance)
Closes #2522
Unit tests, manually using Android and Spring Boot (Jakarta)
- [-] Review from the native team if needed.
- [?] No breaking change for hybrid SDKs or communicated to hybrid SDKs.
- 	Shouldn't break anything, existing behaviour should still work
> Add `enableTracing` option

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/config/ClasspathPropertiesLoader.java
- sentry/src/main/java/io/sentry/internal/modules/CompositeModulesLoader.java
- sentry/src/main/java/io/sentry/internal/modules/ManifestModulesLoader.java
- sentry/src/main/java/io/sentry/internal/modules/ResourcesModulesLoader.java
- sentry/src/main/java/io/sentry/util/ClassLoaderUtils.java
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/internal/modules/CompositeModulesLoaderTest.kt
- sentry/src/test/java/io/sentry/internal/modules/ManifestModulesLoaderTest.kt
This allows us to collect dependencies at runtime by looking at all available `MANIFEST.MF` resources and extracting the dependency name and version from the URL. This does not actually look at the contents of the manifest files but only at the URLs which usually takes a low single digit amount of `ms` to collect all dependencies.
Allows us to show `modules` in UI for JVM applications that aren't using our plugin to provide `sentry-external-modules.txt`. A workaround for #2474 until we can provide a non Android focused build plugin that users can use.
Running Spring Boot from IDE, from runnable JAR and WAR deployed to Tomcat. Unit Tests
- [-] Review from the native team if needed.
> Detect dependencies by listing MANIFEST.MF files at runtime

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
- sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt
If a stack frame neither matches any `inAppIncludes` nor `inAppExcludes`, we now treat it as undecided by setting `null` and leaving the decision to the backend / ingestion.
As discussed internally SDKs should only set `true` / `false` if they're certain.
Unit Tests
- [-] Review from the native team if needed.
> Leave inApp flag for stack frames undecided in SDK if unsure and let ingestion decide instead

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ISpan.java
- sentry/src/main/java/io/sentry/NoOpSpan.java
- sentry/src/main/java/io/sentry/NoOpTransaction.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/test/java/io/sentry/NoOpSpanTest.kt
- sentry/src/test/java/io/sentry/NoOpTransactionTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/SpanTest.kt
`time-to-full-display` end timestamp is now adjusted to the `time-to-initial-display` end timestamp if called too early
added updateEndDate method to ISpan
If the user calls the manual API `Sentry.reportFullDisplayed` too early, we would show the `time-to-full-display` span to be shorter than our automatically calculated `time-to-initial-display`, which would be pretty confusing.
This adjustment is done also by the [Android system](https://developer.android.com/reference/android/app/Activity#reportFullyDrawn()): `If this method is called before the activity's window is first drawn and displayed as measured by the system, the reported time here will be shifted to the system measured time.`
It's also done by the Firebase SDK.
Unit tests
> Adjust time-to-full-display span if reportFullDisplayed is called too early

- build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/README.md
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/Person.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/PersonController.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/PersonService.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/SentryDemoApplication.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/resources/application.properties
- settings.gradle.kts
Adds a new sample for Spring Boot 3 using WebFlux
To showcase new features only available for newer versions of Spring Boot.
manually started it and hit it with requests
- [-] I added tests to verify the changes.
> Add sample for Spring Boot 3 / Jakarta WebFlux

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/util/SampleRateUtils.java
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/util/SampleRateUtilTest.kt
Allow 0.0 sample rate to be set (though the effect would be as setting sample rate to null).
To align with other SDKs (RN, Cocoa, Flutter)
Automated tests
> Make 0 sample rate a valid rate

- CHANGELOG.md
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilter.java
Pass hub from `WebFilter` to `SentryWebExceptionHandler` via `ServerWebExchange` `attributes`.
We just used whatever hub is there which could possibly bleed into other requests.
Manually with debugger
> Use the same hub in WebFlux exception handler as we do in WebFilter

- CHANGELOG.md
- sentry-spring-jakarta/build.gradle.kts
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/ReactorUtils.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilter.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilterWithThreadLocalAccessor.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/ReactorUtilsTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
(modified changelog entry for this chain of PRs instead of having a separate one)
Clone hub from main hub for every WebFlux request
If we just use whatever hub is there on the thread, we could leak between requests.
manually using debugger
> Clone hub from main hub for every WebFlux request

- CHANGELOG.md
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/TodoController.java
- sentry-spring-jakarta/build.gradle.kts
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/ReactorUtils.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilter.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilterWithThreadLocalAccessor.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/ReactorUtilsTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
Use `ThreadLocalAccessor` for WebClient in Spring Boot 3 sample
To showcase how it can be used.
> Use `ThreadLocalAccessor` for WebClient in Spring Boot 3 sample

- CHANGELOG.md
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/TodoController.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/Person.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/PersonController.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/PersonService.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/SentryDemoApplication.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/Todo.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/TodoController.java
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/resources/application.properties
- sentry-spring-jakarta/build.gradle.kts
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/ReactorUtils.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilter.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilterWithThreadLocalAccessor.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/ReactorUtilsTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
Use `ThreadLocalAccessor` in Spring Boot 3 WebFlux sample
To showcase how
> Use `ThreadLocalAccessor` in Spring Boot 3 WebFlux sample

- CHANGELOG.md
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/java/io/sentry/samples/spring/boot/SentryDemoApplication.java
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/java/io/sentry/samples/spring/boot/Todo.java
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/java/io/sentry/samples/spring/boot/TodoController.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/AbstractSentryWebFilter.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilter.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebFilterWithThreadLocalAccessor.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebFilter.java
Use a new hub cloned from main hub for WebFlux requests instead of cloning the current one on the thread. This allows the hub, used for the request, to be garbage collected eventually. Previously we were using the current hub on the thread to call `.pushScope()`, then cloned that hub including the stack and the call to `.popScope()` would go to the clone instead of the hub we called `.pushScope()` on. This means we were popping the copied stack of the cloned hub leaving the stack of the original hub untouched. This lead to an ever growing stack on the original hub, causing a memory leak and also scope bleed because the original hub survives across requests and is never cleaned up.
Improves #2557 but still holds on to one hub per thread + stack and scope etc.
I have some ideas for further …
> Fix memory leak in Webflux related to an ever growing stack

- CHANGELOG.md
- sentry-compose/build.gradle.kts
- sentry-compose/proguard-rules.pro
- sentry/src/main/java/io/sentry/SentryOptions.java
Since our Gradle Plugin is modifying the `.pom` of the dependencies to auto-install integrations, sentry-compose itself was depending on `androidx.compose:runtime`, therefore after auto-installing it was creating a circular dependency. This PR fixes that, so the users will have to have compose/compose-navigation on their classpath for our integration to kick in.
It's also fine if they don't have them on the classpath, because our Navigation instrumentation will not be called/installed if there's no `NavHostController` on the classpath.
Similar to https://github.com/getsentry/sentry-java/pull/2175
Closes #2364 
2 more PRs:
* https://github.com/getsentry/sentry-android-gradle-plugin/pull/442
* https://github.com/getsentry/sentry-docs/pull/6390
> Switch to compileOnly dependencies in sentry-compose

- CHANGELOG.md
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryExceptionResolver.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentryExceptionResolverTest.kt
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentryExceptionResolverTest.kt
Refactor `SentryExceptionResolver` to improve its API: extract Sentry event and hint creation from `resolveException` method into protected methods to allow easier and more flexible override of any of these pieces by the consumers of the Spring integration module.
A very common scenario for the apps I work on is to return the Sentry ID in the `ModelAndView` back to the client who faced a problem so that they could then reach out to me providing that ID which makes it significantly quicker and easier to locate the relevant report and hence trace down the root cause.
The existing implementation of `SentryExceptionResolver` didn't care about the Sentry ID returned from `IHub.captureEvent(event, hint)` and didn't provide a simple way to override this behavior. This change allows a subclass to …
> Improve versatility of exception resolver component for Spring with more flexible API for consumers.

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/PermissionsActivity.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/ProfilingActivity.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/SecondActivity.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/FullyDisplayedReporter.java
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/FullyDisplayedReporterTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/NoOpHubTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
Rename all occurrences of FullDisplayed with FullyDisplayed
Deprecated old Sentry.reportFullDisplayed() method
reportFullDisplayed is not correct english
It fixes https://github.com/getsentry/sentry-java/issues/2575
Unit tests
> Renamed reportFullDisplayed to reportFullyDisplayed

- CHANGELOG.md
- sentry-android-core/proguard-rules.pro
Add proguard rules to keep Classnames for integrations
Fixes #2592
> Keep integration names from being obfuscated

- CHANGELOG.md
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryRequestResolver.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryRequestResolver.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentrySpringFilterTest.kt
- sentry-spring/src/main/java/io/sentry/spring/SentryRequestResolver.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryRequestResolver.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringFilterTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/util/HttpUtils.java
- sentry/src/main/java/io/sentry/util/UrlUtils.java
- sentry/src/test/java/io/sentry/util/HttpUtilsTest.kt
Replace values of certain cookies that could allow impersonation with `[Filtered]` and do not send the value to Sentry.
Fixes #2562 
Unit Tests, manually using samples
> Filter out session cookies sent by Spring and Spring Boot integrations

- CHANGELOG.md
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot-webflux/src/main/resources/application.properties
- sentry-spring-boot-starter-jakarta/api/sentry-spring-boot-starter-jakarta.api
- sentry-spring-boot-starter-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryWebfluxAutoConfiguration.java
- sentry-spring-boot-starter/api/sentry-spring-boot-starter.api
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryWebfluxAutoConfiguration.java
- sentry-spring-jakarta/api/sentry-spring-jakarta.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebTracingFilter.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/SentryWebFluxTracingFilterTest.kt
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/SentryWebfluxIntegrationTest.kt
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebFilter.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebTracingFilter.java
- sentry-spring/src/test/kotlin/io/sentry/spring/webflux/SentryWebFluxTracingFilterTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/webflux/SentryWebfluxIntegrationTest.kt
This adds automatic performance instrumentation for WebFlux
Closes #1807 
Manually using samples + automated tests
> Automatic performance instrumentation for WebFlux

- CHANGELOG.md
- sentry-jul/api/sentry-jul.api
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
- sentry-log4j2/api/sentry-log4j2.api
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
- sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
- sentry-logback/api/sentry-logback.api
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/PersonController.java
- sentry-spring-jakarta/api/sentry-spring-jakarta.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryExceptionResolver.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentryExceptionResolverTest.kt
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/SentryWebfluxIntegrationTest.kt
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebExceptionHandler.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentryExceptionResolverTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/webflux/SentryWebfluxIntegrationTest.kt
When capturing an exception via any of our logging integrations (logback, log4j2, jul) we now add the mechanism and set the mechanism type.
Fixes #2555
Unit tests, manually
> Add mechanism for logging integrations and update spring mechanism types

- CHANGELOG.md
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
Changed INFO level logging to WARN when failing to initialise
Normally log4j appenders are configured to show only warnings, and is also the example on the official page
https://docs.sentry.io/platforms/java/guides/log4j2/.
With that, if Sentry fails to initialise due to e.g missing DSN, the user has no useful feedback.
I didn't find necessary to add a test for the logging
> Change log level from INFO to WARN for error message indicating a failed Log4j2 Sentry.init

- CHANGELOG.md
- sentry-apollo-3/src/main/java/io/sentry/apollo3/SentryApollo3HttpInterceptor.kt
- sentry-apollo-3/src/test/java/io/sentry/apollo3/SentryApollo3InterceptorTest.kt
- sentry-apollo-3/src/test/java/io/sentry/apollo3/SentryApollo3InterceptorWithVariablesTest.kt
- sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt
- sentry-apollo/src/test/java/io/sentry/apollo/SentryApolloInterceptorTest.kt
- sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java
- sentry-graphql/src/test/kotlin/io/sentry/graphql/SentryInstrumentationTest.kt
Adapt Span op and description for graphql integrations to fit spec
Fixes #2261
> Adapt span op and description for graphql

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
Reads integration list from manifest
Reads information provided by https://github.com/getsentry/sentry-android-gradle-plugin/pull/441
Enhances #2179
> Read integration list written by sentry gradle plugin from manifest

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityFramesTrackerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ISpan.java
- sentry/src/main/java/io/sentry/NoOpSpan.java
- sentry/src/main/java/io/sentry/NoOpTransaction.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/main/java/io/sentry/protocol/MeasurementValue.java
- sentry/src/test/java/io/sentry/NoOpSpanTest.kt
- sentry/src/test/java/io/sentry/NoOpTransactionTest.kt
Added ttid and ttfd as measurements
Added getStartDate() to ISpan
Fixed ActivityLifecycleIntegration tests
Currently we track time-to-initial-display and time-to-full-display as spans on automatic activity transactions.
Now we add them as measurements, too.
More info [here](https://github.com/getsentry/sentry-java/issues/2587).
Unit tests
> Add time-to-initial-display and time-to-full-display measurements to Activity transactions

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/test/java/io/sentry/SpanTest.kt
Automatic Activity transactions now have the ttid start timestamp if appStart span is not present
Span now trims for all transaction children if it's the root span of the transaction
The reported duration of the transaction [is wrong](https://github.com/getsentry/sentry-java/issues/2615).
Added Unit tests
> Fix Automatic UI transactions having wrong durations

- README.md
Before bumping the Sentry SDK of my Android app, I had a hard time figuring out if the SDK version was compatible with the hosted Sentry version I was going to use.
After digging through release notes, I stumbled on [this note](https://github.com/getsentry/sentry-java/releases/tag/6.0.0):
> Starting with version `6.0.0` of the `sentry` package, [Sentry's self hosted version >= v21.9.0](https://github.com/getsentry/self-hosted/releases) is required or you have to manually disable sending client reports via the `sendClientReports` option. This only applies to self-hosted Sentry.
I assume this is information that should belong to the main README, shouldn't it?
I proofread the MD 😉
This PR only contains what I actually found reading release notes but I can't be sure I …
> Add 6.0.0 requirements for hosted Sentry

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/test/java/io/sentry/BaggageTest.kt
When converting `Baggage` to `TraceContext` also keep unknown keys prefixed with `sentry-` and send them to Sentry via `SentryEnvelopeHeader`.
So we don't have to add every new key explicitly and instead simply pass through all unknown keys.
Unit Tests, manually using Sample
> Pass through unknown sentry baggage keys into SentryEnvelopeHeader

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/SentryLogcatAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryLogcatAdapterTest.kt
Implements a `SentryLogcatAdapter` that will replace `Log` calls via bytecode manipulation in the Sentry AGP.
Ref: #1620 
This adapter is needed by the AGP. See: https://github.com/getsentry/sentry-android-gradle-plugin/pull/455
- Manual testing
- Jadx
> feat: logcat integration

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/CpuInfoUtils.java
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/Device.java
- sentry/src/test/java/io/sentry/protocol/DeviceSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/DeviceTest.kt
- sentry/src/test/resources/json/contexts.json
- sentry/src/test/resources/json/device.json
- sentry/src/test/resources/json/sentry_base_event.json
- sentry/src/test/resources/json/sentry_event.json
- sentry/src/test/resources/json/sentry_transaction.json
- sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
Adds CPU description, processor count and frequency to the device context.
Implements required changes for https://github.com/getsentry/sentry-java/issues/2561
> Provide CPU count/frequency data as device context

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AppLifecycleIntegrationTest.kt
If `Sentry.close` is called off the main thread, the lifecycle watcher field is set to `null`, while de-registering is posted on the main thread, leading to a NPE in combination with some versions of android x lifecycle lib.
Fixes https://github.com/getsentry/sentry-java/issues/2601
Manual testing, the overhead of running a single test against different version of the androidx lifecycle library didn't seem to justify the efforts.
> Fix missing null check when removing lifecycle observer

- CHANGELOG.md
#skip-ci
Some git submodule refs for `sentry-native` where incorrectly pushed. The newest release will bump `0.6.0` to `0.6.1`
> Fix sentry-native changelog message

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ISpan.java
- sentry/src/main/java/io/sentry/NoOpSpan.java
- sentry/src/main/java/io/sentry/NoOpTransaction.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/test/java/io/sentry/NoOpSpanTest.kt
- sentry/src/test/java/io/sentry/NoOpTransactionTest.kt
ttfd span is trimmed if `reportFullyDisplayed` API is never called
exposed `getFinishDate` internally in ISpan
Currently if the user enables the option to track the fullDisplay, the transaction keeps running and if the manual API is never called, the `time-to-full-display` span would always last 30 seconds, increasing the transaction duration.
This change aims to mitigate this issue, so that if no other spans are present, the total transaction duration would be until the `time-to-initial-display` span is finished.
Unit test
> Trim time-to-full-display span if reportFullyDisplayed API is never called

- CHANGELOG.md
- sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryComposeTracing.kt
Our `SentryTraced` wrapper is using a `Box` right now to capture composition time. We should set the `propagateMinConstraints = true` flag to ensure `SentryTraced` is not modifying any layouting behavior.
As commented here: https://github.com/getsentry/sentry-java/commit/1d79c717cd52a26258ad3ff61df044c9ce6f03a9#r105548701
Manual
> Fix missing propagateMinConstraints flag for SentryTraced

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/profilemeasurements/ProfileMeasurementValue.java
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
PerformanceCollectionData timestamps in profiles have been adjusted to be relative to the profile start
PerformanceCollectionData timestamps were absolute values, but they were supposed to be relative to the profile start
Added a Ui test
> Fix timestamps of PerformanceCollectionData in profiles

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-log4j2/build.gradle.kts
- sentry-samples/sentry-samples-log4j2/src/main/resources/log4j2.xml
Bump log4j2 version to 2.20.0
Use AnnotationProcessor instead of package scanning to find Plugin.
Fixes #2616
> Make log4j2 integration compatible with log4j 3.0

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
fixed timestamps of PerformanceCollectionData in profiles
updated ui test to cover all measurements cases
The PerformanceCollectionData measurements in the profiles were not converted to nanoseconds, generating problems with their intervals
Updated ui test
> Fix timestamp intervals of PerformanceCollectionData in profiles

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/ConnectivityChecker.java
- sentry-android-core/src/test/java/io/sentry/android/core/ConnectivityCheckerTest.kt
Retrieving Network info via ConnectivityManager seems to cause crashes on Android 11. See https://issuetracker.google.com/issues/175055271 for more details.
Fixes https://github.com/getsentry/sentry-java/issues/2646
Added new unit tests
> Fix potential SecurityException thrown by ConnectivityManager on Android 11

- build.gradle.kts
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2Integration.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/threaddump/Line.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/threaddump/Lines.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/threaddump/ThreadDumpParser.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2IntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/internal/threaddump/ThreadDumpParserTest.kt
- sentry-android-core/src/test/resources/thread_dump.txt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/JsonSerializer.java
- sentry/src/main/java/io/sentry/MainEventProcessor.java
- sentry/src/main/java/io/sentry/SentryExceptionFactory.java
- sentry/src/main/java/io/sentry/SentryLockReason.java
- sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
- sentry/src/main/java/io/sentry/instrumentation/file/FileIOSpanManager.java
- sentry/src/main/java/io/sentry/protocol/SentryStackFrame.java
- sentry/src/main/java/io/sentry/protocol/SentryThread.java
- sentry/src/test/java/io/sentry/JsonUnknownSerializationTest.kt
- sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt
- sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt
- sentry/src/test/java/io/sentry/SentryThreadFactoryTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryLockReasonSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryStackFrameSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryThreadSerializationTest.kt
- sentry/src/test/resources/json/sentry_event.json
- sentry/src/test/resources/json/sentry_lock_reason.json
- sentry/src/test/resources/json/sentry_stack_frame.json
- sentry/src/test/resources/json/sentry_thread.json
* Parses a thread dump that we can get from AppExitInfo via `getTraceInputStream()`. Most of the parsing has been adapted from AOSP (with license header!), and each thread is transformed directly to `SentryThread`.
* The exception for the ANR is backfilled by the stacktrace of the main thread from the thread dump
* Adds `SentryLockReason` which we can infer from the thread dump and which can tell us if a thread is blocked on a lock by another thread. A `SentryThread` can have a dictionary/map of held locks.
Part of #1796 
* Merge it and ship it all
* Do frontend changes accordingly
> Parse ANRv2 thread dump into threads interface

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
Added map of ttfd spans in ActivityLifecycleIntegration, to automatically stop only the correct one.
Due to Activity lifecycle, during a navigation between two activities, when the previous activity was destroyed the `ActivityLifecycleIntegration` was terminating the ttfd span of the new activity.
Unit test
> Track a ttfd span per Activity

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/SendCachedEnvelopeIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DefaultTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/ISentryExecutorService.java
- sentry/src/main/java/io/sentry/ITransactionProfiler.java
- sentry/src/main/java/io/sentry/NoOpSentryExecutorService.java
- sentry/src/main/java/io/sentry/NoOpTransactionPerformanceCollector.java
- sentry/src/main/java/io/sentry/NoOpTransactionProfiler.java
- sentry/src/main/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegration.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryExecutorService.java
- sentry/src/main/java/io/sentry/TransactionPerformanceCollector.java
- sentry/src/test/java/io/sentry/DefaultTransactionPerformanceCollectorTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/NoOpSentryExecutorServiceTest.kt
- sentry/src/test/java/io/sentry/NoOpTransactionProfilerTest.kt
- sentry/src/test/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegrationTest.kt
- sentry/src/test/java/io/sentry/SentryExecutorServiceTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
all calls to ISentryExecutorService are now wrapped in a try catch block
closing the hub will close the profiler and the performance collector
Calling `init()` multiple times closes any previous instance of the SDK. 
After closing, any call to the executor service which was previously scheduled resulted in a crash due to `RejectedExecutionException`.
Fixes https://github.com/getsentry/sentry-java/issues/2493
Unit and ui test
> Fix crash on double SDK init

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/test/java/io/sentry/HubTest.kt
https://github.com/getsentry/sentry-java/pull/2679#discussion_r1182190663
Noticed while reviewing #2679
With a test that was failing prior to the fix
> Fix Hub.close using withScope and not configureScope

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
AndroidTransactionProfiler now starts/stops profiles without offloading to the executorService
removed any file checks due to the code running possibly on the main thread
wrapped Debug methods into try/catch to compensate lack of file checks
If the executor service is very busy, the profiler would start with some delay, and when finishing it would wait for the executor to finish, possibly causing ANRs.
fixes https://github.com/getsentry/sentry-java/issues/2649
Unit test
> Android Profiler on calling thread

- .sauce/sentry-uitest-android-benchmark.yml
- .sauce/sentry-uitest-android-ui.yml
changed OnePlus 9 Pro device to Samsung Galaxy S10+ in saucelabs as it doesn't exists anymore
> Changed OnePlus 9 Pro to Samsung Galaxy S10+ in Saucelabs

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
Since we see this test occasionally failing I added some more detailed error message in case the tests fail.
> Improve error output for envelope tests

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry-android-ndk/src/main/jni/sentry.c
Update sentry-native to 0.6.2
Add `SentryAndroidOptions.setNativeSdkName`
Fixes https://github.com/getsentry/sentry-java/issues/2678
Added some unit tests. Ideally we would have some integration test for this as well, but there's nothing setup as of now.
> Add API to set custom sentry-native sdk name

- CHANGELOG.md
Fixes incorrect changelog for Apollo3 Header fix
> fix incorrect changelog

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
A customer reported these 2 crashes internally, so this PR simply fixes/swallows them. Most likely they were caused by calling `Sentry.close()` in the middle of processing transactions.
*  The `synchronized` in `AndroidTransactionProfiler` should actually fix the root cause, but I've also added the null check just to make sure
* For SentryTracer fix we just swallow the exception and finish the transaction immediately if we failed to schedule the finish timer
> Fix AndroidProfiler and SentryTracer crashes

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
Adds an option to disable RootChecker
Closes #2718 
Automated
> Add option to disable RootChecker

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/threaddump/ThreadDumpParser.java
- sentry-android-core/src/test/java/io/sentry/android/core/internal/threaddump/ThreadDumpParserTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/SentryStackFrame.java
- sentry/src/test/java/io/sentry/protocol/SentryStackFrameSerializationTest.kt
- sentry/src/test/resources/json/sentry_stack_frame.json
This is necessary in addition to `SentryThread.held_locks` to highlight the offending frame in the UI, so the lock has to be also on the per-frame level.
Relay PR: https://github.com/getsentry/relay/pull/2171
Q2 Goal
> Add lock attribute to the frame protocol

- CHANGELOG.md
- sentry-android-sqlite/src/main/java/io/sentry/android/sqlite/SQLiteSpanManager.kt
- sentry-android-sqlite/src/test/java/io/sentry/android/sqlite/SQLiteSpanManagerTest.kt
Extends the instrumented spans with main thread information. If the query executes on the main thread, a stack trace is added as well. Based on https://github.com/getsentry/sentry-java/blob/baa4b26a8940ca5785af4ee5cf8fa18b8aedeadd/sentry/src/main/java/io/sentry/instrumentation/file/FileIOSpanManager.java#L104-L108
We want to have database on main thread issues.
> Enrich database spans with blocked main thread info

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/Request.java
- sentry/src/main/java/io/sentry/protocol/Response.java
- sentry/src/test/java/io/sentry/protocol/RequestSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/RequestTest.kt
- sentry/src/test/java/io/sentry/protocol/ResponseSerializationTest.kt
- sentry/src/test/resources/json/contexts.json
- sentry/src/test/resources/json/request.json
- sentry/src/test/resources/json/response.json
- sentry/src/test/resources/json/sentry_base_event.json
- sentry/src/test/resources/json/sentry_base_event_with_null_extra.json
- sentry/src/test/resources/json/sentry_event.json
- sentry/src/test/resources/json/sentry_transaction.json
- sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
Relates to https://github.com/getsentry/relay/pull/2141
> Add `api_target` to `Request` and `data` to `Response` Protocols

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/util/StringUtils.java
- sentry/src/test/java/io/sentry/util/StringUtilsTest.kt
No longer use `String.join` in `Baggage` as it requires API level 26
Fixes https://github.com/getsentry/sentry-java/issues/2774
Unit Tests
> No longer use `String.join` in `Baggage` as it requires API level 26

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DataCategory.java
- sentry/src/main/java/io/sentry/clientreport/ClientReportRecorder.java
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
- sentry/src/test/java/io/sentry/clientreport/ClientReportTest.kt
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
added profile rate limiting
added Profile type in ClientReportRecorder, DataCategory and RateLimiter
Closes https://github.com/getsentry/sentry-java/issues/2017 
Unit test
> Add profile rate limiting

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/proguard-rules.pro
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2Integration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/threaddump/ThreadDumpParser.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2IntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/internal/threaddump/ThreadDumpParserTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Attachment.java
- sentry/src/main/java/io/sentry/Hint.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/hints/HintTest.kt
The PR introduces various improvement to the existing ANRv2 implementation based on customer feedback, namely:
* Adds a rule to keep `ApplicationNotResponding` class from obfuscation so it doesn't look ugly in the issue stream
* Adds an option `setReportHistoricalAnrs`, when enabled it will report all of the ANRs from the `getHistoricalExitReasons` list. By default, the SDK only reports and enriches the latest ANR and only this one counts towards ANR rate. Hence, this reduces the noise quite a bit, but still leaves the possibility to get all of the ANR reports from the past. Worth noting that once the SDK has been updated to the version with the new implementation, we won't need this feature, because we'll always read the latest ANR on the next app restart. These ANRs are reported with …
> Improve ANRv2 implementation based on customer feedback

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
Use env from SentryOptions if none persisted in ANRv2
Internal feedback
> Use env from SentryOptions if none persisted in ANRv2

- CHANGELOG.md
Fixes CHANGELOG - moving note about Tracing without Performance to 6.25.0
> Fix CHANGELOG for Tracing without Performance

- CHANGELOG.md
- sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/2767
> Capture failed HTTP requests by default

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java
changed metrics listener map from HashMap to ConcurrentHashMap
Fixes https://github.com/getsentry/sentry-java/issues/2816
> Fix concurrent access to frameMetrics listener

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/SendCachedEnvelopeIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransactionProfilerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SendCachedEnvelopeIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/util/LazyEvaluator.java
- sentry/src/test/java/io/sentry/util/LazyEvaluatorTest.kt
configure options now happens after adding integrations in `SentryAndroid.init`
added LazyEvaluator to evaluate a function lazily
AndroidOptionsInitializer.installDefaultIntegrations now evaluate cache dir lazily 
Fixes https://github.com/getsentry/sentry-java/issues/2821 and https://github.com/getsentry/sentry-java/issues/2355
Unit test
> Allow removing integrations in SentryAndroid.init

- .github/workflows/agp-matrix.yml
android emulators used for tests are now cached
Speedup the tests in CI
> Cache Android test emulators

- .github/workflows/agp-matrix.yml
reverted gradle cache on gha, as it seems to slow down tests
> reverted gradle cache on github actions

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/InternalSentrySdk.java
- sentry-android-core/src/test/java/io/sentry/android/core/InternalSentrySdkTest.kt
Use configureScope instead of withScope, as it doesn't (partially) deep-copy the scope.
Doesn't really seem to be a problem as scope.session is never deep-copied.
> Fix ensure session is updated using configureScope

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/SentryGestureListener.java
- sentry-android-core/src/test/java/io/sentry/android/core/internal/gestures/SentryGestureListenerTracingTest.kt
Do not overwrite UI transaction status if set by the user
Closes #2378
> Do not overwrite UI transaction status if set by the user

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java
- sentry/src/main/java/io/sentry/HostnameCache.java
- sentry/src/main/java/io/sentry/JsonObjectDeserializer.java
- sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
As discussed, let's try to avoid using methods refs for code which gets executed on the Android platform.
Fixes https://github.com/getsentry/sentry-java/issues/2848
> Ensure no Java 8 method reference sugar is used for Android

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
Reduce flush timeout to 4s on Android to avoid ANRs
[Fixes #2732](https://github.com/getsentry/sentry-java/issues/2732)
> Reduce flush timeout to 4s on Android to avoid ANRs

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry/src/main/java/io/sentry/MainEventProcessor.java
- sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
For disabling: The project configuration has a toggle to disable storing
the IP address.
Fixes https://github.com/getsentry/sentry-java/issues/2850
> Set ip_address = {{auto}} by default

- sentry-android-core/src/main/java/io/sentry/android/core/InternalSentrySdk.java
- sentry-android-core/src/test/java/io/sentry/android/core/InternalSentrySdkTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/Scope.java
Fixes https://github.com/getsentry/sentry-java/pull/2814#discussion_r1272111324
> Use configureScope instead of withScope for InternalSentrySdk

- .sauce/sentry-uitest-android-ui.yml
ui tests on saucelabs now are selected based on OS version only
We don't care about the specific device the tests run on, only the OS version, contrary to benchmarks.
This will improve saucelabs faults due to a specific device being already in use when we try to run a test.
🙃
> UI tests on saucelabs are now selected based on OS version only

- CHANGELOG.md
- sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpEvent.kt
- sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpEventListener.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventListenerTest.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventTest.kt
status of OkHttp calls now gets propagated to parent span
when OkHttp call finishes, status of unfinished spans is not overridden and is set to INTERNAL_ERROR
OkHttp calls are grouped in a tree of parent-children. If a child span fails with status `internal_error`, the parent span has a different status, but it should be `internal_error`, too.
Fixes https://github.com/sentry-demos/android/issues/60 
Unit test
> propagate okhttp status to parent spans

- CHANGELOG.md
- sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt
- sentry-apollo/src/test/java/io/sentry/apollo/SentryApolloInterceptorTest.kt
Adds nullability to BeforeSpanCallback callback
Fixes https://github.com/getsentry/sentry-java/issues/2149
> Apollo v2 BeforeSpanCallback: Allow returning null

- .craft.yml
> Add spring autoconfigure modules to registry task in `.craft.yml`

- .github/workflows/build.yml
- Makefile
- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-navigation/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-okhttp/build.gradle.kts
- sentry-android-sqlite/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-compose/build.gradle.kts
> Codecov reports for Android modules

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/SentryGestureListener.java
- sentry-android-core/src/test/java/io/sentry/android/core/internal/gestures/SentryGestureListenerTracingTest.kt
Adapt click user interaction behavior to JS: launch new transaction on every click.
Scroll and swipes behavior stays unchanged.
Fixes https://github.com/getsentry/sentry-java/issues/2594
> Start a new automatic transaction on every click

- CHANGELOG.md
- sentry-jdbc/api/sentry-jdbc.api
- sentry-jdbc/build.gradle.kts
- sentry-jdbc/src/main/java/io/sentry/jdbc/DatabaseUtils.java
- sentry-jdbc/src/main/java/io/sentry/jdbc/SentryJdbcEventListener.java
- sentry-jdbc/src/test/kotlin/io/sentry/jdbc/DatabaseUtilsTest.kt
- sentry-jdbc/src/test/kotlin/io/sentry/jdbc/SentryJdbcEventListenerTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SpanDataConvention.java
- sentry/src/main/java/io/sentry/util/StringUtils.java
- sentry/src/test/java/io/sentry/util/StringUtilsTest.kt
Send `db.system` and `db.name` in DB span data. To do this we have to parse the JDBC connection string.
Parts of what's required for https://github.com/getsentry/sentry-java/issues/2893
Unit tests, manually
- More fields could be extracted from the JDBC string
- Not all db systems are fully supported by the parser yet
> Send `db.system` and `db.name` in span data

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
A new option to disable sending modules.
I saw this option is in [ruby options](https://docs.sentry.io/platforms/ruby/configuration/options/), but this option is not present in java options.
This option can be useful when you don't need to send a list of modules with versions.
When using sentry-spring-boot-starter you can use this option in application.yaml
I tested it using spring boot app
> Add send-modules option

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/DeviceInfoUtil.java
- sentry-android-core/src/test/java/io/sentry/android/core/DeviceInfoUtilTest.kt
We were not sending memory stats for transactions by default, but reading memory stats does not require any IO or IPC, we just querying `ActivityManager`, so it should be fine to always send it.
As a result we can query transactions by `device.class` now
Closes #2929 
Manually
> Always send memory stats for transactions

- CHANGELOG.md
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/resources/application.properties
- sentry-spring-boot-jakarta/api/sentry-spring-boot-jakarta.api
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProperties.java
Add property `sentry.enable-aot-compatibility` to disable AOP, which breaks GraalVM Builds. 
Currently it's not possible to build for GraalVM with performance enabled due to AOP on `@SentryTransaction` and `@SentrySpan`. With this change performance can be enabled, but the AOP functionality is turned off.
Fixes #2742
Add `id("org.graalvm.buildtools.native") version "0.9.24"` plugin to `build.gradle` and run the `bootBuildImage` command.
> add property to disable AOP related features that break graalvm build

- CHANGELOG.md
- sentry-android-core/src/test/java/io/sentry/android/core/SessionTrackingIntegrationTest.kt
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/CustomJob.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/CheckIn.java
- sentry/src/main/java/io/sentry/CheckInStatus.java
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/ISentryClient.java
- sentry/src/main/java/io/sentry/MonitorConfig.java
- sentry/src/main/java/io/sentry/MonitorContexts.java
- sentry/src/main/java/io/sentry/MonitorSchedule.java
- sentry/src/main/java/io/sentry/MonitorScheduleType.java
- sentry/src/main/java/io/sentry/MonitorScheduleUnit.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpSentryClient.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
- sentry/src/main/java/io/sentry/SentryItemType.java
- sentry/src/test/java/io/sentry/CheckInSerializationTest.kt
- sentry/src/test/java/io/sentry/HubAdapterTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/resources/json/checkin_crontab.json
- sentry/src/test/resources/json/checkin_interval.json
Add API for sending checkins (CRONS) manually.
Simplest usage looks like:
```
Sentry.captureCheckIn(new CheckIn("my_monitor", CheckInStatus.OK))
```
One of the parts required for https://github.com/getsentry/sentry-java/issues/2875
Manually, automated tests
> Add API for sending checkins (CRONS) manually

- sentry-quartz/src/main/java/io/sentry/quartz/SentryJobListener.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/checkin/SentryCheckInAdvice.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentryCheckInAdviceTest.kt
- sentry-spring/src/main/java/io/sentry/spring/checkin/SentryCheckInAdvice.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentryCheckInAdviceTest.kt
> CRONS pushScope, new PropagationContext, popScope

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ScreenshotEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/ViewHierarchyEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/Debouncer.java
- sentry-android-core/src/test/java/io/sentry/android/core/ScreenshotEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ViewHierarchyEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/internal/util/DebouncerTest.kt
- sentry/src/test/java/io/sentry/NoOpHubTest.kt
- sentry/src/test/java/io/sentry/NoOpSentryClientTest.kt
improve default SS/VH debouncing mechanism: after 3 times occurring in a time frame, the next occurrence is debounced
added execution counter to Debouncer
Closes https://github.com/getsentry/sentry-java/issues/2917
Unit test
> improve default debouncing mechanism

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/util/CheckInUtils.java
- sentry/src/test/java/io/sentry/util/CheckInUtilsTest.kt
A util class that send a check-in (`IN_PROGRESS`) before the code being passed in is executed and another check-in (`OK` or `ERROR`) once the code has completed. It also starts a new trace.
Simplifies manual check-ins.
Manually + unit tests
> Add `CheckInUtils.withCheckIn` which abstracts away some of the manual check-ins complexity

- CHANGELOG.md
- sentry-samples/sentry-samples-openfeign/src/main/java/io/sentry/samples/openfeign/Main.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/test/java/io/sentry/HubAdapterTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
Remove `startTransaction` overloads that can be replaced by passing `TransactionOptions`.
Closes #2754
> Improve start transaction overloads

- CHANGELOG.md
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryWebExceptionHandler.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebExceptionHandler.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/TypeCheckHint.java
Added ServerWebExchange as a property in the Hint object
Closes https://github.com/getsentry/sentry-java/issues/2974
Unit tests
> Added ServerWebExchange as Hint property

- CHANGELOG.md
- sentry-graphql/api/sentry-graphql.api
- sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java
- sentry-graphql/src/test/kotlin/io/sentry/graphql/SentryInstrumentationAnotherTest.kt
- sentry-graphql/src/test/kotlin/io/sentry/graphql/SentryInstrumentationTest.kt
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/resources/application.properties
- sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
- sentry-spring-boot-jakarta/api/sentry-spring-boot-jakarta.api
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProperties.java
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/graphql/SentryGraphqlAutoConfiguration.java
- sentry-spring-boot/api/sentry-spring-boot.api
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/SentryProperties.java
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/graphql/SentryGraphqlAutoConfiguration.java
Allow users to privde a `List<String>` to filter out certain GraphQL errors. Decided to use `String` instead of a specific type as `String` can easily be set in config files.
Closes #2899
Manually + unit tests
> Allow filtering graphql errors

- CHANGELOG.md
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
There's tutorials out there suggesting to use an Encoder to mask/strip PII from log messages. Therefore we now guard the raw message and parameters with `sendDefaultPii` if an `encoder` has been configured.
Closes https://github.com/getsentry/sentry-java/issues/2973
Unit tests, manually using logback sample
> Guard raw logback message and parameters with `sendDefaultPii` if an `encoder` has been configured

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java
choreographer instance is now retrieved in a try/catch block, due to a crash reported by Google Play SDK console
Fixes a crash. Closes https://github.com/getsentry/sentry-java/issues/2912
> Fix crash accessing Choreographer instance

- CHANGELOG.md
> Fix Changelog again

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-android-core/src/main/java/io/sentry/android/core/ContextUtils.java
- sentry-android-core/src/main/java/io/sentry/android/core/DeviceInfoUtil.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ContextUtilsUnitTests.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
registerReceiver now sets the RECEIVER_NOT_EXPORTED flag on API 33+
updated SDK target version to 34
Starting from Android 14, it is necessary to explicitly set the export behavior for runtime-registered broadcasts as described [here](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported).
Fixes https://github.com/getsentry/sentry-java/issues/2986
> Set export flag on Android receivers on API 33+

- CHANGELOG.md
- sentry-android-ndk/api/sentry-android-ndk.api
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/DebugImagesLoader.java
DebugImagesLoader is now public, to allow manually init the NDK
Fixes https://github.com/getsentry/sentry-java/issues/2957
> Make DebugImagesLoader public

- sentry-android-integration-tests/sentry-uitest-android-benchmark/src/androidTest/java/io/sentry/uitest/android/benchmark/SdkBenchmarkTest.kt
- sentry-android-integration-tests/sentry-uitest-android-benchmark/src/androidTest/java/io/sentry/uitest/android/benchmark/SentryBenchmarkTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/AutomaticSpansTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
- sentry/src/test/java/io/sentry/SentryWrapperTest.kt
removed ui test EnvelopeTests.checkProfileNotSentIfEmpty. Added unit test with same goal: SentryEnvelopeItemTest.fromProfilingTrace with empty file throws
added description messages to eventually failing benchmark tests
added small sleeps in SentryWrapperTest to avoid race conditions
This should greatly reduce CI flakyness
> Improve ui and unit tests

- sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/FirstDrawDoneListener.java
- sentry/src/main/java/io/sentry/CircularFifoQueue.java
- sentry/src/main/java/io/sentry/SynchronizedCollection.java
- sentry/src/main/java/io/sentry/SynchronizedQueue.java
- sentry/src/main/java/io/sentry/transport/ReusableCountLatch.java
- sentry/src/main/java/io/sentry/vendor/Base64.java
- sentry/src/main/java/io/sentry/vendor/gson/internal/bind/util/ISO8601Utils.java
- sentry/src/test/java/io/sentry/transport/ReusableCountLatchTest.kt
- sentry/src/test/java/io/sentry/vendor/gson/internal/bind/util/ISO8601UtilsTest.java
Add missing license headers, or change them to adhere to the correct structure
Closes #2619
> Add missing license headers

- CHANGELOG.md
- sentry/src/main/java/io/sentry/transport/HttpConnection.java
- sentry/src/test/java/io/sentry/transport/HttpConnectionTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/3001
> Fix crash when HTTP connection error message contains formatting symbols

- CHANGELOG.md
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
- sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
- sentry-samples/sentry-samples-android/src/main/res/values/strings.xml
- sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
- sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt
> Cap max number of stack frames to 100 to not exceed payload size limit

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-compose-helper/src/jvmMain/java/io/sentry/compose/gestures/ComposeGestureTargetLocator.java
- sentry-compose/proguard-rules.pro
Extends the behaviour for determining if a LayoutNode is clickable/scrollable. This change should be backwards compatible as the old logic still stays intact for older versions of Jetpack Compose.
Fixes https://github.com/getsentry/sentry-java/issues/2978
Manual tests, we definitely should setup a test matrix for different Jetpack Compose versions.
> Fix user interaction tracking not working for Jetpack Compose 1.5+

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/SpanDataConvention.java
- sentry/src/test/java/io/sentry/OutboxSenderTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
Whenever SentryTracer creates a span, it immediately sets the main thread flag.
Fixes https://github.com/getsentry/sentry-java/issues/2997
Open questions: How do deal with our existing main thread flagging.
E.g. SentryFileInputStream sets the flag on `.close()` and right now would overwrite the flag - IMHO that's fine.
Add Unit test
> Tag all spans with main thread flag

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryExceptionFactory.java
- sentry/src/main/java/io/sentry/SentryStackTraceFactory.java
- sentry/src/main/java/io/sentry/SentryThreadFactory.java
- sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt
- sentry/src/test/java/io/sentry/SentryStackTraceFactoryTest.kt
* Send SDK frames for uncaught exceptions to enable SDK detection on Java/Android
Here's a sample event for testing https://sentry-sdks.sentry.io/issues/4595173909/events/ea05056bfc2b4f42ae04df91a4745881/
Closes #2758 
> Send SDK frames in case of crashes

- sentry-android-core/src/main/java/io/sentry/android/core/ContextUtils.java
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/AutomaticSpansTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/EnvelopeAsserter.kt
- sentry-test-support/api/sentry-test-support.api
- sentry-test-support/src/main/kotlin/io/sentry/Assertions.kt
improved deserialization of envelope items using header type to avoid oom errors
removed screen refresh rate from maximum allowed timestamp
Fixes errors like https://github.com/getsentry/sentry-java/actions/runs/6743234669/job/18330770480
> Fix UI tests deserialization of envelope items

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Dsn.java
- sentry/src/test/java/io/sentry/DsnTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/3025
Inspired by https://github.com/getsentry/sentry-python/blob/36c2650ccc6edcd300e2d207d7123b12c8b77b27/sentry_sdk/utils.py#L237-L238
Ensure we crash early on when an invalid dsn is provided.
> Ensure DSN uses http/https protocol

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
moved assertions after "assume" call
The `checkEnvelopeProfiledTransaction` test is already skipped on headless emulator (agp matrix), but some assertions were done before the `assume` call, which is the one that skips the test. So sometimes those assertions could throw in the agp matrix workflow. 
Fixes issues like https://github.com/getsentry/sentry-java/actions/runs/6814073423/job/18530091061?pr=3036
> moved assertions after "assume" call

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/util/CheckInUtils.java
- sentry/src/test/java/io/sentry/util/CheckInUtilsTest.kt
Add `MonitorConfig` param to `CheckInUtils.withCheckIn`.
This makes it easier to perform upserts.
Unit Test.
> Add `MonitorConfig` param to `CheckInUtils.withCheckIn`

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/util/DebugMetaPropertiesApplier.java
This PR exposes funtion which retrieves the proguard uuid property.
This will be used by Hybdrid SDKs.
- https://github.com/getsentry/sentry-react-native/pull/3397
RN sample app
> feat(debugmeta): Add `getProguardUuid`

- CHANGELOG.md
https://github.com/getsentry/sentry-java/releases/tag/6.33.2-beta.1 did not include the two mentioned futures.
They are still to be released.
> Fix changelog move feature from beta to unreleased

- sentry/src/main/java/io/sentry/Scope.java
Sorry. I'm sure this is super helpful.
> chore: Comments cleanup in `Scope.java`

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/TempSensorBreadcrumbsIntegrationTest.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventListenerTest.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventTest.kt
- sentry-test-support/api/sentry-test-support.api
- sentry-test-support/src/main/kotlin/io/sentry/test/Mocks.kt
- sentry-test-support/src/main/kotlin/io/sentry/test/Reflection.kt
- sentry/src/test/java/io/sentry/DefaultTransactionPerformanceCollectorTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
moved several integrations to the background to reduce main thread usage on SDK init:
-AnrIntegration
-PhoneStateBreadcrumbsIntegration
-SystemEventsBreadcrumbsIntegration
-TempSensorBreadcrumbsIntegration
Relates to https://github.com/getsentry/sentry-java/issues/2222
It continues the work done on https://github.com/getsentry/sentry-java/pull/3036
Fixes https://github.com/getsentry/sentry-java/issues/3040
> Move integrations registration to background during init

- CHANGELOG.md
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
> Respect maxSpans for nested child spans

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SendCachedEnvelopeIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SendCachedEnvelopeIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/TempSensorBreadcrumbsIntegrationTest.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventListenerTest.kt
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventTest.kt
- sentry-test-support/api/sentry-test-support.api
- sentry-test-support/src/main/kotlin/io/sentry/test/Mocks.kt
- sentry-test-support/src/main/kotlin/io/sentry/test/Reflection.kt
- sentry/src/main/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegration.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/test/java/io/sentry/DefaultTransactionPerformanceCollectorTest.kt
- sentry/src/test/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegrationTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
Moved old profiles deletion to the background
moved some Integration.register() to the background using executorService
added tests
This is an attempt to improve SDK startup timing.
Relates to https://github.com/getsentry/sentry-java/issues/2222
> Reduce main thread work on init

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SpanDataConvention.java
Add slow and frozen frame keys to span conventions, as per https://github.com/getsentry/develop/pull/1099/files
> Add slow and frozen frames span data conventions

- CHANGELOG.md
- sentry-android-core/proguard-rules.pro
Came up in internal discussion
> Keep SentryHttpClientException name from obfuscation

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollectorTest.kt
Do it in one place, so we can later use it for both the AndroidProfiler as well as txns.
Mainly moved some logic from `AndroidProfiler` to `SentryFrameMetricsAggregator`.
Added some logic to calculate the frame delay, as well as exposing frame start/end times.
Partly fixes https://github.com/getsentry/sentry-java/issues/3099
Added unit tests.
> Calculate frame delay, slow+frozen frames inside SentryFrameMetricsCollector

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/java/io/sentry/samples/spring/boot/jakarta/SecurityConfiguration.java
- sentry-samples/sentry-samples-spring-jakarta/src/main/java/io/sentry/samples/spring/jakarta/SecurityConfiguration.java
- sentry-spring-boot-jakarta/api/sentry-spring-boot-jakarta.api
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/graphql/SentryGraphqlAutoConfiguration.java
- sentry-spring-boot/api/sentry-spring-boot.api
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/graphql/SentryGraphqlAutoConfiguration.java
- sentry-spring-jakarta/api/sentry-spring-jakarta.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/graphql/SentryGraphqlBeanPostProcessor.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryReactorThreadLocalAccessor.java
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/graphql/SentryGraphqlBeanPostProcessor.java
Set `SentryGraphqlBeanPostProcessor` to run last so it does not trigger "is not eligible for getting processed by all BeanPostProcessors" warnings.
Fixes #3042 
Manually using Spring Boot samples.
> Get rid of "is not eligible for getting processed by all BeanPostProcessors" warnings in Spring Boot

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanProcessor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/SentrySpanProcessorTest.kt
Bump OpenTelemetry to `1.33.0` / `1.32.0` (Java). There also is a new dependency for semantic conventions (semconv) which has its own version (`1.23.1-alpha`) and requires different imports. There's also been some deprecations which I suppressed for now as Sentry still relies on e.g. `http.url` etc.
Fixes #3082
Manually using Spring Boot 3 sample with OTEL agent and auto init turned on and off.
> Bump OpenTelemetry version

- CHANGELOG.md
- sentry-apollo-3/api/sentry-apollo-3.api
- sentry-apollo-3/src/main/java/io/sentry/apollo3/SentryApollo3ClientException.kt
- sentry/src/main/java/io/sentry/exception/InvalidSentryTraceHeaderException.java
- sentry/src/main/java/io/sentry/exception/SentryHttpClientException.java
Exceptions implement `Serializable`, thus it's a good pratice to give `serialVersionUID` a unique value.
This _may_ helps with regard to code obfuscation too, as we've seen customer reports where Exception subclasses with the same fields get merged into a single class, giving confusing de-obfuscated results.
> Ensure serialVersionUID of Exception classes are unique

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/BaseUiTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/MockRelay.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/RelayAsserter.kt
added a check to avoid processing requests with 0 bytes bodies in ui tests (probably useless)
added a check to drop duplicated envelopes
Some envelopes were sent twice, corrupting the counter in `MockRelay` and making tests fail
> Fix Ui tests receiving empty requests

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidProfiler.java
put list for loop in synchronized block in AndroidProfiler 
Fixes https://github.com/getsentry/sentry-java/issues/3119
> Avoid concurrency in AndroidProfiler performance data collection

- sentry-android-integration-tests/sentry-uitest-android/src/main/java/io/sentry/uitest/android/ProfilingSampleActivity.kt
reduced bitmap size and background worker count in ProfilingSampleActivity to reduce the likeliness of ANRs during tests
Sometimes a test was failing, likely due to an ANR
> Reduced bitmap size and background work in ui tests

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/performance/AppStartMetricsTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/JsonSerializer.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryAppStartProfilingOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/TransactionContext.java
- sentry/src/main/java/io/sentry/TransactionOptions.java
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/TransactionContextTest.kt
Manifest option: 
io.sentry.traces.profiling.enable-startup -> io.sentry.traces.profiling.enable-app-start
Sentry option:
enableStartupProfiling -> enableAppStartProfiling
AppStartMetrics fields:
startupSamplingDecision -> appStartSamplingDecision
startupProfiler -> appStartProfiler
TransactionContext field:
isForNextStartup -> isForNextAppStart
TransactionOptions field:
isStartupTransaction -> isAppStartTransaction
Class
SentryStartupProfilingOptions -> SentryAppStartProfilingOptions
Config file name:
startup_profiling_config -> app_start_profiling_config
Let's align with appStartTracing naming. Also, cocoa is going to do the same.
We didn't release a version, so we don't need to support the old name.
This is mostly to make this feature more clear to the user
> Renamed startupProfiling to appStartProfiling

- CHANGELOG.md
- sentry/src/main/java/io/sentry/TracesSamplingDecision.java
We had a breaking change which we thought wasn't used by (many) customers. This documents the breaking change and explains how to fix.
> Document breaking change in `6.2.1` and remove internal annotation

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/transport/HttpConnection.java
- sentry/src/test/java/io/sentry/transport/HttpConnectionTest.kt
This was mainly used by self-hosted users who has a self-signed certificate. There will be 3 options for them going forward:
* Provide a custom `ITransportFactory`, where they can copy over most parts like `HttpConnection` and `AsyncHttpTransport` with necessary modifications
* Get a certificate for their server through e.g. Let's Encrypt
* Fork the SDK and add the hostname verifier back
It's a breaking change, but we agreed that the impact is gonna be so small that it's not worth waiting for the next major, given that it produces so many false positives by security tools of some app stores
Closes https://github.com/getsentry/sentry-unity/issues/1513
> Remove HostnameVerifier option

- .github/workflows/integration-tests-ui.yml
Since we can't do much when test orchestrator itself fails, I think it's fair to ignore those failures.
Ignore TestOrchestrator failures by checking the logs for presence of "process crashed" entry. If there's a failing test, it will actually print a proper stacktrace (like [here](https://github.com/getsentry/sentry-java/actions/runs/7624407511/job/20766479920)), so we're narrowing this down only to test orchestration issues.
> Ignore TestOrchestrator failures

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryFrameMetrics.java
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryFrameMetricsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SpanFrameMetricsCollectorTest.kt
Interpolate the total_frame count in order to match the span duration.
If there are no content changes on Android, also no frames are rendered, thus no frame metrics are provided by the system.
In order to match the span duration with the total frame count, we simply interpolate the total number of frames based on the span duration, based on the last known refresh rate.
This way the data is more sound and we also match the output of the cocoa SDK
> Interpolate total frame count to match span duration

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryFrameMetrics.java
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryFrameMetricsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SpanFrameMetricsCollectorTest.kt
Similar to https://github.com/getsentry/sentry-java/blob/a45911fbaca266a0af3eee9a66bbcfecbfe0b40c/sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java#L161-L172 we want to report slow and frozen frame count for transactions, just like we had before.
> Collect slow and frozen frames as measurements

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
Ideally we would do this server-side, but built-in server-side fingerprint rules are still [WIP](https://github.com/getsentry/sentry/blob/58c2ce2469c5b81ec63a343ae98cb8710e7169d4/src/sentry/conf/server.py#L1552-L1553), so I think we can get away with doing it on the SDK side for now. We only set the fingerprint if user hasn't defined their custom rules to not override them. 
Multiple internal reports from customers
> Set default fingerprint for ANR v2 events to correctly group background and foreground ANRs

- CHANGELOG.md
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpEventTest.kt
… to http root call span
scheduled finish timestamp now applies to all running spans, not only to http root call span
When the response is not read, we finish the OkHttp span automatically.
We were finishing the root call span at the last http span timestamp, but we were not applying it to all other OkHttp running spans.
[An image is worth more than a thousand words](https://demo.sentry.io/performance/android:c2475d976c3942c296351f558a7dc936/?limit=100&transaction=EmpowerPlantActivity)
Unit test
> Apply OkHttp listener auto finish timestamp to all running spans

- CHANGELOG.md
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpEventTest.kt
increased SentryOkHttpEvent.scheduleFinish timeout 500ms -> 800ms
added a guard to avoid finishing an already finished event
If an OkHttp event was finished multiple times, multiple breadcrumbs would been sent.
This was possible when the response of a call was closed (or read) after more than 500ms since it was received, as our timeout automatically closes the call after 500ms.
I increased the timeout to 800ms to make it less likely to happen. And I added a flag to skip closing the event if it was already closed.
Likely relates to https://github.com/getsentry/sentry-android-gradle-plugin/issues/617
Unit tests
> Avoid multiple breadcrumbs from OkHttpEventListener

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-samples/sentry-samples-spring-boot-jakarta/src/main/resources/application.properties
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/internal/SpotlightIntegration.java
> Spotlight fixes for Backend

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/MonitorConfig.java
- sentry/src/test/java/io/sentry/CheckInSerializationTest.kt
- sentry/src/test/java/io/sentry/util/CheckInUtilsTest.kt
- sentry/src/test/resources/json/checkin_crontab.json
- sentry/src/test/resources/json/checkin_interval.json
> Add new threshold parameters to monitor config

- CHANGELOG.md
- sentry-compose-helper/src/jvmMain/java/io/sentry/compose/gestures/ComposeGestureTargetLocator.java
Using the latest version of Compose, the compiler plugin sometimes does not fold `SentryTraced` into the same UI Node element anymore. This causes our `SentryTag` semantic to be inside the parent node, but the `Clickable` semantic ends up in the child node.
Fixes https://github.com/getsentry/sentry-java/issues/3208
I was able to reproduce the issue locally, did some manual tests.
We definitely need to get better at automating this, right now it's super painful as newer versions of Compose require a newer versions of Kotlin. This in turn requires bumping some plugins (e.g. detekt), which then in turn emit new build time errors.
> Fix Compose widgets are not being correctly identified

- CHANGELOG.md
- sentry-android-core/src/test/java/io/sentry/android/core/InternalSentrySdkTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SessionTrackingIntegrationTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/MockRelay.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/mockservers/RelayAsserter.kt
- sentry-apache-http-client-5/api/sentry-apache-http-client-5.api
- sentry-apache-http-client-5/src/main/java/io/sentry/transport/apache/ApacheHttpClientTransport.java
- sentry-apache-http-client-5/src/test/kotlin/io/sentry/transport/apache/ApacheHttpClientTransportTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/IHub.java
- sentry/src/main/java/io/sentry/ISentryClient.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpSentryClient.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/transport/AsyncHttpTransport.java
- sentry/src/main/java/io/sentry/transport/ITransport.java
- sentry/src/main/java/io/sentry/transport/NoOpTransport.java
- sentry/src/main/java/io/sentry/transport/StdoutTransport.java
- sentry/src/test/java/io/sentry/HubAdapterTest.kt
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/NoOpHubTest.kt
- sentry/src/test/java/io/sentry/NoOpSentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/transport/AsyncHttpTransportTest.kt
added new methods to close instances with isRestarting flag:
- IHub.close(Boolean)
- ISentryClient.close(Boolean)
- ITransport.close(Boolean)
when the SDK restarts 
- the executor service is now closed in the background
- current network connections are dropped. This is not a problem, as data will be sent anyway after the SDK restarts
We still wait for any processing that is happening, as that's more complex, but the biggest slowdown when restarting the SDK is waiting for the network to send data.
When the SDK is initialized multiple times, it closes the old instance, waiting for any task to be completed.
This PR aims to reduce the wait time by dropping network connections and let any job scheduled to the executor to be finished in the background.
Relates to …
> Don't wait on main thread when SDK restarts

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryFrameMetrics.java
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryFrameMetricsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SpanFrameMetricsCollectorTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/FrameDataForSpansActivity.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
- sentry-samples/sentry-samples-android/src/main/res/layout/activity_main.xml
- sentry-samples/sentry-samples-android/src/main/res/values/strings.xml
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SpanDataConvention.java
- sentry/src/main/java/io/sentry/protocol/MeasurementValue.java
Fixes https://github.com/getsentry/sentry-java/issues/3183
https://github.com/getsentry/sentry-java/assets/1411808/9b78e1c8-110a-4b32-bc3d-a1fd023f22a6
> Calculate frame delay on a span level

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Sentry.java
profiles deleted on init now need to be at least 5 minutes older than the class creation time to account for app start profiles
App start profiles could have a lower timestamp than the class creation, resulting in the SDK deleting the app start profile during init
> Fix old profiles deletion on SDK init

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/MetricsAggregator.java
- sentry/src/main/java/io/sentry/metrics/CounterMetric.java
- sentry/src/main/java/io/sentry/metrics/DistributionMetric.java
- sentry/src/main/java/io/sentry/metrics/GaugeMetric.java
- sentry/src/main/java/io/sentry/metrics/Metric.java
- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
- sentry/src/main/java/io/sentry/metrics/SentryMetric.java
- sentry/src/main/java/io/sentry/metrics/SetMetric.java
- sentry/src/test/java/io/sentry/MetricsAggregatorTest.kt
- sentry/src/test/java/io/sentry/metrics/CounterMetricTest.kt
- sentry/src/test/java/io/sentry/metrics/DistributionMetricTest.kt
- sentry/src/test/java/io/sentry/metrics/GaugeMetricTest.kt
- sentry/src/test/java/io/sentry/metrics/SetMetricTest.kt
Implement the force flush behavior described here: https://develop.sentry.dev/sdk/metrics/#aggregator-behavior
Details like max_weight taken from https://github.com/getsentry/sentry-python/blame/master/sentry_sdk/metrics.py
> Force flush metrics when weight is too high

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
For now PersistingScopeObserver is used only for ANRv2, but it's generic enough that we can use it for other features (e.g. to address #547), hence we're introducing a new flag to disable scope persistence separately. 
We should also think how to improve its performance see #3168 
Part of https://github.com/getsentry/sentry-unity/issues/1555
> Add enableScopePersistence option

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidCpuCollector.java
- sentry/src/main/java/io/sentry/DefaultTransactionPerformanceCollector.java
performance measurement collection now waits at least 10ms between collections
compiled regex in AndroidCpuCollector to parse the cpu file, to improve speed
Some UI tests are failing. Also, measurements taken too quickly (1ms) caused issues when the backend parsed the data. It was resolved in the backend, but it's something we should avoid in the first place
> Ensure performance measurement collection is not taken too frequently

- CHANGELOG.md
- sentry-spring-jakarta/api/sentry-spring-jakarta.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryTaskDecorator.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/SentryScheduleHook.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentryTaskDecoratorTest.kt
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/webflux/SentryScheduleHookTest.kt
- sentry-spring/src/main/java/io/sentry/spring/SentryTaskDecorator.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryScheduleHook.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentryTaskDecoratorTest.kt
- sentry-spring/src/test/kotlin/io/sentry/spring/webflux/SentryScheduleHookTest.kt
- sentry/src/main/java/io/sentry/SentryWrapper.java
- sentry/src/test/java/io/sentry/SentryWrapperTest.kt
Fix restore point for hub in async wrappers
- SentryWrapper
- SentryScheduleHook
- SentryTaskDecorator
Fixes #3177
> Fix hub restore in async wrappers

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
As these spans are synthetic, they don't get enriched with thread info. Given that all of them run on the main thread, it should be safe to directly add the main thread info to them.
> Fix add missing thread name/id to app start spans

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/main/java/io/sentry/protocol/SentrySpan.java
- sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/SpanTest.kt
- sentry/src/test/java/io/sentry/protocol/SentrySpanSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryTransactionSerializationTest.kt
- sentry/src/test/resources/json/sentry_span.json
- sentry/src/test/resources/json/sentry_span_legacy_date_format.json
- sentry/src/test/resources/json/sentry_transaction.json
- sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
- sentry/src/test/resources/json/sentry_transaction_no_measurement_unit.json
spans forward measurements to transaction
added measurements to spans
spans forward measurements to transaction
[Example transaction](https://sentry-sdks.sentry.io/performance/sentry-android:1cb0481f3b564ce899296156ea61dbae/?project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=1h&transaction=MainActivity&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
Fixes https://github.com/getsentry/sentry-java/issues/3180
Unit tests
> Add support for measurements at span level

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/MonitorConfig.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/util/CheckInUtilsTest.kt
Allow configuring global default values for  `checkinMargin`, `maxRuntime`, `timezone`, `recoveryThreshold` and `failureIssueThreshold` of `MonitorConfig` through `SentryOptions`.
Fixes #3122
> Defaults for Cron - MonitorConfig

- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
- sentry/src/test/java/io/sentry/metrics/MetricsHelperTest.kt
see https://github.com/getsentry/develop/pull/1171
and https://github.com/getsentry/relay/pull/3174
and https://github.com/getsentry/sentry-python/pull/2775
Whitespace is fine.
#skip-changelog 
-- as the feature hasn't been released yet.
> Allow whitespace in metric tag values

- buildSrc/src/main/java/Config.kt
- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/build.gradle.kts
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/Windows.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleFrameMuxer.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleMp4FrameMuxer.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ViewHierarchyNode.kt
This is just a dump of the PoC phase more-or-less, so a lot will be refactored and made pretty, but you're welcome to review nonetheless. I've tried to left TODOs where I see changes forthcoming 
Relates to: 
* https://github.com/getsentry/sentry/issues/63255
> [SR] Add screenshot recorder

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/metrics/MetricsApi.java
- sentry/src/main/java/io/sentry/metrics/NoopMetricsAggregator.java
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/metrics/MetricsApiTest.kt
As described in the RFC: https://github.com/getsentry/rfcs/edit/main/text/0123-metrics-correlation.md
We want `.timing()` to be in span-creating mode, meaning a span is automatically created.
> Add support for span creating mode in metrics.timing API

- CHANGELOG.md
Preview: https://github.com/getsentry/sentry-java/blob/chore/metrics-changelog/CHANGELOG.md
> Unify Metrics changelog entry

- .github/workflows/release.yml
> Fix release pipeline being unable to fetch tags

- Makefile
- build.gradle.kts
- gradle.properties
An attempt to fix CI issues where certain gradle tasks simply get stuck forever. E.g. https://github.com/getsentry/sentry-java/actions/runs/8200009043/job/22426029447?pr=3253#step:5:1524
Reliable CI!
> Increase gradle memory pool size from 4gb to 12gb, crash on OOM

- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/LifecycleWatcher.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/LifecycleWatcherTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayCache.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayController.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/TraceContext.java
- sentry/src/test/java/io/sentry/BaggageTest.kt
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/TraceContextSerializationTest.kt
- sentry/src/test/resources/json/sentry_envelope_header.json
- sentry/src/test/resources/json/trace_state.json
* Add `buffer` mode to buffer last 30s of replay and send them together with an error/crash event
* Link replays with events/transactions via the DSC and the `replayId` tag
> [SR] Add buffer mode and link replays with events/transactions

- CHANGELOG.md
- sentry/src/main/java/io/sentry/TransactionOptions.java
fixed default deadline timeout to 30s instead of 300s
some transaction were kept alive for 5 minutes instead of 30 seconds
> fixed default deadline timeout to 30s instead of 300s

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/transport/HttpConnection.java
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/transport/HttpConnectionTest.kt
Until now the proxy type was hardcoded to HTTP, let's allow other types (e.g. SOCKS) as well. 
Customer feedback
> Extend Proxy options with proxy type

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
When using our Spring Boot integration in servlet mode but without having `spring-webmvc` as a dependency an exception occurred during startup.
This is caused by the return type of the `@Bean` declaration already being loaded before the `@ConditionalOnClass` is checked. To avoid it we wrap the bean definition in another `@Configuration` class.
The `ConditionalOnClass` JavaDoc mentions this:
> Extra care must be taken when using `@ConditionalOnClass` on `@Bean` methods where typically the return type is the target of the condition. Before the condition on the method applies, the JVM will have loaded the class and potentially processed method references which will fail if the class is not present. To handle this scenario, a separate `@Configuration` class should be used to isolate the …
> Fix java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerExceptionResolver in Spring Boot Servlet mode without WebMVC

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/TransactionOptions.java
- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
- sentry/src/test/java/io/sentry/metrics/MetricsHelperTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/3323
> Update normalization for Metrics

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DataCategory.java
- sentry/src/main/java/io/sentry/clientreport/ClientReportRecorder.java
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
- sentry/src/main/java/io/sentry/util/CollectionUtils.java
- sentry/src/main/java/io/sentry/util/StringUtils.java
- sentry/src/test/java/io/sentry/clientreport/ClientReportTest.kt
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
- sentry/src/test/java/io/sentry/util/CollectionUtilsTest.kt
- sentry/src/test/java/io/sentry/util/StringUtilsTest.kt
add rate limiting to metrics
added metric_bucket data category
Implements https://github.com/getsentry/sentry-java/issues/3292
Unit tests
> Add rate limit to Metrics

- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Executors.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayController.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
A few improvements this PR does:
* Cleans up older replay folders when starting a new one
* Adds deadline of 1 hour for full session recordings
* Adds safe wrappers for executors that handle failures gracefully when submitting or executing tasks
> [SR] Cleanups and session deadline

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryAutoConfiguration.java
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry-spring-jakarta/api/sentry-spring-jakarta.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/tracing/SpringServletTransactionNameProvider.java
- sentry-spring/api/sentry-spring.api
- sentry-spring/src/main/java/io/sentry/spring/tracing/SpringServletTransactionNameProvider.java
HandlerMapping is used by `SpringMvcTransactionNameProvider`. We now provide a fallback `TransactionNameProvider` which uses the `requestURI` as transaction name. This means we're not using the route which contains placeholders for IDs (e.g. `/todo/{id}`) but instead use e.g. `/todo/100`.
Fix-es #1863 (2nd part)
> Fix java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerMapping in Spring Boot Servlet mode without WebMVC

- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayCacheTest.kt
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
* Moves away from using a static height, but rather determine the recording size based on density (use 1x=mdpi for now, which means 2280x1080 will translate to something like 840x400)
* Fixes crashing MediaCodec on some devices, because we were not rounding height and width so they're divisible by 16 (pixel block size, which codecs work on)
* Increases default bitrate because 20k bps is of very low quality (we'll introduce different quality levels in the future, so it's easier for customers to chose from low|medium|high rather than picking arbitrary values)
* Fixes out-of-sync viewHierarchy in some cases by setting it to null immediately so it's not used for a later (maybe irrelevant) screenshot
> [SR] Fix crashing MediaCodec and use density to determine recording resolution

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Executors.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ViewHierarchyNode.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayController.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
* Align naming (sessionReplay instead of sessionReplayOptions)
* Add redactAllText and redactAllImages options
> [SR] Add redact options and align naming

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/IMetricsAggregator.java
- sentry/src/main/java/io/sentry/MetricsAggregator.java
- sentry/src/main/java/io/sentry/metrics/MetricsApi.java
- sentry/src/main/java/io/sentry/metrics/NoopMetricsAggregator.java
- sentry/src/test/java/io/sentry/MetricsAggregatorTest.kt
- sentry/src/test/java/io/sentry/metrics/MetricsApiTest.kt
removed timing from IMetricsAggregator
duration of timing metric of MetricsApi now equals span duration
local metrics aggregator is fetch directly from the span in the timing api
Fixes https://github.com/getsentry/sentry-java/issues/3289 and https://github.com/getsentry/sentry-java/issues/3290
Unit tests
> Fix timing metric value different from span duration

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/protocol/App.java
- sentry/src/test/java/io/sentry/protocol/AppSerializationTest.kt
- sentry/src/test/java/io/sentry/protocol/AppTest.kt
- sentry/src/test/resources/json/app.json
- sentry/src/test/resources/json/contexts.json
- sentry/src/test/resources/json/sentry_base_event.json
- sentry/src/test/resources/json/sentry_base_event_with_null_extra.json
- sentry/src/test/resources/json/sentry_event.json
- sentry/src/test/resources/json/sentry_transaction.json
- sentry/src/test/resources/json/sentry_transaction_legacy_date_format.json
Fixes https://github.com/getsentry/sentry-java/issues/3178
> Add start_type to app context

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/TimeSpan.java
- sentry-android-core/src/test/java/io/sentry/android/core/SpanFrameMetricsCollectorTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/AutomaticSpansTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
performance collectors are called independently from profiling (now transactions get frames measurements)
`TimeSpan.getStartTimestamp` is now a `SentryNanotimeDate`, to fix `FrameMetricsCollector` on app start transactions
`FrameMetricsCollector` checks the start and end timestamp with a difference to a common date. The issue is that using a `SentryLongDate` and a `SentryNanotimeDate` gives different results. We always use `SentryNanotimeDate` on Android, except for app start timestamps, which are then propagated to app start transaction, TTID and TTFD.
Also, `SentryTracer` was not added to the `PerformaceCollectors` when profiling was disabled, due to previous constraints
Added UI test
> Fix Frame measurements in app start transactions

- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/rrweb/RRWebBreadcrumbEvent.java
- sentry/src/test/java/io/sentry/rrweb/RRWebBreadcrumbEventSerializationTest.kt
- sentry/src/test/resources/json/rrweb_breadcrumb_event.json
* Adds RRWebBreadcrumbEvents and transforms our breadcrumbs from the scope to these, filtered by the replay segment timespan
* There's still some things TBD and TODO so will be addressed in follow-up PRs for sure
> [SR] Capture breadcrumbs (temporary)

- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/build.gradle.kts
- sentry-android-replay/src/main/java/io/sentry/android/replay/Recorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayCache.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayCacheTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationWithRecorderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayController.java
- sentry/src/main/java/io/sentry/rrweb/RRWebBreadcrumbEvent.java
* Rework `ReplayIntegration` so it can accept a `Recorder` as a parameter and be used in e.g. Flutter by reusing most parts of the replay logic from the native layer
* Make `ReplayIntegration` testable and add a simple test with a different recorder. This is just a first step to make it testable and cover it with tests
Ivan did
> [SR] Expose public API for flutter

- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayController.java
This PR adds `sendReplay` method which is not depending on the Event class and so can be used by the hybrid SDKs to capture Replay for hybrid errors (JS errors).
- https://github.com/getsentry/sentry-react-native/pull/3714
Tested with the RN Sample app.
> [SR] Add `sendReplay` method for Hybrid SDKs

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SpanDataConvention.java
- sentry/src/main/java/io/sentry/protocol/SentrySpan.java
Attaches the ttid/ttfd contribution flags to all spans within a txn, if the txn contains a ttid/ttfd span. 
Relevant docs PR: https://github.com/getsentry/develop/pull/1250/files
Relevant discussion on Notion: https://www.notion.so/sentry/span-contribution-9b5a0979a81645789db6877593729cf4
Added tests
> Add ttid/ttfd contribution flags

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/MetricsAggregator.java
- sentry/src/main/java/io/sentry/metrics/LocalMetricsAggregator.java
- sentry/src/main/java/io/sentry/metrics/MetricType.java
- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
- sentry/src/main/java/io/sentry/protocol/SentryTransaction.java
- sentry/src/test/java/io/sentry/MetricsAggregatorTest.kt
- sentry/src/test/java/io/sentry/metrics/LocalMetricsAggregatorTest.kt
- sentry/src/test/java/io/sentry/metrics/MetricsHelperTest.kt
- Remove `timestampMs` from `LocalMetricsAggregator`
- put `toStatsdType` in enum directly
- beforeMetric wrapped in try catch
- flush check if there are metrics before scheduling again
Just a small cleanup of the metrics code
> Metrics clean

- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/TimeSpan.java
- sentry-android-core/src/test/java/io/sentry/android/core/SpanFrameMetricsCollectorTest.kt
reverted TimeSpan.getStartTimestamp to SentryLongDate, to not break hybrid sdks
fixed SpanFrameMetricsCollector.realNanos (it now checks the date type and reacts accordingly)
improves https://github.com/getsentry/sentry-java/pull/3382
Hybrid SDKs read the start timestamp of the app start spans as it's the current timestamp (like the `SentryLongDate`).
Reverting this before it gets to hybrid SDKs
> reverted app start span timestamp to SentryLongDate

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/cache/AndroidEnvelopeCache.java
- sentry-android-core/src/test/java/io/sentry/android/core/cache/AndroidEnvelopeCacheTest.kt
* We were using epoch millis for startup time, whereas `CurrentDateProvider` uses uptime millis, therefore we were always writing the crash marker file and always blocking SDK init. This is a regression from when we introduced app start spans
Found out this accidentally while testing
> Do not always write startup crash marker

- .github/workflows/build.yml
Supply a token and use v4 of codecov-action
Without a token codecov API usage may be rate limited. This should prevent it.
> Supply a token for CODECOV and bump to action v4

- CHANGELOG.md
- sentry-graphql/src/main/java/io/sentry/graphql/ExceptionReporter.java
- sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/webflux/AbstractSentryWebFilter.java
- sentry-spring/src/main/java/io/sentry/spring/webflux/SentryWebFilter.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/HubScopesWrapper.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpScopes.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/ScopesAdapter.java
- sentry/src/main/java/io/sentry/Sentry.java
> Add changelog for `8.x` (alpha) release

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry/src/main/java/io/sentry/SentryTracer.java
The return value of `frameMetricsCollector.getLastKnownFrameStartTimeNanos()` was ignored, thus creating large frame delay values.
I also moved data collection post initial `tracer.finish`, ensuring a finish timestamp is set and spans / txns are already trimmed. This is especially useful for idle `ui.load` transactions, as otherwise the frame delay will be longer than the txn duration.
> Fix faulty span.frame_delay calculation for early app start spans

- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/InternalSentrySdk.java
- sentry-android-core/src/test/java/io/sentry/android/core/InternalSentrySdkTest.kt
This PR adds a new method to the HybridSDKs interface which returns serializable app start data including span structures.
This can be used in Flutter (replacing current custom impl), React Native and other hybrid SDKs like Unity, Capacitor and others.
- https://github.com/getsentry/sentry-react-native/issues/3445
unit tests
> Kw/app start span for hybrid SDKs

- CHANGELOG.md
- sentry/src/main/java/io/sentry/ShutdownHookIntegration.java
- sentry/src/test/java/io/sentry/ShutdownHookIntegrationTest.kt
* There was a report from the SDK console (See below), so I've just wrapped the `addShutdownHook` method analogous to what we do when removing the hook
Google Play SDK console yield this crash:
```
Exception java.lang.IllegalStateException: VM already shutting down
at java.lang.Runtime.addShutdownHook (Runtime.java:280)
at io.sentry.ShutdownHookIntegration.register (ShutdownHookIntegration.java:34)
at io.sentry.Sentry.init (Sentry.java:237)
at io.sentry.Sentry.init (Sentry.java:147)
at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:89)
at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:70)
at <private>
at java.lang.reflect.Method.invoke
at <private>
at android.os.Handler.handleCallback (Handler.java:1000)
at android.os.Handler.dispatchMessage …
```
> Do not crash when installing shutdown hook

- CHANGELOG.md
- sentry/src/main/java/io/sentry/MetricsAggregator.java
- sentry/src/test/java/io/sentry/MetricsAggregatorTest.kt
The flush schedule flag wasn't properly reset and thus metrics weren't always sent properly.
Fixes https://github.com/getsentry/sentry-java/issues/3472
Maybe fixes https://github.com/getsentry/sentry-java/issues/3494
Extended unit tests
> Properly reset metric flush flag on metric emission

- CHANGELOG.md
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt
- sentry-android-fragment/src/test/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacksTest.kt
moved fragment auto span finish to onFragmentStarted instead of onFragmentResumed to account for ViewPager2 behaviour
Other options considered, but failed:
* [getUserVisibleHint()](https://developer.android.com/reference/androidx/fragment/app/Fragment.html#getUserVisibleHint()): it's deprecated and returns true for all fragments
* [mMaxState](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/Fragment.java;l=297): only accessible through reflection and returns the current max state achieved (in onFragmentStarted it will be STARTED, while in onFragmentResumed it will be RESUMED
* [isVisible](https://developer.android.com/reference/androidx/fragment/app/Fragment.html#isVisible()): returns true for all fragments …
> Move fragment auto span finish to onFragmentStarted

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidProfilerTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ProfilingTraceData.java
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
added start timestamp in ProfileStartData when a profile starts
added the timestamp in ProfilingTraceData and send it in the json payload
Example of [wrong profile](https://demo.sentry.io/profiling/profile/android/625533174daa4b7b964d8ac08b7ab75b/flamegraph/?colorCoding=by+system+vs+application+frame&fov=0%2C5%2C10353642496%2C13&query=&sorting=call+order&tid=8734&view=top+down) (before)
Example of [correct profile](https://sentry-sdks.sentry.io/profiling/profile/sentry-android/dc544fbc9c4b496a88ec4b62cfe0a3e0/flamegraph/?colorCoding=by+system+vs+application+frame&fov=0%2C0%2C2867905792%2C19&query=&sorting=call+order&tid=8998&view=top+down) (after)
Profiles are a not aligned to spans, especially when we change the transaction start timestamp. In that case, it is assumed that the profile …
> Add timestamp when a profile starts

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SpanFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/main/java/io/sentry/Span.java
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/SpanTest.kt
moved span and transaction finish callback before they are actually finished
Closes https://github.com/getsentry/sentry-java/issues/3228
This fixes and aligns the behaviour among spans and transactions.
Unit tests
> Move onFinishCallback before span or transaction is finished

- sentry-android-core/proguard-rules.pro
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/DefaultReplayBreadcrumbConverter.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/DefaultReplayBreadcrumbConverterTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/NoOpReplayBreadcrumbConverter.java
- sentry/src/main/java/io/sentry/NoOpReplayController.java
- sentry/src/main/java/io/sentry/ReplayBreadcrumbConverter.java
- sentry/src/main/java/io/sentry/ReplayController.java
* Extract breadcrumb conversion to a separate class, so the hybrid SDKs can override the logic
* Also make the default converter public and open, so others can delegate to it to do the conversion for some categories
> [SR] Allow RRWeb breadcrumb customization from hybrid SDKs

- CHANGELOG.md
- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
In order to not get flagged by security scanners we should use `SecureRandom` in favor of `Random`. Whilst the use-case (random flush shift) doesn't really require a strong random, I guess it's maintenance-friendlier to use `SecureRandom`.
Fixes https://github.com/getsentry/sentry-react-native/issues/3897
> Use SecureRandom instead of Random for Metrics

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java
- sentry/src/test/java/io/sentry/UncaughtExceptionHandlerIntegrationTest.kt
Upon registration check if an `UncaughtExceptionHandlerIntegration` is already set as `defaultUncaughtExceptionHandler`, if so, set its `defaultExceptionHandler` as the default of the new `UncaughtExceptionHandlerIntegration`. 
Fixes #3266
> Fix UncaughtExceptionHandlerIntegration Memory Leak

- CHANGELOG.md
> POTEL 22 - Improve Changelog

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/3503
> Fix duplicate session start for React Native

- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
Use `auto.opentelemetry` for POTel span origin
So we can better distinguish it from our legacy OpenTelemetry integration.
> POTEL 28 - Use `auto.opentelemetry` for POTel span origin

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
- Remove sentry-native submodule again
- Ignore a failing test, we'll revisit this for the next release
Seems to have resurfaced due to auto merge bringing it back. It was removed in https://github.com/getsentry/sentry-java/pull/3189/files#diff-359faa0e4a4584b6ac04835e8df52961f6b7b2eb4ba0962c5ac5c2b4ef45832c
> Remove sentry-native submodule again; ignore failing test

- CHANGELOG.md
- sentry-android-okhttp/build.gradle.kts
- sentry-android-okhttp/proguard-rules.pro
- sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpEventListenerTest.kt
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEventListener.kt
SentryOkHttpEventListener now checks if an existing `io.sentry.android.SentryOkHttpEventListener` is attached and skips it
Customers reported duplicated http spans, that was happening due to our Gradle plugin auto instrument using the old version of the `SentryOkHttpEventListener` from the `sentry-android-okhttp` artifact. 
That was delegating to the listener from `sentry-okhttp`, and when being instrumented multiple times, it was creating multiple http spans, overwriting the parent `http.client` span in the listener, causing the duplicated spans to never finish, due to their reference being lost.
Unit test
> Fix duplicated http spans

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DataCategory.java
- sentry/src/main/java/io/sentry/Hub.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/clientreport/ClientReportRecorder.java
- sentry/src/main/java/io/sentry/clientreport/IClientReportRecorder.java
- sentry/src/main/java/io/sentry/clientreport/NoOpClientReportRecorder.java
- sentry/src/test/java/io/sentry/HubTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/clientreport/ClientReportTest.kt
added span data category for client reports
added dropped span report when recording lostEnvelopeItem added dropped span report on beforeSend and eventProcessor filtering (SentryClient) and backpressure and sampleRate (Hub)
Closes https://github.com/getsentry/sentry-java/issues/3527
Unit tests
> Report dropped spans

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
We now parse and use `send-default-pii` and `max-request-body-size` from `sentry.properties`.
- `max-request-body-size` was already being parsed but never applied to `SentryOptions`
- `send-default-pii` was neither parsed nor applied
As of `8.0.0-alpha.2` our Sentry OpenTelemetry Java Agent has been released and is supposed to be a vital part in our future Performance instrumentation. Some features (e.g. error reporting) are currently still based on the integrations that existed before.
Some data is only sent when certain options are enabled (see PR title). We never parsed those until now, meaning our OpenTelemetry Agent Init wasn't able to utilize all of the functionality Sentry offers.
NOTE: There might be more options, that aren't parsed yet. We should investigate and fix. Here's an …
> Parse and use `send-default-pii` and `max-request-body-size` from `sentry.properties`

- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt
- sentry-android-navigation/src/main/java/io/sentry/android/navigation/SentryNavigationListener.kt
- sentry-android-navigation/src/test/java/io/sentry/android/navigation/SentryNavigationListenerTest.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryOptions.java
* Adds an option to disable screen tracking - this is necessary for RN/Flutter, so they can set their own screens to the native scope and we won't override them
* Adds screen tracking to the missing places (fragment and navigation integrations) to match what we capture as navigation breadcrumbs for replay
* Fills in `replay.urls` array based on navigation breadcrumbs
* For the buffer mode: we have to know what was the last screen before the buffer replay started to display the correct screen name. For that we:
* Install ScopeObserver to observe whenever `scope.screen` changes and persist it with timestamp
* When capturing the buffered replay we then search for the last screen before the buffered replay started and add it to the `replay.urls` array
Part of …
> [SR]  Capture screen names as urls 

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
Invert `isSpanTooOld` check so spans that haven't been sent to Sentry yet survive until the next invocation of `SpanExporter.export`.
When spans belonging to a single transaction were split into multiple batches for `SpanExporter`, we did not add all spans because the `isSpanTooOld` check wasn't inverted.
> Support spans that are split into multiple batches

- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
* Fixes out-of-sync redaction (hopefully) for good:
* We now listen for the screenshot result on the same (=main) thread, and only capture the view hierarchy after the fact, so in theory there should be no new `onDraw` call in between  
* However, if there was a `onDraw` call in between, we say that the view hierarchy is invalid and drop the frame (which should never happen)
* Switched `postAtFrontQueue` to `post` as we don't need the front queue anymore
* Additionally made an perf improvement to capture the screenshot of the target (scaled) size, which should be faster
* For that we also had to adjust how we calculate the dominant color for images, by applying the prescaled matrix to the image's visibleRect before drawing it to the single-pixel bitmap
Part of …
> [SR] Redaction fixes pt. 2

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ViewHierarchyNode.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
This adds option to redact any java class selected by users. 
This can be also used by React Native to redact SVGs.
- https://github.com/getsentry/sentry-react-native/pull/3930
rn sample app
> [SR] Add `redactClasses` option

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
Fallback to otelspan name as transaction description if sentry span description is null
Avoid having `<unlabeled transaction>` as label in sentry.
> POTEL 35 - Use OtelSpan name as fallback for transaction name

- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Views.kt
* Our `isObscured` was falsely returning `true` for many views in the test app (BlueSky), still not sure if it's purely RN issue or may also happen on Android. For now I've just commented out, as the gains are not that high, compared to losses, gonna figure it out later
* Fixed a small bug when we were not redacting text lines containing emojis - for some reason `lineEnd` was returning 0, so we fix it by getting the pixel offset of the second-to-last character and then adding 1 pixel to it (not exactly correct, as we should consider resolution/density, but I think it will cover most cases)
Closes #3558 
Closes #3559 
@krystofwoldrich you can check this replay and compare with your runs https://sentry-sdks.sentry.io/replays/a34a01679f7e4d43b80f7c46d36ea7a1/ it should have …
> [SR] Redaction fixes for RN

- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
* Fixes small bug when there were no nav breadcrumb, we were trying to access an empty list
* Add an if-check and avoid capturing frames when offline in session mode
Part of https://github.com/getsentry/sentry/issues/70065
> [SR] Add stopgap for offline session recording

- CHANGELOG.md
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEventListener.kt
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpInterceptor.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpEventListenerTest.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpEventTest.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpInterceptorTest.kt
SentryOkHttpEvent now set data instead of creating child spans
renamed constants to make them nicer in the UI
SentryOkHttpInterceptor now closes the listener call
[Before](https://sentry-sdks.sentry.io/performance/trace/9e4523f514dd49cf8e6902a3de94af25/?node=span-080479a614234019&node=txn-4f56a4eb30da4150ac7d0818e99a10fb&project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=14d&timestamp=1719498761&transaction=SecondActivity&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
[After](https://sentry-sdks.sentry.io/performance/trace/d8e2db038c254758b419da8a57c3ecb7/?node=span-6eb58507b1fa4033&node=txn-6ec8c14919854bcb822eb364d7201a76&project=5428559&query=&referrer=performance-transaction-summary&showTra …
> Change OkHttp sub-spans to span attributes

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/test/java/io/sentry/SentryTest.kt
added a check in Sentry.init to check the options against the SentryAndroidOptions when using Android
We want to avoid people on Android calling Sentry.init directly, instead of SentryAndroid.init.
Closes https://github.com/getsentry/sentry-java/issues/3440
Unit tests
> throw when calling Sentry.init on Android

- CHANGELOG.md
- sentry-android-sqlite/src/main/java/io/sentry/android/sqlite/SQLiteSpanManager.kt
- sentry-android-sqlite/src/main/java/io/sentry/android/sqlite/SentryCrossProcessCursor.kt
- sentry-android-sqlite/src/test/java/io/sentry/android/sqlite/SQLiteSpanManagerTest.kt
- sentry-android-sqlite/src/test/java/io/sentry/android/sqlite/SentryCrossProcessCursorTest.kt
added SentryCrossProcessCursor wrapper
SQLiteSpanManager now wraps CrossProcessCursors to start a span only when the cursor is filled with data
[Before](https://sentry-sdks.sentry.io/performance/trace/da0a8c7da0cd4d7783855dfdf23bab77/?node=span-2767ff9a333f425c&node=txn-4fac448451464ab0976a76d25f2c1508&project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=1h&timestamp=1721897865&transaction=MainActivity&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
[After](https://sentry-sdks.sentry.io/performance/trace/6183d0a92c274da2b0cd37ee4207b34a/?node=span-571334cc22984ffd&node=txn-6ae3201d217d4481ba8082b2decafab2&project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&sourc …
> Fix lazy select queries instrumentation

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
Pixel devices were missing app start spans.
We post a task on the main thread on Application creation and register a callback on activity creation to check if an activity has been created right after the application is created.
This works fine, unless running on Pixel devices, where the task posted on the main thread in application creation is called before the Activity.onCreate().
So we are now posting a task to post another task to check the activity creation, meaning we post it twice. This seems to work fine on Pixel devices from our tests
Closes https://github.com/getsentry/sentry-java/issues/3608
> Fix app start spans missing from Pixel devices

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
Add all OTEL attributes to span data
> POTEL 37 add otel attributes to span data

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/api/sentry-opentelemetry-core.api
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OtelSpanInfo.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
We're copying all of attribues as of (https://github.com/getsentry/sentry-java/pull/3593). This means we no longer need to selectively copy some of them.
Remove unnecessary code.
> POTEL 37b - No longer selectively copy OTel span attributes

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/AnrWithReplayIntegrationTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplaySmokeTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/capture/BufferCaptureStrategyTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
- sentry/src/test/java/io/sentry/SentryTest.kt
To better reflect and align with web replays, we've changed it to `onErrorSampleRate`
Closes #3616
> [SR] Rename errorSampleRate to onErrorSampleRate

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java
Also fixes a bug where `isTraceSampling` was used instead of `isTracingEnabled`.
> POTEL 39 - Use RECORD_ONLY sampling decision if performance is disabled

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
- sentry-android-core/src/test/java/io/sentry/android/core/performance/AppStartMetricsTest.kt
AppStartMetrics stops appStartProfiler only if no activity ever started
We were always stopping appStartProfiler after application creation.
Not a real issue, as the profiler should already be detatched from AppStartMetrics at that point.
Unit test
> Avoid stopping appStartProfiler after application creation

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Views.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ViewHierarchyNode.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/util/TextViewDominantColorTest.kt
* RN always uses Spannables to apply/change the text color, so we just iterate over the spans and pick the longest one to determine the dominant color, if the text is `Spanned`, otherwise fall back to `currentTextColor`
Results on RN:
Part of https://github.com/getsentry/sentry/issues/74441
> [SR] Detect dominant color for TextViews with Spans

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryItemType.java
- sentry/src/test/java/io/sentry/protocol/SentryItemTypeSerializationTest.kt
Adds the `feedback` envelope header item type
Feedback envelope items are just regular envelope items, with additional context data and support for attachments.
Currently we are implementing this on flutter, and android is the only platform missing, as the type is lost from the envelope sent to the native sdk from the flutter side.
Relates to https://github.com/getsentry/sentry-dart/pull/2230#issuecomment-2341262726
Added unit tests.
> Add support for `feedback` envelope header item type

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2Integration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/ContextUtils.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/DeviceInfoUtil.java
- sentry-android-core/src/main/java/io/sentry/android/core/NetworkBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/debugmeta/AssetsDebugMetaLoader.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/modules/AssetsModulesLoader.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/AndroidConnectionStatusProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/SentryFrameMetricsCollector.java
- sentry-android-core/src/test/java/io/sentry/android/core/ContextUtilsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/BaseUiTest.kt
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
- sentry-android-integration-tests/sentry-uitest-android/src/main/res/values/values.xml
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Context.kt
Ensures https://github.com/getsentry/sentry-java/issues/3658 will not happen again.
`LeakAssertions.assertNoLeaks()` FTW
> Ensure app context is used even when SDK is initialized via Activity Context

- CHANGELOG.md
- sentry-spring-boot-jakarta/api/sentry-spring-boot-jakarta.api
- sentry-spring-boot/api/sentry-spring-boot.api
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentrySpringFilter.java
- sentry-spring-jakarta/src/test/kotlin/io/sentry/spring/jakarta/SentrySpringFilterTest.kt
- sentry-spring/src/main/java/io/sentry/spring/SentrySpringFilter.java
- sentry-spring/src/test/kotlin/io/sentry/spring/SentrySpringFilterTest.kt
> Attach request body for `application/x-www-form-urlencoded` requests in Spring

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-samples/sentry-samples-android/build.gradle.kts
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
- sentry/src/main/java/io/sentry/cache/CacheStrategy.java
- sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
- sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java
- sentry/src/main/java/io/sentry/util/LazyEvaluator.java
- sentry/src/test/java/io/sentry/SentryReplayOptionsTest.kt
- sentry/src/test/java/io/sentry/cache/CacheStrategyTest.kt
There are members that we eagerly initialize, but we actually don't need them, so we can only init them when accessing for the first time:
* JsonSerializer
* EnvelopeReader
* DateProvider
Additionally, `AtomicClientReportStorage` was showing big numbers, so I made the lostEventCounts map a lazy one.
Closes #2541 
Manually, existing tests should cover this
> [QA] Lazily load SentryOptions members

- CHANGELOG.md
- sentry-android-replay/proguard-rules.pro
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
* Mask more things by default: WebViews, VideoViews, and androidx PlayerViews
* Reverted key_frame interval to 10s, because I realized for buffered replays (which are 30sec), the quality becomes garbage without having key_frames at all. 10s seems like a good middle-ground for low size but decent quality videos.
Manually on the pocketcasts app
> [SR] Mask web and video views

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Sampling.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/capture/BufferCaptureStrategyTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/TracesSampler.java
- sentry/src/main/java/io/sentry/cache/PersistingScopeObserver.java
- sentry/src/main/java/io/sentry/metrics/MetricsHelper.java
- sentry/src/main/java/io/sentry/util/Random.java
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
We were using `SecureRandom` due to a reported issue in https://github.com/getsentry/sentry-java/issues/1830 that the usage of `java.util.Random` gets flagged by security tools. However, we don't really benefit from `SecureRandom` since we don't generate passwords or anything like that. 
So we just vendor a simplified version of `java.util.Random` to prevent it from getting flagged, and it's much faster.
> [QA] Replace SecureRandom with vendored Random

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidLogger.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
* There are some benchmarks in [here](https://stackoverflow.com/questions/513600/should-i-use-javas-string-format-if-performance-is-important) comparing `String.format` vs plus-operator, and `String.format` is indeed slower.
* Since we're doing some logging on startup (e.g. when parsing the manifest), even when `debug` is set to `false`, this was adding some overhead. I've removed the redundant log call + add changed `String.format` usages to the plus operator
* We were doing unnecessary `String.format` even when there are no args passed, so we check for their presence now and call the method without `String.format` explicitly now
> [QA] Make logging faster on startup

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2Integration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/NetworkBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/ScreenshotEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/SendCachedEnvelopeIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/UserInteractionIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/ViewHierarchyEventProcessor.java
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/FragmentLifecycleIntegration.kt
- sentry-android-navigation/src/main/java/io/sentry/android/navigation/SentryNavigationListener.kt
- sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberIntegration.kt
- sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpInterceptor.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegration.java
- sentry/src/main/java/io/sentry/ShutdownHookIntegration.java
- sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java
- sentry/src/main/java/io/sentry/util/IntegrationUtils.java
Profiling showed that there's quite some time spent on adding integrations to the sdk version, probably due to string manipulation and reflection for class name, so I've just dropped this entirely in favour of hardcoding integration names as-is.
It's gone completely, we just add directly to the sdk version
> [QA] Hardcode integration names

- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
> Fix ANRv2 test flakyness

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/DefaultReplayBreadcrumbConverter.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ComposeViewHierarchyNode.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ViewHierarchyNode.kt
* There are some things we were eagerly initializing for replay that we actually don't need (and only use them on a bg thread, so this should be a good improvement)
* Use `Class.getName` instead of `Class.getCanonicalName` as seems like the latter is quite a bit slower due to checks for class locality/anonymity which goes into the native layer. Maybe an outlier, but they are essentially the same thing except a couple of cases, so I think it's fine to use it here
* Get rid of unnecessary `positionInWindow` call as we already get the coords via `boundsInWindow` anyway
* Get rid of `runInBackground` init call as it wouldn't do anything because ReplayCache is null at that point anyway
Existing tests should cover it
> [QA] Make replay lazy and faster

- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpInterceptor.kt
Update the documented default value for `captureFailedRequests` to match the actual default value in code.
Looks like you forgot to update the docs when you flipped the default in 7.1.0 😅 
🫣
> docs(okhttp): update documented default value to match actual

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/DsnUtil.java
- sentry/src/main/java/io/sentry/RequestDetailsResolver.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/util/LazyEvaluator.java
- sentry/src/test/java/io/sentry/util/LazyEvaluatorTest.kt
We parse the dsn multiple times in the app lifecycle, and most of the times on the main thread. We can parse it once and cache its result
> [QA] Cache parsed Dsn

- CHANGELOG.md
- sentry-android-fragment/api/sentry-android-fragment.api
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/FragmentLifecycleIntegration.kt
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/FragmentLifecycleState.kt
- sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt
- sentry-android-fragment/src/test/java/io/sentry/android/fragment/FragmentLifecycleStateTest.kt
- sentry-android-fragment/src/test/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacksTest.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/DefaultReplayBreadcrumbConverter.kt
replaced kotlin setOf() with HashSet<>() + add() calls
setOf() was taking ~10ms to run, while instantiating an HashSet and then calling add multiple times is almost instantaneous - at least in debug builds
Unit test
> [QA] Replace setOf with HashSet.add

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
Lazy fields in SentryOptions are now loaded on init in the background
Instead of loading the options fields backed by LazyEvaluator when needed, we do it in the background as soon as we can. When the SDK will need these fields, they will be already cached and ready to use
This improved init() by ~5-15ms in profileable builds
> [QA] Load lazy fields on init in the background

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
`globalHubMode` used to only be a param on `Sentry.init`. To make it easier to be used in e.g. Desktop environments, we now additionally added it as an option on `SentryOptions` that can also be set via `sentry.properties`.
We can consider deprecating and removing the `Sentry.init` overloads that have the `globalHubMode` parameter.
If both the param on `Sentry.init` and the option are set, the option will win. By default the option is set to `null` meaning whatever is passed to `Sentry.init` wins.
Fixes #3779
> Add `globalHubMode` to options

- CHANGELOG.md
> Prepare Changelog for 7.16.0 release

- .github/workflows/codeql-analysis.yml
With 8.x we won't have sentry-native as a submodule anymore, thus there's no need to run cpp codeql.
> Update CodeQL for sentry-java 8.x

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
ManifestMetadataReader now accepts integers other than floats
Fixes https://github.com/getsentry/sentry-java/issues/3603
Unit test
> Accept manifest integer values when requiring floating values

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/TracesSampler.java
- sentry/src/main/java/io/sentry/util/SentryRandom.java
- sentry/src/test/java/io/sentry/util/SentryRandomTest.kt
Instead of using `Random` directly, we now go through `SentryRandom.current()` which keeps one instance per thread. While there's still some synchronization overhead when compared to `ThreadLocalRandom` it still performs much better than using `Random` from multiple threads directly.
We've found reduced performance when using `Random` from multiple threads. While it's thead-safe, it slows down significantly. It'd be even better to use `ThreadLocalRandom` instead, since it has even better performance but we'd risk being flagged in security audits again (`Random` vs. `SecureRandom`).
See https://github.com/getsentry/sentry-java/pull/3818#issuecomment-2445034392 for more details on performance test results.
Vendoring `ThreadLocalRandom` (like we did with `Random`) doesn't seem possible as …
> Use `Random` through `ThreadLocal<Random>`

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry/src/main/java/io/sentry/DisabledQueue.java
- sentry/src/main/java/io/sentry/Scope.java
- sentry/src/test/java/io/sentry/DisabledQueueTest.kt
- sentry/src/test/java/io/sentry/ScopeTest.kt
Previously, when MaxBreadcrumbs was set to 0, the app would crash since the CircularQueue implementation must have a size higher than 0.
With that, I made a `disabledqueue` that behaves similarly like `CircularQueue` do, with the difference that any items inserted into it will be ignored. 
I was also surprised to see that max breadcrumbs wasn't exposed on the metadata, so I also exposed it on this PR to make tests with the sample easier.
To fix
https://github.com/getsentry/sentry-react-native/issues/3634
and
https://github.com/getsentry/sentry-java/issues/3313
Unit tests and running the sample app with max breadcrumbs set to 0 and 100.
> Fix: Allow MaxBreadcrumb 0  / Expose MaxBreadcrumb metadata.

- .github/workflows/agp-matrix.yml
CI runs recently started to fail due to disk size issues when creating the emulator:
>  ERROR        | Not enough space to create userdata partition. Available: 7329.925781 MB at /home/runner/.android/avd/../avd/test.avd, need 7372.800000 MB.
This PR sets the disk size to 4096M which should be large enough for our tests.
> Limit emulator size to 4096M

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/DsnUtil.java
- sentry/src/main/java/io/sentry/RequestDetailsResolver.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
Rename `getParsedDsn()` to `retrieveParsedDsn()` to fix issue with `JNDI` property binding.
This caused `getParsedDsn()` to be called prematurely and lead to crashes with an emtpy `Dsn`.
Fixes #3825
> Fix standalone tomcat jndi issue

- sentry-spring-boot/build.gradle.kts
- sentry-spring-boot/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/it/SentrySpringIntegrationTest.kt
- sentry-spring/api/sentry-spring.api
- sentry-spring/build.gradle.kts
- sentry-spring/src/main/java/io/sentry/spring/opentelemetry/SentryOpenTelemetryAgentWithoutAutoInitConfiguration.java
- sentry-spring/src/main/java/io/sentry/spring/opentelemetry/SentryOpenTelemetryNoAgentConfiguration.java
Port Spring Boot 3 OpenTelemetry changes to Spring Boot 2
> POTEL 56 - Port Spring Boot 3 OpenTelemetry changes to Spring Boot 2

- .github/workflows/agp-matrix.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/enforce-license-compliance.yml
- .github/workflows/generate-javadocs.yml
- .github/workflows/integration-tests-benchmarks.yml
- .github/workflows/integration-tests-ui-critical.yml
- .github/workflows/integration-tests-ui.yml
- .github/workflows/release-build.yml
- .github/workflows/system-tests-backend.yml
- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/DisabledQueue.java
- sentry/src/main/java/io/sentry/DsnUtil.java
- sentry/src/main/java/io/sentry/RequestDetailsResolver.java
- sentry/src/main/java/io/sentry/Scope.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/DisabledQueueTest.kt
- sentry/src/test/java/io/sentry/ScopeTest.kt
> Merge `main` into `8.x.x` (latest release `7.17.0`)

- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
Closes https://github.com/getsentry/sentry-java/issues/3872
> re-enable flaky test

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
We were not swallowing exceptions in case the user options config throws on Android, therefore everything that comes after that (event processors and a bunch of other stuff) were not added and executed at all.
Internal customer report
> Ensure android initialization process continues even if options configuration block throws an exception

- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/README.md
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry/README.md
- sentry-samples/sentry-samples-spring-boot-opentelemetry/build.gradle.kts
Adds new gradle task `bootRunWithAgent` to our spring boot opentelemetry samples.
Implements #3880
> Add gradle task to start spring boot samples with agent

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySpanExporter.java
Closes https://github.com/getsentry/sentry-java/issues/3901
> Send `otel.kind` to Sentry

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
Disabled auto `op` generation based on span kind. We only do it if it's something other than `INTERNAL`.
Solution 5b from https://github.com/getsentry/sentry-java/issues/3904
> Do not replace `op` with auto generated content for OpenTelemetry spans with span kind`INTERNAL`

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- scripts/update-sentry-native-ndk.sh
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
- sentry-samples/sentry-samples-android/build.gradle.kts
Re-applies the NDK optimizations done on the 7.x.x branch: https://github.com/getsentry/sentry-java/blob/3d24791bd1b80d3dbf8a849d9f23bf14445902c9/sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
As some of the optimization code lies with `sentry-native` now, a version bump of `sentry-native-ndk` is required as well.
No degration in NDK init performance for 8.x.x
Manually double checked 16kb alignment using the official [check_elf_alignment.sh script
](https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh)
````shell
./check_elf_alignment.sh sentry-samples-android-debug.apk
Recursively analyzing sentry-samples-android-debug.apk
NOTICE: Zip alignment check requires build-tools version 35.0.0-rc3 or higher.
You can …
```
> Re-apply NDK init performance improvements for 8.x.x

- CHANGELOG.md
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
- `UncaughtExceptionHandlerIntegration.uncaughtException` waits the full 15s after capturing an event and calling `hint.waitFlush()` when rate limited since we never called `markFlushed` in `RateLimiter`.
Fixes https://github.com/getsentry/sentry-java/issues/3857
> Mark hint flushed when rate limited

- CHANGELOG.md
- sentry/src/main/java/io/sentry/instrumentation/file/FileIOSpanManager.java
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileInputStreamTest.kt
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileOutputStreamTest.kt
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileReaderTest.kt
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileWriterTest.kt
file span description is now masked if isSendDefaultPii is false
file path on Android is sent only if isSendDefaultPii is true
Closes https://github.com/getsentry/sentry-java/issues/3324
Unit tests
> Send file name and path only if isSendDefaultPii is true

- README.md
> add talk on session replay to readme

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry-noagent/build.gradle.kts
Bump OpenTelemetry SDK to `1.44.1`, OpenTelemetry instrumentation to `2.10.0` and OpenTelemetry semantic conventions to `1.28.0`
> POTEL 59 - Bump OpenTelemetry

- sentry/src/main/java/io/sentry/DisabledQueue.java
- sentry/src/test/java/io/sentry/DisabledQueueTest.kt
DisabledQueue.isEmpty now returns true
This isn't really used anywhere, but it's conceptually correct for the `DisabledQueue` to return true on `isEmpty()`
Left from [another PR](https://github.com/getsentry/sentry-java/pull/3836#discussion_r1839687988)
Unit test
> DisabledQueue.isEmpty now returns true

- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidContinuousProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidContinuousProfilerTest.kt
- sentry-opentelemetry/sentry-opentelemetry-bootstrap/api/sentry-opentelemetry-bootstrap.api
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DataCategory.java
- sentry/src/main/java/io/sentry/clientreport/ClientReportRecorder.java
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
continuous profiler now doesn't start if offline or rate limited
continuous profiler stops when rate limited
continuous profiler prevents sending chunks after being closed
added profile_chunk rate limit
Implements rate limit for Continuous Profiling
Part 6 of https://github.com/getsentry/sentry-java/pull/3710
> Add rate limit for Continuous Profiling v8 (p6)

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/Windows.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/gestures/GestureRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Views.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplaySmokeTest.kt
- Fix `IndexOutOfBoundsException` when tracking window changes. The problem here was that we had an `object RootViewSpy`, and it was shared between different instances of the ReplayIntegration, hence messing up things.
- Fix `IllegalStateException` when adding/removing draw listener for a dead view
- Fix `ConcurrentModificationException` when registering window listeners and stopping `WindowRecorder`/`GestureRecorder`
- Fix some TODOs in Windows.kt
Closes https://github.com/getsentry/sentry-java/issues/3859
Closes https://github.com/getsentry/sentry-react-native/issues/4234
> [SR] Fix various crashes

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
changed TTFD timeout to 25 seconds, to avoid competing with transaction's timeout
Sometimes the timeout of the TTFD span compete with the timeout of the transaction, being both at 30 seconds
Fixes https://github.com/getsentry/sentry-java/issues/3831
> Change TTFD timeout to 25 seconds

- .github/workflows/agp-matrix.yml
- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/proguard-rules.pro
- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/ReplayTest.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Nodes.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/viewhierarchy/ComposeViewHierarchyNode.kt
Use `WeakReference` to store root coordinates and add a test for leaks in replay
Closes #3915 
> [SR] Fix memory leak in Compose masking 

- .craft.yml
- .github/ISSUE_TEMPLATE/bug_report_java.yml
- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-agentless/README.md
- sentry-opentelemetry/sentry-opentelemetry-agentless/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-agentless/src/main/java/io/sentry/opentelemetry/agent/AgentlessMarker.java
- sentry-samples/sentry-samples-console-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-console-opentelemetry-noagent/src/main/java/io/sentry/samples/console/Main.java
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry-noagent/build.gradle.kts
- settings.gradle.kts
Add `sentry-opentelemetry-agentless` module that customers can add as a single dependency to use our OpenTelemetry offering instead of having to add multiple dependencies and manage versions.
Closes https://github.com/getsentry/sentry-java/issues/3913
- Consider `agentless-spring-boot` that pulls in `opentelemetry-spring-boot-starter` with the required version
- Consider creating a BOM, that also drags in the OTel BOM to manage Sentry + OTel versions
- Update README
> POTEL 64 - `sentry-opentelemetry-agentless` module

- CHANGELOG.md
- sentry-graphql-22/api/sentry-graphql-22.api
- sentry-graphql-22/src/main/java/io/sentry/graphql22/SentryInstrumentation.java
Replace deprecated `SimpleInstrumentation` with `SimplePerformantInstrumentation` in `sentry-graphql-22`.
Fixes #3968
> graphql 22 update instrumentation

- sentry-opentelemetry/sentry-opentelemetry-agentless-spring/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-agentless/build.gradle.kts
Change api to implementation for dependency of agentless modules on bootstrap
> POTEL 72 - Change api to implementation for dependency of agentless modules on bootstrap

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/gestures/ReplayGestureConverter.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Executors.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Persistable.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationWithRecorderTest.kt
* Switch touch events from `LinkedList` with a lock to `ConcurrentLinkedDeque` which suits this case better. Iterators of this deque are [weakly consistent](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html), which means it's possible another thread will add new touch events while we're iterating but this is fine for us, because we filter them out based on timestamp upon sending, so the newly-added touch events won't make it to the current segment, but to the next one.
* Get rid of storing touch events to disk (for now), because it was overloading cpu a lot, and we only need them for the last segment in case of an ANR or Crash. iOS is currently not storing them either, so I think it's fine. But we should do it eventually, after we have proper disk …
> [SR] Fix ANRs and speed up

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/PerformanceAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/TimeSpan.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/performance/AppStartMetricsTest.kt
* ActivityLifecycleIntegration:
- creates `onCreate` and `onStart` TimeSpans
- set app start type to warm in AppStartMetrics when needed
* AppStartMetrics has now a method to restart appStartSpan and reset its uptime_ms
* PerformanceAndroidEventProcessor now attaches activity start spans to warm starts, too
* SentryPerformanceProvider doesn't create spans anymore
Confirm warm starts are registered for background starts (BroadcastReceiver)
Cold start:
Open second Activity:
Reopen first Activity without closing app:
Open first Activity after close app with `Don't keep activity` developer option enabled:
Fixes https://github.com/getsentry/sentry-java/issues/3896
Relates and possibly fixes https://github.com/getsentry/sentry-java/issues/3899
In a [followup …
> Warm start detection

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryAppStartProfilingOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/TracesSampler.java
- sentry/src/main/java/io/sentry/util/SampleRateUtils.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
- sentry/src/test/java/io/sentry/ScopesTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
- sentry/src/test/java/io/sentry/util/SampleRateUtilTest.kt
added SentryOptions.continuousProfilesSampleRate
now continuous profiling is disabled if continuousProfilesSampleRate is 0
profiles directory is created when continuous profiling is enabled, too
continuous profiling decision is passed to SentryAppStartProfilingOptions
app start continuous profiling is sampled, too
Add sample rate to continuous profiling
Part 7 of https://github.com/getsentry/sentry-java/pull/3710
Unit test
> added SentryOptions.continuousProfilesSampleRate

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryWebfluxAutoConfiguration.java
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryWebfluxAutoConfigurationTest.kt
Change default for `sentry.reactive.thread-local-accessor-enabled` when the property is missing to use `ThreadLocalAccessor` by default.
Closes https://github.com/getsentry/sentry-java/issues/4020
> Enable `ThreadLocalAccessor` for Spring Boot 3 WebFlux by default

- .github/workflows/codeql-analysis.yml
- sentry-android-core/src/test/java/io/sentry/android/core/performance/ActivityLifecycleSpanHelperTest.kt
Fix `ActivityLifecycleSpanHelperTest` by resetting `AppStartMetrics`
> Fix `ActivityLifecycleSpanHelperTest` by resetting `AppStartMetrics`

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryClient.java
Make `SentryClient` constructor public
So we can support https://docs.sentry.io/platforms/android/configuration/shared-environments/ for v8
> Make `SentryClient` constructor public

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/UserInteractionIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/AndroidViewGestureTargetLocator.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/ViewUtils.java
- sentry-android-core/src/test/java/io/sentry/android/core/UserInteractionIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/internal/gestures/SentryGestureListenerClickTest.kt
- sentry-compose-helper/src/jvmMain/java/io/sentry/compose/gestures/ComposeGestureTargetLocator.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/instrumentation/file/SentryFileInputStream.java
- sentry/src/main/java/io/sentry/instrumentation/file/SentryFileOutputStream.java
- sentry/src/main/java/io/sentry/internal/gestures/GestureTargetLocator.java
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileInputStreamTest.kt
- sentry/src/test/java/io/sentry/instrumentation/file/SentryFileOutputStreamTest.kt
Here are just some preventive measure that will make less code/instructions to run on the main thread:
- Safety check for the `Window.Callback` to not be a `SentryWindowCallback` already to prevent multiple callbacks running simultaneously
- Get rid of `requireNonNull` calls as they are redundant (we do `instanceof` checks later on anyway)
- Check if tracing is enabled before instrumenting File I/O streams, because otherwise they go into the void anyway
- Speed up ViewUtils.findTarget method by avoiding ViewGroup children traversal if the touch was not within the ViewGroup bounds
Internal customer discussions
> Various fixes to instrumentations running on the main thread

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryExceptionFactory.java
- sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt
Do not set the exception group marker (`"is_exception_group": true,`) when there is a suppressed exception.
Fixes https://github.com/getsentry/sentry-java/issues/4054 but also removes the list of exceptions from the top of the issue detail page. We can fix that at a later point.
> Do not set the exception group marker when there is a suppressed exception

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry/src/main/java/io/sentry/MainEventProcessor.java
- sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/4068
> Only send {{auto}} ip-adress if sendDefaultPii is enabled (8.x.x)

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AnrV2EventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrV2EventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry/src/main/java/io/sentry/MainEventProcessor.java
- sentry/src/test/java/io/sentry/MainEventProcessorTest.kt
Fixes https://github.com/getsentry/sentry-java/issues/4068
> Only send {{auto}} ip-adress if sendDefaultPii is enabled (7.x.x)

- CHANGELOG.md
> Merge v8 pre-release changelogs into one `8.0.0` changelog

- CHANGELOG.md
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
Restores the same behaviour we had in 7.x.x: 
https://github.com/getsentry/sentry-java/blob/1e796d816d8218e33084e02800c7485dcdd5b722/sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java#L29-L32
> Fix swallow NDK loadLibrary errors

- .craft.yml
Add modules that are new in v8 to `.craft.yml`
So registry is updated automatically on every release after `8.0.0`.
> Add modules that are new in v8 to `.craft.yml`

- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
Replace awaitility with CountDownLatch to try and fix the test on CI
> Replace awaitility with CountDownLatch to try and fix the test on CI

- CHANGELOG.md
link to migration guide where possible and also at the top
fix exra -> extra
also updated https://github.com/getsentry/sentry-java/releases/tag/8.0.0
> Improve v8 changelog

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
Avoid logging an error when a float is passed in the manifest
https://github.com/getsentry/sentry-java/pull/3823 added support for integer values in the manifest.
But that's used as default value when parsing floats. This means that all float values are evaluated as integers and floats, causing one of the checks to fail.
Everything still works correctly, but when the type is wrong, the error is logged in the logcat.
This PR avoids the log if the value passed in the manifest is a float
Closes https://github.com/getsentry/sentry-android-gradle-plugin/issues/803
> Avoid logging an error when a float is passed in the manifest

- CHANGELOG.md
- sentry/src/main/java/io/sentry/opentelemetry/OpenTelemetryUtil.java
Use `NoOpLogger` for `LoadClass` when searching for OpenTelemetry marker classes to determine if Sentry OpenTelemetry dependencies / agent are present.
It's not a nice experience to start the SDK without OpenTelemetry and be greeted with a wall of stacktraces when `debug` is enabled.
```
DEBUG: Class not available:io.sentry.opentelemetry.agent.AgentMarker
java.lang.ClassNotFoundException: io.sentry.opentelemetry.agent.AgentMarker
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:421)
at …
```
> Remove debug logs when searching for OpenTelemetry marker classes

- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
RateLimiterTest `close cancels the timer`  was flaky
Now it uses reflection to assert the timer was cancelled
> Fix flaky RateLimiter test

- CHANGELOG.md
- sentry-spring-boot-jakarta/src/test/kotlin/io/sentry/spring/boot/jakarta/SentryAutoConfigurationTest.kt
- sentry-spring-boot/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/util/ErrorUtils.java
- sentry/src/main/java/io/sentry/util/ExceptionUtils.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
Adds an option `ignoredErrors` (called `ignoreErrors` in other SDKs) to ignore Errors matching a certain String or Regex
Closes #3471 
Unit tests for Client, Options and ExternalOptions
> Add `options.ignoredErrors` accepting String and Regex

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-webflux-jakarta/build.gradle.kts
Bump Spring Boot to `3.4.2`
Have CI run against the latest version.
> Bump Spring Boot to `3.4.2`

- sentry/src/main/java/io/sentry/SentryOptions.java
Adds JavaDoc to some fields and methods in `SentryOptions`.
Closes #4101
> Add JavaDoc to `SentryOptions.ignoredTransactions,ignoredSpanOrigins,ignoredCheckIns`

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryExceptionFactory.java
- sentry/src/test/java/io/sentry/SentryExceptionFactoryTest.kt
Set mechanism `type` to `suppressed` for suppressed exceptions so customers can distinguish exceptions causes from suppressed exceptions.
Closes https://github.com/getsentry/sentry-java/issues/4059
> Set mechanism `type` to `suppressed` for suppressed exceptions

- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OpenTelemetryAttributesExtractor.java
Use `java.net.URL` for combining url attributes
> Use `java.net.URL` for combining url attributes

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/opentelemetry/OpenTelemetryUtil.java
Log debug messages giving info about OpenTelemetry related config settings
example output
```
DEBUG: openTelemetryMode has been inferred from AUTO to AGENT
INFO: Initializing SDK with DSN: 'https://502f25099c204a2fbf4cb16edc5975d1@o447951.ingest.sentry.io/5428563'
...
DEBUG: Using openTelemetryMode AGENT
DEBUG: Using span factory io.sentry.opentelemetry.OtelSpanFactory
DEBUG: Using scopes storage io.sentry.opentelemetry.OtelContextScopesStorage
...
```
> Log debug messages giving info about OpenTelemetry related config settings

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Sentry.java
We're now passing a `NoOpLogger` to `ScopesStorageFactory` so it doesn't log `java.lang.ClassNotFoundException: io.sentry.opentelemetry.OtelContextScopesStorage` if the class isn't available.
Fixes https://github.com/getsentry/sentry-java/issues/4094
> Do not log if `OtelContextScopesStorage` cannot be found

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-compose/build.gradle.kts
- sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryModifier.kt
- sentry-compose/src/androidUnitTest/kotlin/io/sentry/compose/SentryModifierComposeTest.kt
Cherry-picked #4029 onto the main branch
> Cherry-pick: Modifier.sentryTag uses Modifier.Node (#4029)

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/IDebugImagesLoader.java
- sentry-android-core/src/main/java/io/sentry/android/core/NoOpDebugImagesLoader.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry-android-ndk/api/sentry-android-ndk.api
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/DebugImagesLoader.java
- sentry-android-ndk/src/test/java/io/sentry/android/ndk/DebugImagesLoaderTest.kt
Backport of https://github.com/getsentry/sentry-java/pull/4089 for 7.x.x
cc @buenaflor
> feat(android-ndk): add api for getting debug images by addresses

- .github/workflows/build.yml
- .github/workflows/system-tests-backend.yml
- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- buildSrc/src/main/java/Publication.kt
- gradle.properties
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-navigation/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-replay/build.gradle.kts
- sentry-android-sqlite/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-compose/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-agent/build.gradle.kts
Follow up to #3936
When running `./gradlew build` there were still some leftovers that resulted in config cache errors, so this PR just fixes them.
> Fix config cache for build command

- CHANGELOG.md
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
Closes https://github.com/getsentry/sentry-java/issues/3817
> Log a warning when envelope or items are dropped due to rate limiting

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidContinuousProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/ProfileChunk.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/JsonSerializerTest.kt
- sentry/src/test/java/io/sentry/ScopesTest.kt
- sentry/src/test/java/io/sentry/SentryClientTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
Last changes in order to have working continuous profiling on Android.
Notable change: chunk duration is now increased to 60 seconds
There is still a frontend fix that needs to be deployed before testing it out completely
Last part of https://github.com/getsentry/sentry-java/pull/3710
> Wrap up continuous profiling 

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryOptions.java
Remove internal annotation
Since this is a documented option it shouldn't be marked internal.
> `options.tracePropagationTargets` should not be internal

- CHANGELOG.md
> Mention ip-address change in 7.21.0 changelog as well

- CONTRIBUTING.md
> chore(contributing): Update contributing guide

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/util/AndroidConnectionStatusProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidConnectionStatusProviderTest.kt
We don't seem to be able to get rid of calling `getConnectionStatus()` on connectivity change, as the NetworkCallback seems to fire for any network, e.g. reporting a disconnect of WIFI, although Cellular connection is still available.
But I noticed every internal `IConnectionStatusObserver` was tied to it's own `NetworkCallback`, causing us to call `getConnectionStatus()` per change per observer - which quickly blows our number of IPC calls up.
So instead let's have a single `NetworkCallback`, call `getConnectionStatus()` once per network change and then broadcast the state to all observers. This should already reduce the number of IPC calls by 3.
Less IPC calls
Fixes https://github.com/getsentry/sentry-java/issues/4053
> Move to a single NetworkCallback listener to reduce number of IPC calls

- .craft.yml
As this is now done within sentry-native
Relevant sentry-native PR: https://github.com/getsentry/sentry-native/pull/1155
> chore(craft): Remove symbol collector step

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/config/PropertiesProvider.java
- sentry/src/test/java/io/sentry/ExternalOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
Fix `ignoredErrors`, `ignoredTransactions` and `ignoredCheckIns` being unset by external options if not present in any external config mechanism.
Fixes #4205
> Fix `ignoredErrors`, `ignoredTransactions` and `ignoredCheckIns` being unset by external options

- CHANGELOG.md
- sentry-jul/api/sentry-jul.api
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
Add another constructor to `SentryHandler` that allows passing `enableExternalConfiguration` to disable parsing of external configuration (by passing `false`). This defaults to `true` when using other constructors.
Came up in https://github.com/getsentry/sentry-java/issues/4205 where Quarkus is trying to disable parsing of external config like `sentry.properties` or ENV vars.
> Add constructor to JUL `SentryHandler` for disabling external config

- CHANGELOG.md
- sentry/src/main/java/io/sentry/FilterString.java
- sentry/src/test/java/io/sentry/FilterStringTest.kt
Fix exception when creating FilterString from string that cannot be parsed as regex.
This was the case e.g. for `ignoredErrors`, `ignoredTransactions`, `ignoredCheckIns`
Catch exception from `Pattern.compile` and skip using the pattern in that case.
Fixes https://github.com/getsentry/sentry-java/issues/4212
> Filter strings that cannot be parsed as Regex no longer cause an SDK crash

- sentry-android-core/src/main/java/io/sentry/android/core/CurrentActivityIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-openfeign/src/main/java/io/sentry/openfeign/SentryFeignClient.java
- sentry/src/main/java/io/sentry/SpotlightIntegration.java
Reports a couple more integrations that we were not capturing
Closes #2771
> Report missing integrations

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
We officially support it [according to our docs](https://docs.sentry.io/platforms/android/configuration/options/#in-app-include), but actually it's not implemented.
Fixes https://github.com/getsentry/sentry-java/issues/2617
Added tests
> Add support for setting in-app-includes/in-app-excludes via AndroidManifest.xml

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PerformanceAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryPerformanceProviderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/performance/AppStartMetricsTest.kt
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
Fix Ensure app start type is set, even when ActivityLifecycleIntegration is not running or init is deferred.
Fixes https://github.com/getsentry/sentry-react-native/issues/4598
> Fix Ensure app start type is set, even when ActivityLifecycleIntegration is not running

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java
- sentry-android-core/src/test/java/io/sentry/android/core/performance/AppStartMetricsTest.kt
As otherwise they would happen before application init.
> Fix properly reset application/content-provider timespans

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OpenTelemetryAttributesExtractor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OtelInternalSpanDetectionUtil.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/OpenTelemetryAttributesExtractorTest.kt
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/OtelInternalSpanDetectionUtilTest.kt
- sentry/src/main/java/io/sentry/DsnUtil.java
- sentry/src/test/java/io/sentry/DsnUtilTest.kt
We now check the hostname and port to see if a request is being made to Sentry.
When running tests, we set the DSN to a localhost URL which then disabled injection of tracing information for requests that also go to localhost.
> Also use port when checking if a request is made to Sentry DSN

- CHANGELOG.md
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt
- sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpInterceptor.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpEventTest.kt
- sentry-okhttp/src/test/java/io/sentry/okhttp/SentryOkHttpInterceptorTest.kt
Makes span/breadcrumb data mutable, so we can update it whenever the underlying http request changes.
Unfortunately the okhttp `EventListener` always gets the _original_ request in most of it's callbacks, even though interceptors have changed the request already. Only when a response is received (e.g. `responseHeadersStart()`) the `response.request.call` would contain the actual request, which probably isn't always called due to caching / errors, etc..
Thus we need to wire the update logic into our interceptor instead - and assume it's running last in the chain.
Fixes https://github.com/getsentry/sentry-java/issues/3610
> Propagate modifications of OkHttp requests to the affected spans / breadcrumbs

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SamplingContext.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
`SamplingContext` now has a `getAttribute` method granting access to OpenTelemetry span attributes when Sentry is used in OpenTelemetry mode.
Fixes #4192
> Pass OpenTelemetry span attributes into TracesSampler callback

- CHANGELOG.md
- sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryModifier.kt
https://github.com/getsentry/sentry-java/pull/4255 for 7.x.x
> Fix AbstractMethodError when using SentryTraced for Jetpack Compose (7.x.x)

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SpanDescriptionExtractor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/SpanDescriptionExtractorTest.kt
When extracting span description, assume it's `http.client` if the span is not a root span (invalid or remote parent).
Fixes #3904
> Assume `http.client` for span `op` if not a root span

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidContinuousProfiler.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidContinuousProfilerTest.kt
- sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MyApplication.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/HubScopesWrapper.java
- sentry/src/main/java/io/sentry/IContinuousProfiler.java
- sentry/src/main/java/io/sentry/IScopes.java
- sentry/src/main/java/io/sentry/NoOpContinuousProfiler.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpScopes.java
- sentry/src/main/java/io/sentry/ProfileLifecycle.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/ScopesAdapter.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryTracer.java
- sentry/src/test/java/io/sentry/HubAdapterTest.kt
- sentry/src/test/java/io/sentry/NoOpContinuousProfilerTest.kt
- sentry/src/test/java/io/sentry/NoOpHubTest.kt
- sentry/src/test/java/io/sentry/ScopesAdapterTest.kt
- sentry/src/test/java/io/sentry/ScopesTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
Renamed
Sentry.startProfileSession -> Sentry.startProfiler
Sentry.stopProfileSession -> Sentry.stopProfiler
Renaming APIs to avoid confusion with sessions and sample rates
> Change continuous profiling API names

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- Check for NoOpInstance before setting the defaults
Closes #2565 
unit tests
> fix(sdk-init): Do not override user-defined SentryOptions

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/capture/SessionCaptureStrategyTest.kt
Cherry-pick #4185 onto `7.x.x` for RN https://github.com/getsentry/sentry-react-native/issues/4659
> fix(session-replay):  Do not crash if navigation breadcrumb has no destination (#4185)

- CHANGELOG.md
- sentry/src/main/java/io/sentry/SentryOptions.java
To have a better chance of envelopes being sent without retry
> chore(http-client): Increase http timeouts from 5s to 30s

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
An attempt to fix SIGSEGV which seems to be happening when we stop the replay after 30s the app has been backgrounded. I traced it down to [this call](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/libs/hwui/jni/Bitmap.cpp;l=47) which is where the exception `(SkColorInfo::operator=(SkColorInfo const&)+32)` is happening. This `mInfo` is set from the `Bitmap.Config` value that we pass upon constructing a bitmap. My theory is that it doesn't work well with the `RGB_565` config, especially when we're reusing the same bitmap to capture screenshots.
Also it could be a combination of RN and some device vendors having tweaks to the AOSP code, not sure.
Fixes #4228 
no way to test this sadly as I couldn't reproduce on my devices
> fix(replay): Change bitmap config to `ARGB_8888` for screenshots

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
Cherry-pick https://github.com/getsentry/sentry-java/pull/4282 onto 7.x.x for RN
> fix(replay): Change bitmap config to `ARGB_8888` for screenshots (#4282)

- CHANGELOG.md
> chore(changelog): Re-apply 7.22.5 changelog

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryEnvelopeItem.java
- sentry/src/main/java/io/sentry/SentryEnvelopeItemHeader.java
- sentry/src/test/java/io/sentry/SentryEnvelopeItemTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryEnvelopeItemHeaderSerializationTest.kt
- sentry/src/test/resources/json/sentry_envelope_item_header.json
Added `platform` to SentryEnvelopeItemHeader
Added platform "android" in ProfileChunk envelope items
Implements client side of https://github.com/getsentry/team-ingest/issues/679
We want to rate limit UI and backend profile chunks differently.
In order to avoid having to maintain a list of sdk names, we are required to send the platform in the item header.
Unit tests
> added `platform` to SentryEnvelopeItemHeader

- CHANGELOG.md
- sentry-android-core/src/test/java/io/sentry/android/core/InternalSentrySdkTest.kt
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/SentrySpanProcessorTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/Baggage.java
- sentry/src/main/java/io/sentry/PropagationContext.java
- sentry/src/main/java/io/sentry/Scope.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/TransactionContext.java
- sentry/src/main/java/io/sentry/util/TracingUtils.java
- sentry/src/test/java/io/sentry/BaggageTest.kt
- sentry/src/test/java/io/sentry/SpanContextTest.kt
- sentry/src/test/java/io/sentry/TransactionContextTest.kt
- sentry/src/test/java/io/sentry/util/TracingUtilsTest.kt
Keeps the rate / rand values as doubles, until being transferred to `TraceContext`.
We seem to be hitting some performance regression with 8.x.x where formatting the sample rate/rand seems to have some impact. I don't trust the profiled app fully, be there seems to be something to it:
Before:
After:
TODO: Check why this even being called 3 times (assuming it's for every scope right now)
> Keep baggage sample rate/rand as doubles

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryClient.java
- sentry/src/main/java/io/sentry/SentryIntegrationPackageStorage.java
Changelog is written in a follow up PR
- Checks `SentryIntegrationPackageStorage.packages` for mixed versions when sending out an envelope.
- Caches the decision so the check is only performed once*
- * invalidates the cache when a new package is added
This is only the first step where we log when mixed versions have been detected.
Next step is to not enable the SDK in that case.
First step for solving https://github.com/getsentry/sentry-java/issues/4132
> Check for mixed SDK versions

- CHANGELOG.md
- sentry/src/main/java/io/sentry/IScopes.java
- sentry/src/main/java/io/sentry/ISentryClient.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/transport/ITransport.java
`Sentry.flush` as well as other `flush` methods had a comment saying "Not yet implemented" which is no longer true.
Fixes https://github.com/getsentry/sentry-java/issues/4304
> Remove "not yet implemented" from flush comments

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryPerformanceProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/ExperimentalOptions.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/test/java/io/sentry/ScopeTest.kt
- sentry/src/test/java/io/sentry/ScopesTest.kt
- sentry/src/test/java/io/sentry/SentryOptionsTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/SentryTracerTest.kt
- sentry/src/test/java/io/sentry/TracesSamplerTest.kt
moved continuous profiling out of `ExperimentalOptions` back into `SentryOptions`
Continuous Profiling is about to GA
> Continuous Profiling - Out of Experimental

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/EnvelopeTests.kt
As a follow-up to https://github.com/getsentry/sentry-java/pull/4298
> Add test to verify transactions from sentry-native are sent to relay

- CHANGELOG.md
Updated changelog with UI Profiling notes
> updated changelog with UI Profiling notes

- CHANGELOG.md
- sentry/src/main/java/io/sentry/util/ClassLoaderUtils.java
Prioritizes the thread context classloader over the system classloader when the bootstrap classloader is null.
This ensures correct resource loading in environments like Spring Boot where the thread context classloader is used for resource loading.
Fixes https://github.com/getsentry/sentry-java/issues/4318
Manually
> Use thread context classloader when available

- CHANGELOG.md
- sentry-android-core/api/sentry-android-core.api
- sentry-android-core/src/main/java/io/sentry/android/core/ContextUtils.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/ContextUtilsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
If you launch a Jetpack Compose Preview for a `@Composable` within a library, the library will be packaged as an app (`androidTest` flavor) and the Compose Tooling will add a [preview activity](https://developer.android.com/reference/kotlin/androidx/compose/ui/tooling/PreviewActivity).
If the library has a dependency to Sentry, this will cause the preview-app to crash, as typically no DSN is set within the library and our SDK will try to auto-init.
There's no easy way around this, but we can detect at runtime if the app is a preview app.
Fixes https://github.com/getsentry/sentry-java/issues/2904
Added unit tests.
> Fix do not initialize SDK for Jetpack Compose Preview builds

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegrationTest.kt
- `onLowMemory` is a deprecated API and should not be used in conjunction with `onTrimMemory`
- Move the `level` check out of the runnable lambda, so we don't even enqueue a task if the level is not suitable for reporting
- Debounce low memory breadcrumbs by minute
> fix(breadcrumbs): Improve low memory breadcrumb capturing

- sentry-kotlin-extensions/src/main/java/io/sentry/kotlin/SentryCoroutineExceptionHandler.kt
Forgot to push this in https://github.com/getsentry/sentry-java/pull/4259
> Add `handled=true` to `SentryCoroutineExceptionHandler`

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegrationTest.kt
The PR attempts to make `SystemEventsBreadcrumbsIntegration` faster by:
- Using a fixed-size array for storing default actions we're subscribing for
- This will avoid growing (previously unbounded) array list
- But also will avoid allocating a new iterator in the for-loop
- Improve `getStringAfterDot` by using a pre-allocated buffer and iterating from the end of the string until the first dot to create a String after that. This yielded ~2x faster results on Android (10k iterations x 3 times):
> perf(breadcrumbs): Make SystemEventsBreadcrumbsIntegration faster

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ActivityLifecycleIntegrationTest.kt
Sentry.reportFullyDisplayed now sets a flag if the ttid is not finished. 
When the TTID finishes, if the flag is set, the TTFD is finished as well
Fixes https://github.com/getsentry/sentry-java/issues/3384
Unit tests
> Fix TTFD measurement when API called too early

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryWrapper.java
- sentry/src/test/java/io/sentry/SentryWrapperTest.kt
Wrap `Runnable` for usage with Sentry, e.g. when using virtual threads
Closes https://github.com/getsentry/sentry-java/issues/4328
> Wrap `Runnable` for usage with Sentry

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/SessionTrackingIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegrationTest.kt
Android 14 introduced new behavior for broadcast receivers, and our SystemEvents receiver (used to add breadcrumbs like screen on/off, airplane mode change, etc.) is falling under this. What's happening is the process gets cached for some period of time (can be hours or days) and after getting uncached it receives all those pending broadcasts in a quick succession which most likely causes ANRs. This also correlates with the numbers we see in SDKCD where the biggest number of ANRs is coming from Android 14+. 
I did some tests locally and it is indeed happening as described on the screenshot. 
---
- `SystemEventsBreadcrumbsIntegration` is now lifecycle-aware:
-  When an app enters background we unregister the receiver
-  When it enters foreground back, we enqueue a task to register the …
> fix(breadcrumbs): Unregister SystemEventsBroadcastReceiver when entering background

- CHANGELOG.md
- scripts/toggle-codec-logs.sh
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/internal/debugmeta/AssetsDebugMetaLoader.java
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
- sentry-samples/sentry-samples-android/build.gradle.kts
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/JsonObjectWriter.java
- sentry/src/main/java/io/sentry/ObjectWriter.java
- sentry/src/main/java/io/sentry/ProfileChunk.java
- sentry/src/main/java/io/sentry/ProfilingTraceData.java
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
- sentry/src/main/java/io/sentry/cache/CacheUtils.java
- sentry/src/main/java/io/sentry/util/LoadClass.java
- sentry/src/main/java/io/sentry/util/MapObjectWriter.java
- sentry/src/main/java/io/sentry/vendor/gson/stream/JsonWriter.java
- Introduce new `debug` option under the session replay sub-options. This controls verbose logging of Session Replay-specific code paths.
- Introduce a bash script that disables/enables system logs via `adb shell`
- Hook the script via a Gradle task which reads the `session-replay.debug` manifest option and runs the script for the sample app
- Reduce log levels for some logs
- Get rid of printing Throwables with stacktraces for logs where it's expected to fail in some cases (e.g. no Compose dependency)
- Change `indent` when serializing Profiles' measurements, because the list is too big and makes logcat unreadable
Fixes #4307 
Fixes https://github.com/getsentry/sentry-dart/issues/2673
Existing tests should cover it
The script I tested manually
> fix(logging): Reduce debug logs verbosity

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/ViewUtils.java
- sentry-compose/proguard-rules.pro
- sentry-compose/src/androidMain/kotlin/io/sentry/compose/SentryComposeHelper.kt
- sentry-compose/src/androidMain/kotlin/io/sentry/compose/gestures/ComposeGestureTargetLocator.kt
- Use `class.getName` instead of `class.getCanonicalName` as it's almost ~2x faster, and there's almost no difference in what it returns except for inner classes (tested 10k iterations over 10 times)
- Fix `SentryTag` extraction for compose, because `SentryTagModifierNodeElement` is an inner class and we have to use a dollar-sign to properly get its class name.
- Use `fori` instead of `foreach` loop to avoid allocating an Iterator in hot paths (e.g. when traversing the view hierarchy which can happen 100s of times for complex UIs). Reduced allocations by almost 2x doing the same user flow (launch -> scroll -> button click)
Improve perf of user interaction tracing
existing tests
> perf(user-interactions): Make user interaction tracing faster and allocate less

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/internal/modules/AssetsModulesLoader.java
- sentry/src/main/java/io/sentry/internal/modules/ModulesLoader.java
- Pre-load modules on a background thread upon initialization so we don't need to load them when an error/crash happens (could be on the main thread)
- Fix `cachedModules` were not thread-safe
An actual ANR from GPC originating in `UncaughtExceptionHandler`
https://play.google.com/sdk-console/accounts/3062283563667932501/sdks/5766124106675877123/crashes/44125318/details
Manually + existing tests
- [] I added tests to verify the changes.
> perf(modules): Pre-load modules on a background thread

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidContinuousProfiler.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidContinuousProfilerTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/DataCategory.java
- sentry/src/main/java/io/sentry/SentryItemType.java
- sentry/src/main/java/io/sentry/clientreport/ClientReportRecorder.java
- sentry/src/main/java/io/sentry/transport/RateLimiter.java
- sentry/src/test/java/io/sentry/transport/RateLimiterTest.kt
update rate limiting and client reports for profile chunks from `profile_chunk` to `profile_chunk_ui`
Rate limiting is different for UI and backend profiling, so they have different keys
> Update profile chunk rate limit and client report

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-bootstrap/src/main/java/io/sentry/opentelemetry/SentryContextStorageProvider.java
Use SPI to search for other `ContextStorageProvider`s and wrap them instead of using `SentryOtelThreadLocalStorage`
Closes https://github.com/getsentry/sentry-java/issues/4339
> Wrap configured `ContextStorageProvider` if available

- .github/ISSUE_TEMPLATE/bug_report_android.yml
- .github/ISSUE_TEMPLATE/bug_report_java.yml
- .github/ISSUE_TEMPLATE/feature_android.yml
- .github/ISSUE_TEMPLATE/feature_java.yml
- .github/ISSUE_TEMPLATE/maintainer-blank.yml
> Update GH issue templates for Linear compatibility

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/RequestDetailsResolver.java
Follow up to https://github.com/getsentry/sentry-java/pull/4323
This makes `RequestDetailsResolver` public and adds a constructor which just takes the a DSN and client name.
`ITransportFactory.create` currently [receives](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/ITransportFactory.java#L17) a `RequestDetails`. This means that, when creating a custom transport, you can't change the request details (dsn, auth header, ..) without resorting to ugly rewrites on the url / headers.
Having a public `RequestDetailsResolver` makes it easy to make a new instance with the desired DSN / client name.
Use case (from https://github.com/getsentry/sentry-java/pull/4323) is to make a transport that can send to multiple different DSNs. (Somewhat simplified) example …
> Make RequestDetailsResolver public

- README.md
As far as I can tell the Android NDK support was moved from sentry-java to sentry-native in #3189 and since then sentry-java has not had submodules.
Pure docs change so no tests.
> Remove mention of sentry-native submodule

- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/Recorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/Windows.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationWithRecorderTest.kt
> fix(replay): Fix window tracking

- buildSrc/src/main/java/Config.kt
- gradle/libs.versions.toml
- sentry-android-core/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android-critical/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-navigation/build.gradle.kts
- sentry-android-replay/build.gradle.kts
- sentry-compose/build.gradle.kts
- sentry-samples/sentry-samples-android/build.gradle.kts
Continue adopting version catalog
> Move compose deps to version catalog

- sentry/src/main/java/io/sentry/SentryLogEventAttributeValue.java
- sentry/src/test/java/io/sentry/protocol/SentryLogsSerializationTest.kt
- sentry/src/test/resources/json/sentry_logs.json
Ensures we stringify objects properly and adds attributes of other types to the de/serialization test.
> Ensure that log attributes of Object type are stringified

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryAttribute.java
- sentry/src/main/java/io/sentry/SentryAttributeType.java
- sentry/src/main/java/io/sentry/SentryAttributes.java
- sentry/src/main/java/io/sentry/SentryLogEventAttributeValue.java
- sentry/src/main/java/io/sentry/logger/ILoggerApi.java
- sentry/src/main/java/io/sentry/logger/LogParams.java
- sentry/src/main/java/io/sentry/logger/LoggerApi.java
- sentry/src/main/java/io/sentry/logger/NoOpLoggerApi.java
- sentry/src/main/java/io/sentry/logger/SentryLogParameters.java
- sentry/src/test/java/io/sentry/ScopesTest.kt
Improve Log Attributes API:
- Add `Sentry.logger().log()` overload that takes a `LogParams` param object
- This avoids having tons of overloads and creating a large pyramid of methods
- Having multiple overloads is especially problematic with varargs since it can easily become ambiguous
- Add `SentryAttributes` and `SentryAttribute`
- `SentryAttributeType` enum
> Improve Log Attributes API

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryAttribute.java
- sentry/src/main/java/io/sentry/SentryAttributeType.java
- sentry/src/main/java/io/sentry/SentryAttributes.java
- sentry/src/main/java/io/sentry/SentryLogEventAttributeValue.java
- sentry/src/main/java/io/sentry/logger/ILoggerApi.java
- sentry/src/main/java/io/sentry/logger/LoggerApi.java
- sentry/src/main/java/io/sentry/logger/NoOpLoggerApi.java
- sentry/src/main/java/io/sentry/logger/SentryLogParameters.java
- sentry/src/test/java/io/sentry/ScopesTest.kt
- sentry/src/test/java/io/sentry/protocol/SentryLogsSerializationTest.kt
- sentry/src/test/resources/json/sentry_logs.json
Extend Logs API to allow passing in `attributes`
Filtering Logs in Sentry via custom attributes.
> Extend Logs API to allow passing in `attributes`

- buildSrc/src/main/java/Config.kt
- gradle/libs.versions.toml
- sentry-android-core/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android-benchmark/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-replay/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-compose/build.gradle.kts
- sentry-jdbc/build.gradle.kts
- sentry-openfeign/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-agentcustomization/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-bootstrap/build.gradle.kts
- sentry-opentelemetry/sentry-opentelemetry-core/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-jakarta/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry-noagent/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot-opentelemetry/build.gradle.kts
- sentry-samples/sentry-samples-spring-boot/build.gradle.kts
- sentry-servlet-jakarta/build.gradle.kts
- sentry-servlet/build.gradle.kts
- sentry-spring-jakarta/build.gradle.kts
- sentry-spring/build.gradle.kts
- sentry/build.gradle.kts
> Move remaining testLib dependencies to version catalog

- CHANGELOG.md
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OtelSentryPropagator.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/OtelSentrySpanProcessor.java
- sentry-opentelemetry/sentry-opentelemetry-core/src/test/kotlin/OtelSentryPropagatorTest.kt
Fork isolation scope for root spans in `OtelSentrySpanProcessor` instead of `OtelSentryPropagator`.
- Fixes https://github.com/getsentry/sentry-java/issues/4430
- Propagator is no longer required for proper scope forking.
- `Sentry.startTransaction` (via `OtelSpanFactory`) was also affected and did not fork isolation scope.
- Also if `sentry-trace` header can't be parsed we now still fork isolation scope
> Fork isolation scope for root spans in `OtelSentrySpanProcessor` instead of `OtelSentryPropagator`

- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/HubScopesWrapper.java
- sentry/src/main/java/io/sentry/util/ScopesUtil.java
Add `ScopesUtil.printScopesChain` for debugging what the chain of `Scopes` looks like by traversing the `parent` and printing `Scopes` and `Scope` object IDs as well as `creator` string.
Looks like this:
```
==========================================
=============== v Scopes v ===============
==========================================
io.sentry.Scopes@4a8d50aa {g=io.sentry.Scope@58dbf263 , i=io.sentry.Scope@75d0c553 , c=io.sentry.Scope@77699062 } [contextwrapper.scopeincontext]
io.sentry.Scopes@6711e5b2 {g=io.sentry.Scope@58dbf263 , i=io.sentry.Scope@75d0c553 , c=io.sentry.Scope@47b9e1fa } [contextwrapper.spanancestor]
io.sentry.Scopes@34b05e03 {g=io.sentry.Scope@58dbf263 , i=io.sentry.Scope@75d0c553 , c=io.sentry.Scope@f613277  } [spanprocessor.rootspan] …
```
> Add `ScopesUtil.printScopesChain` for debugging

- buildSrc/src/main/java/Config.kt
- sentry-spring-jakarta/build.gradle.kts
Use `graphql-java` v24 for Spring Boot 3.5
Compilation error due to v22 of `graphql-java` being used.
> Use `graphql-java` v24 for Spring Boot 3.5

- buildSrc/src/main/java/Config.kt
- gradle/libs.versions.toml
- sentry-android-core/build.gradle.kts
- sentry-android-fragment/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android-benchmark/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android-critical/build.gradle.kts
- sentry-android-integration-tests/sentry-uitest-android/build.gradle.kts
- sentry-android-sqlite/build.gradle.kts
- sentry-compose/build.gradle.kts
- sentry-samples/sentry-samples-android/build.gradle.kts
Version catalog adoption cont'd
> Migrate Androidx dependencies to version catalog

- scripts/update-sentry-native-ndk.sh
- The script has been [failing](https://github.com/getsentry/sentry-java/actions/runs/15439442783/job/43453544853) after migrating to `libs.versions.toml`, so this fixes it  
Manually ran `update-sentry-native-ndk.sh set-version 0.8.5` and `get-version`
> fix(ci): Fix update-sentry-native-ndk script to work with libs.versions.toml

- sentry-android-replay/api/sentry-android-replay.api
- sentry-android-replay/src/main/java/io/sentry/android/replay/Recorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/ReplayIntegration.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BaseCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/BufferCaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/CaptureStrategy.kt
- sentry-android-replay/src/main/java/io/sentry/android/replay/capture/SessionCaptureStrategy.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplayIntegrationWithRecorderTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/ReplaySmokeTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/capture/BufferCaptureStrategyTest.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/capture/SessionCaptureStrategyTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/SentryReplayOptions.java
As we anyway have `onConfigurationChanged` now. This removes the need for odd constructs like this one
```Kotlin
captureStrategy?.let { capture ->
if (capture.currentReplayId == SentryId.EMPTY_ID) {
capture.start(recorderConfig)
} else {
capture.onConfigurationChanged(recorderConfig)
}
}
```
> [SR] Remove configuration from start() method

- build-logic/src/main/kotlin/io.sentry.javadoc.aggregate.gradle.kts
Add `s` to the name of the task as we seem to be referencing `aggregateJavadocs` everywhere.
`make format` and `./gradlew aggregateJavadocs` failed without this change.
> Fix `aggregateJavadocs` task name

- CHANGELOG.md
- sentry/src/main/java/io/sentry/logger/LoggerBatchProcessor.java
Check item count before invoking `SentryClient.captureBatchedLogEvents`
`LoggerBatchProcessor` sent out empty envelopes which
- caused problems in relay (which have already been fixed)
- is unnecessary work
> No longer send out empty log envelopes

- gradle.properties
> ALL THE CORES

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/video/SimpleVideoEncoder.kt
This applies the T606 chipset fix for all spreadtrum/unisoc chipsets because there are still crashes coming from e.g. this [device](https://www.gsmarena.com/tecno_spark_go_1-13274.php) which has a T615 chip
See replay: https://sentry-sdks.sentry.io/replays/f7d9309ffba843e68ff9c6285ab84970/
Internal customer reports
Manually
> fix(replay): Expand fix for crash on devices to all Unisoc/Spreadtrum chipsets

- codecov.yml
We suspect the code coverage report is coming from the cache and
therefore older than 12h. This should allow us to pass.
> Ignore Codecov report age

- .git-blame-ignore-revs
> Add git blame ignore revs for spotless ktfmt

- CHANGELOG.md
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
Use `ScopesAdapter.getInstance().getOptions()` instead of `this.options` as Spring Boot config does not affect the instances options.
Fixes https://github.com/getsentry/sentry-java/issues/4521
> Fix Logback with Spring Boot

- CHANGELOG.md
- sentry/src/main/java/io/sentry/transport/TransportResult.java
`ITransport.send` doesn't return a `TransportResult` anymore since [we optimized it for high throughput](https://github.com/getsentry/sentry-java/pull/1114).
Closes https://github.com/getsentry/sentry-java/issues/4522
> Fix javadoc on TransportResult

- CHANGELOG.md
- sentry-android-replay/src/main/java/io/sentry/android/replay/util/Views.kt
- sentry-android-replay/src/test/java/io/sentry/android/replay/util/ViewsTest.kt
Apparently `width` and `height` can return negative values, so our != 0 check was not enough 
https://sentry.sentry.io/issues/6713535878/events/318005d8a00a468abccdd5f4f5576f28/
With tests
> fix(replay): Fix `IllegalArgumentException` when `Bitmap` is initialized with non-positive values

- CHANGELOG.md
- sentry-spring-boot-starter-jakarta/build.gradle.kts
Close https://github.com/getsentry/sentry-java/issues/4544
> Use Spring Boot Starter 3 in `sentry-spring-boot-starter-jakarta`

- .cursor/rules/coding.mdc
Adds coding rules configuration for Cursor IDE that includes:
- Project overview and tech stack information
- Key gradle commands for development workflow
- Contributing guidelines and coding standards
- Development process and formatting requirements
This helps maintain consistency in the development environment and provides quick reference for common project commands.
Manual
> feat(dev): Add Cursor IDE coding rules configuration

- CHANGELOG.md
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
- sentry-samples/sentry-samples-log4j2/src/main/resources/sentry.properties
Do not use Sentry logging API if logs are disabled
Fixes https://github.com/getsentry/sentry-java/issues/4571
> Do not use Sentry logging API in Log4j2 if logs are disabled

- sentry-opentelemetry/sentry-opentelemetry-agentcustomization/src/main/java/io/sentry/opentelemetry/SentryAutoConfigurationCustomizerProvider.java
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/internal/ManifestVersionReader.java
Remove indirection for integrations and packages via VersionInfoHolder
`ManifestVersionDetector` expects `ManifestVersionReader` to write to `SentryIntegrationPackageStorage` directly.
> Remove indirection for integrations and packages via VersionInfoHolder

- .github/workflows/release-build.yml
As they don't exist anymore and this is done within sentry-native directly: https://github.com/getsentry/sentry-native/pull/1327/files
> fix(ci): remove obsolete NDK debug symbols

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
Calling `Bundle.getSerializable(key)` without specifying the serializable class as a second argument [is considered unsafe](https://developer.android.com/privacy-and-security/risks/unsafe-deserialization). Luckily this was the only occurrence and the method wasn't even used, so we can just remove it.
> fix(android): Remove unused method

- .cursor/rules/offline.mdc
Add rules file for documenting SDK offline behaviour
Should help speed up AI reasoning about the SDK offline/retry behaviour.
> Add rules file for documenting SDK offline behaviour

- scripts/update-gradle.sh
Gradle now uses a proper [semver](https://gradle.org/whats-new/gradle-9/#:~:text=As%20you%20can%20see%2C%20we%20are%20switching%20to%20the%203%2Ddigit%20version%20format.%20Starting%20with%209.0.0%2C%20Gradle%20releases%20will%20follow%20the%20Semantic%20Versioning%20(SemVer)%20specification%20for%20all%20stable%20features%3B%0Aincubating%20features%20and%20internal%20APIs%20might%20have%20a%20different%20lifecycle.) for their versions, so we don't need the workaround for the missing patch version anymore
> fix(scripts): update-gradle script set-version

- sentry-android-core/src/main/java/io/sentry/android/core/AppState.java
- sentry-android-core/src/test/java/io/sentry/android/core/AppStateTest.kt
Just some minor nits:
- added @TestOnly getters
- Update internal state first before notifying listeners
- Add listeners before notifying them as well
Added unit tests.
> Improve callback handling and test visibility

- sentry-samples/sentry-samples-spring-boot-4/build.gradle.kts
- sentry-spring-boot-4/build.gradle.kts
OTEL doesn't support Spring Boot 4 yet, removing the dependency for now.
> Fix class not found due to OTel not supporting spring boot 4 yet

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/SentryLogcatAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryLogcatAdapterTest.kt
- sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
- sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
- sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/logger/LoggerApi.java
- sentry/src/main/java/io/sentry/logger/SentryLogParameters.java
Sends the `sentry.origin` attribute to Sentry.
For integrations this is set to e.g. `sentry.log.logcat`, `sentry.log.logback`, ...
The default is `manual`.
So we know what's creating logs.
> Add origin to logs

- CHANGELOG.md
- sentry/api/sentry.api
- sentry/src/main/java/io/sentry/MovePreviousSession.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/cache/EnvelopeCache.java
- sentry/src/test/java/io/sentry/MovePreviousSessionTest.kt
- sentry/src/test/java/io/sentry/SentryTest.kt
- sentry/src/test/java/io/sentry/cache/EnvelopeCacheTest.kt
- Previously, we were waiting on previous session flush latch on our background queue when processing ANRs or finalizing previous session for 15 seconds to give it a good chance to be flushed. However, the trigger for the flush was actually a new session start:
- We start a new session on foreground
- We see that there's an existing unfinished session
- We move it to its own file
- We flush the latch
However this was not working well for background app starts. Since there's no foreground event, a new session would not be started and we were waiting for 15 seconds for nothing (on a background thread, but still). So this PR addresses it by moving any unfinished session to its own file right away on `init` (but before any of the integrations are registered, so those that rely on the previous …
> fix(sessions): Move and flush unfinished previous session on init

- test/system-test-runner.py
Fixes CI to look for the version of Java agent we actually want to test (specified in `gradle.properties`).
Tests were failing most likely due to cached builds on CI that contained both 8.18.0 and 8.19.0 for the agent JAR and it kept using 8.18.0. This then caused mixed version detection to kick in and fail Spring Boot startup on the E2E tests.
> Fix agent JAR lookup

- .github/workflows/integration-tests-ui-critical.yml
Testing against a newer Android API-level in CI and dropping the oldest one. At the time the UI tests were added the most recent versions were selected, but since then new versions have been released.
We have experienced issues with the API level 30 in the UI tests critical action, resulting in our CI hanging. See the recent cancelled runs: https://github.com/getsentry/sentry-java/actions?query=is%3Acancelled
See related thread: https://github.com/ReactiveCircus/android-emulator-runner/issues/385
> Update API level in UI tests critical

- .sauce/sentry-uitest-android-benchmark-lite.yml
- .sauce/sentry-uitest-android-benchmark.yml
- .sauce/sentry-uitest-android-ui.yml
- sentry-android-integration-tests/sentry-uitest-android-benchmark/src/androidTest/java/io/sentry/uitest/android/benchmark/SentryBenchmarkTest.kt
Update Android benchmark configurations to include newer API levels and devices
increased number of benchmark runs to increase accuracy
increased passing threshold from 5% to 5.5%
Nightly benchmarks keep failing due to missing devices from saucelabs.
Also, they rarely fail for surpassing the threshold, but that's most likely a false positive. I increased the benchmark runs to reduce this possibility. The con is that the test takes a couple minutes longer
> Update benchmark tests and devices

- gradle/libs.versions.toml
- sentry-spring-7/build.gradle.kts
- sentry-spring-7/src/test/kotlin/io/sentry/spring7/mvc/SentrySpringIntegrationTest.kt
Spring Boot 4 M2 has been released, this PR bumps our used version and fixes some problems that showed up.
We should try to replace the explicit dependency version pin.
> Bump Spring Boot 4 to M2

- CHANGELOG.md
- sentry-jul/src/main/java/io/sentry/jul/SentryHandler.java
- sentry-jul/src/test/kotlin/io/sentry/jul/SentryHandlerTest.kt
- sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java
- sentry-log4j2/src/test/kotlin/io/sentry/log4j2/SentryAppenderTest.kt
- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
Only set template attribute for logging integrations if the formatted message differs from the template.
Closes https://github.com/getsentry/sentry-java/issues/4675
> Only set log template if message differs from template

- sentry/src/main/java/io/sentry/SentryOptions.java
The sampleRate is nullable and the setSampleRate method didn't have the `@Nullable` annotation.
This is fixed now.
> ref: Add Nullable for setSampleRate in Options

- CHANGELOG.md
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/HubAdapter.java
- sentry/src/main/java/io/sentry/HubScopesWrapper.java
- sentry/src/main/java/io/sentry/IScopes.java
- sentry/src/main/java/io/sentry/ISentryClient.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpScopes.java
- sentry/src/main/java/io/sentry/NoOpSentryClient.java
- sentry/src/main/java/io/sentry/ScopesAdapter.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryOptions.java
- sentry/src/main/java/io/sentry/logger/ILoggerApi.java
- sentry/src/main/java/io/sentry/logger/LoggerApi.java
- sentry/src/main/java/io/sentry/logger/NoOpLoggerApi.java
- sentry/src/main/java/io/sentry/logger/NoOpLoggerBatchProcessor.java
removed all @Experimental annotations from SentryLogs code
> Move SentryLogs out of experimental

- sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/SdkInitTests.kt
removed checking envelope sent while SDK restart from ui test, as it was flaky
> Fix double init UI test

- CHANGELOG.md
- sentry-spring-7/src/main/java/io/sentry/spring7/checkin/SentryCheckIn.java
- sentry-spring-7/src/main/java/io/sentry/spring7/checkin/SentryCheckInAdvice.java
- sentry-spring-7/src/main/java/io/sentry/spring7/checkin/SentryCheckInAdviceConfiguration.java
- sentry-spring-7/src/main/java/io/sentry/spring7/checkin/SentryCheckInPointcutConfiguration.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/checkin/SentryCheckIn.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/checkin/SentryCheckInAdvice.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/checkin/SentryCheckInAdviceConfiguration.java
- sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/checkin/SentryCheckInPointcutConfiguration.java
- sentry-spring/src/main/java/io/sentry/spring/checkin/SentryCheckIn.java
- sentry-spring/src/main/java/io/sentry/spring/checkin/SentryCheckInAdvice.java
- sentry-spring/src/main/java/io/sentry/spring/checkin/SentryCheckInAdviceConfiguration.java
- sentry-spring/src/main/java/io/sentry/spring/checkin/SentryCheckInPointcutConfiguration.java
- sentry/src/main/java/io/sentry/CheckIn.java
- sentry/src/main/java/io/sentry/CheckInStatus.java
- sentry/src/main/java/io/sentry/ExternalOptions.java
- sentry/src/main/java/io/sentry/HubScopesWrapper.java
- sentry/src/main/java/io/sentry/IScopes.java
- sentry/src/main/java/io/sentry/ISentryClient.java
- sentry/src/main/java/io/sentry/MonitorConfig.java
- sentry/src/main/java/io/sentry/MonitorContexts.java
- sentry/src/main/java/io/sentry/MonitorSchedule.java
- sentry/src/main/java/io/sentry/MonitorScheduleType.java
- sentry/src/main/java/io/sentry/MonitorScheduleUnit.java
- sentry/src/main/java/io/sentry/NoOpHub.java
- sentry/src/main/java/io/sentry/NoOpSentryClient.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/Sentry.java
- sentry/src/main/java/io/sentry/SentryClient.java
Removes `@ApiStatus.Experimental` from the whole Check-in API.
Keeps `@ApiStatus.Internal` where present.
Close #4673
> Remove ApiStatus.Experimental annotations from check-in API

- CHANGELOG.md
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry/src/main/java/io/sentry/Scopes.java
- sentry/src/main/java/io/sentry/SentryExecutorService.java
- sentry/src/main/java/io/sentry/SentryValues.java
- sentry/src/main/java/io/sentry/backpressure/BackpressureMonitor.java
- sentry/src/main/java/io/sentry/logger/LoggerBatchProcessor.java
- sentry/src/main/java/io/sentry/transport/QueuedThreadPoolExecutor.java
- Handle `RejectedExecutionException` on `submit` where it was previously unhandled
- Log the failure with `WARNING` level everywhere
- Change the signature of methods in `SentryExecutorService` to `throws RejectedExecutionException` (not sure if this is effective because it's a `RuntimeException` anyway)
- An alternative would be to handle the exception e.g. in the `submit` method itself of `SentryExecutorService`, but then we wouldn't throw it to the caller which can log a more specific message
- Change `deviceInfoUtil` to be nullable in `DefaultAndroidEventProcessor`. Upon accessing it, if it's null it will still trigger an NPE and log things like `options.getLogger().log(SentryLevel.ERROR, "Failed to retrieve device info", e);`
- Perhaps here it's better to check for null instead of …
> Handle `RejectedExecutionException` everywhere

- CHANGELOG.md
Expanded details on Sentry continuous profiling feature, including configuration options and default settings.
> Improve Profiling changelog entry

- CHANGELOG.md
- sentry/src/main/java/io/sentry/Sentry.java
Use the logger from options when loading and running the profiler.
Otherwise, you would log everything to stdout even if `debug: false`.
Close https://github.com/getsentry/sentry-java/issues/4772
Close JAVA-193
> Use logger from options for JVM profiler
